### ISSUE TITLE
v2 no longer downloads tags

### ISSUE THREAD

**Issue by charliebruce** [actions/checkout#100]
As of v2, tags are no longer available in the cloned repository, whereas previously tags would have been visible. I was caught out by this, as I was referencing this Action by `@master` rather than `@v1`.

Worth mentioning somewhere in the changelog?

**Comment by ericsciple** [comment]
i'll update the scenarios in the readme. v2 perf was optimized for the mainline to only fetch a single sha

**Comment by gitfool** [comment]
Rather than now requiring a separate `run` command to fetch tags, it would be much nicer to have a `fetch-tags` option. Default to `false` to preserve new behaviour, passing `—no-tags`, otherwise pass `—tags` when `true`.
