### ISSUE TITLE
What is the usage of post in runs in action.yml

### ISSUE THREAD

**Issue by DaHuoKolmostar** [actions/checkout#101]
I find the following line in action.yml, however I haven't found the meaning of 'post' in the documents. Would you please give me a hint of its meaning?

https://github.com/actions/checkout/blob/5881116d181dc80f3ed5f395296a5579ee6fc6a4/action.yml#L29

**Comment by nickelc** [comment]
> # What's new
>* Script authenticated git commands 
>    * Post-job cleanup removes the token

https://github.com/actions/checkout/blob/5881116d181dc80f3ed5f395296a5579ee6fc6a4/src/main.ts#L44-L47

**Comment by DaHuoKolmostar** [comment]
> > # What's new
> > 
> > * Script authenticated git commands
> >   
> >   * Post-job cleanup removes the token
> 
> https://github.com/actions/checkout/blob/5881116d181dc80f3ed5f395296a5579ee6fc6a4/src/main.ts#L44-L47
> 
> https://github.community/t5/GitHub-Actions/post-and-post-if-metadata-tags-are-not-documented/m-p/40821#M4372

Thanks nickelc. That helps.
