### ISSUE TITLE
checkout-multiple-repos-side-by-side doc example

### ISSUE THREAD

**Issue by maxatka** [actions/checkout#1021]
The [README.md](https://github.com/actions/checkout#readme) contains example for mulitple checkouts in the context of one organization, if I'm not wrong.
May be, it's about to checkout public repository.

There is another example - checkout-multiple-repos-private, but is a repository of the same organization on GitHub for which the GitHub action is run, is considered "private" as well?

I thought if I run the action in private repository for my organization, other private repositories are accessible.
If not, it's better to precise the documentation by adding to "Checkout multiple repos (private)" something like:

...so if your want to checkout a different repository that is private **(no matter if it's the same organization on GitHub or not)**...

and to "Checkout multiple repos (side by side)" example to add something like:

Attention! You second repository must be public, even if it's from the same organization on GitHub that the action repository.

**Comment by vanZeben** [comment]
Hey @maxatka, thank you for the feedback!

The `Private` keyword directly corresponds to the [visibility of the repository](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/managing-repository-settings/setting-repository-visibility) in the settings. 

To directly answer your question `is a repository of the same organization on GitHub for which the GitHub action is run, is considered "private" as well?`. That solely uses the visibility settings I mentioned above to determine whether or not the repo is private. . 

We note in a few places that we use `${{ github.token }}` by default which is scoped to the current repository only. This means that it _only_ has permission to access the current repository within an organization and you will need to include a PAT token for it to access other private repositories. 


I've added in a PR to add a reference to the private section just to make it more clear :)

**Comment by maxatka** [comment]
@vanZeben Thanks for your feedback!
Appreciate!
