### ISSUE TITLE
v3 tag broken

### ISSUE THREAD

**Issue by Hamza141** [actions/checkout#1042]
I'm unable to use the v3 tag when I checkout multiple repos. I get a `Unable to resolve v3: unsupported object type` error.

I even tried using the [example](https://github.com/actions/checkout#checkout-multiple-repos-side-by-side) in docs.

I'm assuming this [commit](https://github.com/actions/checkout/commit/b56e6a3d768b11aef1d4c73977caf6413c0d74c8) broke something because the commit belongs to a fork.

**Comment by peter-evans** [comment]
`v3` points to the wrong commit.

![image](https://user-images.githubusercontent.com/18365890/207239658-4947ce8f-56ea-40fc-847a-2b3f7eeaf3aa.png)

**Comment by peter-evans** [comment]
Looks like it can be fixed by running this workflow: https://github.com/actions/checkout/actions/workflows/update-main-version.yml

cc: @vmjoseph

**Comment by cory-miller** [comment]
Apologies for that. I've run the workflow to update v3 to the v3.2.0 commit.

<img width="386" alt="Screenshot 2022-12-13 at 8 53 22 AM" src="https://user-images.githubusercontent.com/13227161/207347504-08c747e9-382e-4001-af80-1a3e38858453.png">
