### ISSUE TITLE
Cloning into an absolute path

### ISSUE THREAD

**Issue by nbahar-intel** [actions/checkout#1044]
Currently the `path` argument only allows for relative path under GIT_WORKSPACE directory.

It would be helpful to be able to set up an absolute path when cloning.

**Comment by nbahar-intel** [comment]
I guess it's a duplicated of #197

**Comment by vanZeben** [comment]
Hey @nbahar-intel, thank you for the input. You would be correct that this is a duplicate of #197. I'm going to close this issue if that's okay and I recommend you subscribe to the other enhancement for updates on that feature request.
