### ISSUE TITLE
Node.js 12 to 16

### ISSUE THREAD

**Issue by LyKos4** [actions/checkout#1047]
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the action to use Node.js 16

**Comment by ebrannin-bw** [comment]
From [this comment](https://github.com/actions/checkout/issues/959#issuecomment-1342479774) on #959, it seems like the way to resolve this is to upgrade to v3.

**Comment by vanZeben** [comment]
As noted above from @ebrannin-bw, upgrading to use `actions/checkout@v3` should correct the deprecations. If it doesn't, please re-open this with some more information about your workflow :)

**Comment by Vadorequest** [comment]
The issue with upgrading to v3 is to have to deal with the major bumps, and all it entails (probably little, but still).

The issue becomes really tough to deal with when you multiply this by the number of actions that needs to be upgraded to node16, and then do this for all repositories. (as manager of dozens of repos, this is heavy work)

https://github.com/UnlyEd/github-action-await-vercel/issues/74#issuecomment-1369991231

**It'd be easier if actions/checkout@v2 would be migrated to v16 directly.**

And it'd be awesome if that became some sort of "best practice" (assuming it doesn't break other things), so as to avoid having to change the major version of all our actions that aren't yet up-to-date.

**Comment by Vadorequest** [comment]
After reading changelog, it appears the v3 was created [specifically because of the nodejs v16 upgrade](https://github.com/actions/checkout/blob/main/CHANGELOG.md#v300).

So, I guess there are reasons not to do that upgrade in @v2 directly... but that does create a ton of needless work

**Comment by yeeydu** [comment]
changing to actions/checkout@v3 doen´t work for me

**Comment by ntimpj** [comment]
actions/checkout@v3 doesn´t work for me either
