### ISSUE TITLE
Link to "Full changelog" in release notes is incorrect

### ISSUE THREAD

**Issue by GMNGeoffrey** [actions/checkout#1060]
The "full changelog" link in the release is https://github.com/actions/checkout/compare/v3...v3.2.0, but v3 is just an alias for the latest 3.x.x release, so this shows nothing, or when a later 3.x version is released will show the backwards diff between that and this release. This should instead be https://github.com/actions/checkout/compare/v3.1.0...v3.2.0

![image](https://user-images.githubusercontent.com/5732088/209882915-de915c56-af59-4a9d-979f-a17f51b9fc40.png)

**Comment by cory-miller** [comment]
Thanks for catching. I've updated the link in the release page.

**Comment by GMNGeoffrey** [comment]
Thanks, but it's actually wrong for ~all of the releases. I suspect there's some automation creating these incorrectly.

**Comment by cory-miller** [comment]
There is no automation for generating these releases. Whoever is drafting the release needs to select a specific revision to compare to when generating (using UI) release notes. If "auto" is selected (and it is by default) then it'll compare to the last tag of that major version. While we could go back and automate these releases, we don't have plans to at this time.
