### ISSUE TITLE
Add Node 16 to `checkout@v2`

### ISSUE THREAD

**Issue by OmAximani0** [actions/checkout#1064]
Since `action/checkout@v2` uses Node 12.x.x and it is [deprecated](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/) I think we should add Node 16 to it

**Comment by cory-miller** [comment]
`action/checkout@v2` has been maintained partly because of needing to keep compat with Node 12. `actions/checkout@v3` is already on Node 16. I suggest switching if possible, or filing a new issue stating why you cannot.
