### ISSUE TITLE
QUESTION: is the duplicate subdir nesting (".../reponame/reponame/...") normal?

### ISSUE THREAD

**Issue by xparq** [actions/checkout#1139]
(GHA noob here.) Just have done my very first build action (_thank you guys for such a wonderful service!_), but noticed that the work tree is created at a strange path, with the repo dir created within a repo dir already created... 

From the YAML:

    jobs:
      build:
        runs-on: windows-latest
        
        steps:
        
        - name: Checkout...
          uses: actions/checkout@v3
        ...
         - name: Diag.
              shell: cmd
              run: |
                echo "So, we are here now: %CD%..."
                echo And this is in the parent dir:
                dir ..

From the output:

    "So, we are here now: D:\a\sfml-test\sfml-test..."
    
    And this is in the parent dir:
    ....    
     Directory of D:\a\sfml-test
    
    01/22/2023  10:56 PM    <DIR>          .
    01/22/2023  10:56 PM    <DIR>          ..
    01/22/2023  10:57 PM    <DIR>          sfml-test

Am I somehow causing this, or is it a known quirk? Or is it normal? (But haven't seen it explained anywhere yet.)
(Obviously doesn't cause trouble, but you may still wonder.)

**Comment by kilahm** [comment]
That's GitHub's default location for the workspace. See the example event payload [here](https://docs.github.com/en/actions/learn-github-actions/contexts#example-contents-of-the-github-context).

**Comment by xparq** [comment]
Oh, man... :) As my imaginary grampa used to always say: "Never trust people who repeat subdirs in a path!"...

Thanks fot the answer!
