### ISSUE TITLE
checkout@v2 fetch download speed sometimes slower than v1

### ISSUE THREAD

**Issue by gregwym** [actions/checkout#119]
with `checkout@v2` it indeed saves a lot of bandwidth but seems much slower on the download speed. Please see the comparison bellow. Is it because GitHub has to do the compression on the fly when fetching with `--depth=1`?

V1
![image](https://user-images.githubusercontent.com/510089/71149998-27097e00-226b-11ea-9a09-1baec170ffae.png)

V2
![image](https://user-images.githubusercontent.com/510089/71150013-2f61b900-226b-11ea-818a-f38c390d99eb.png)

Initially reported at https://github.com/actions/checkout/issues/22#issuecomment-567353410

**Comment by gregwym** [comment]
Another round of test, even much slower. It also spend quite some time on the "Updating files" phase. 

![image](https://user-images.githubusercontent.com/510089/71364769-1b55e880-25d8-11ea-90ae-f0aa363f8cf3.png)

**Comment by ericsciple** [comment]
Curious about the overall time difference? The `...` menu has a Show timestamps menu item. Guessing from the screenshots around 7s vs 20s.

It looks like in this case, HEAD has large files?

**Comment by ericsciple** [comment]
Changed the title since it depends on the factors. V2 is optimized for scenarios such as gb of history, where only downloading HEAD saves many minutes.

**Comment by ericsciple** [comment]
Closing since this is a tradeoff and the difference is seconds not minutes.
