### ISSUE TITLE
actions/checkout@v3 doesn't work when using repository

### ISSUE THREAD

**Issue by jun-jia** [actions/checkout#1197]
We're using self-hosted GitHub enterprise 3.6, usually we use actions/checkout@v3 to checkout source codes directly and there is no issue. But recently it failed after we add repository when checking out

```
actions/checkout@v3
  with:
    repository: ${{github.repository}}.wiki  
```

The error logs are:

> Run actions/checkout@v3
> with:
> repository: DevOps/CIDemo.wiki
> token: ***
> ssh-strict: true
> persist-credentials: true
> clean: true
> fetch-depth: 1
> lfs: false
> submodules: false
> set-safe-directory: true
> Syncing repository: DevOps/CIDemo.wiki
> Getting Git version info
> Deleting the contents of '/data/action-runners/DevOps/CIDemo/CIDemo'
> The repository will be downloaded using the GitHub REST API
> To create a local Git repository instead, add Git 2.18 or higher to the PATH
> Determining the default branch
> Retrieving the default branch name
> Default branch 'master'
> Downloading the archive
> Not Found
> Waiting 16 seconds before trying again
> Downloading the archive
> Not Found
> Waiting 19 seconds before trying again
> Downloading the archive
> Error: Not Found

**Comment by jun-jia** [comment]
@rmccarthy-ellevation First I removed the cache with submodule. Then removed the code directory in working space. And run again, finally it worked.

**Comment by rmccarthy-ellevation** [comment]
> @rmccarthy-ellevation First I removed the cache with submodule. Then removed the code directory in working space. And run again, finally it worked.

Do you have a little more details on how you did that? Sorry new this all this.
