### ISSUE TITLE
Permission denied while executing node binary in checkout action

### ISSUE THREAD

**Issue by prashanthbgoud** [actions/checkout#1229]
Hello All,

Job is ran on a self-hosted ephemeral github runner on amazon linux. It randomly fails the workflow runs with the below error.

```
Run actions/checkout@v3
Error: An error occurred trying to start process '/opt/actions-runner/externals/node16/bin/node' with working directory '/opt/actions-runner/_work/my-org/my-repo'. Permission denied
```

**Comment by prashanthbgoud** [comment]
I see the issue already reported here too https://github.com/actions/runner/issues/2486

**Comment by jww3** [comment]
Hi Prashanth,

   Can you please provide a link to an example of a failed job?  If your repo is not publicly viewable, consider reaching out to [GitHub Customer Support](https://support.github.com/) so that they can advise you on the best way to share job logs, etc.

      -- Wes
