### ISSUE TITLE
Not a git repository error with checkout v2

### ISSUE THREAD

**Issue by gitfool** [actions/checkout#126]
See [gitfool/Cake.Dungeon](https://github.com/gitfool/Cake.Dungeon) workflow builds for commit [6a287dc](https://github.com/gitfool/Cake.Dungeon/commit/6a287dce8d1c137ad4ca3c3cd566396036f0570b):
- [Linux](https://github.com/gitfool/Cake.Dungeon/runs/366247199)
- [Mac](https://github.com/gitfool/Cake.Dungeon/runs/366247194)
- [Windows](https://github.com/gitfool/Cake.Dungeon/runs/366247210)
- [Docker](https://github.com/gitfool/Cake.Dungeon/runs/366248444)

The Docker build is failing with error:
```
fatal: not a git repository (or any parent up to mount point /)
```
This [seems](https://github.com/gitfool/Cake.Dungeon/runs/366248444#step:3:23) to be because, after I switched from checkout v1 to checkout v2, the git version used regressed from [2.24.0](https://github.com/gitfool/Cake.Dungeon/runs/349851037#step:3:12) to [2.17.1](https://github.com/gitfool/Cake.Dungeon/runs/366248444#step:3:20). All other builds above are still using git version 2.24.0.

Did something change on your end or am I missing something? 🤔

**Comment by gitfool** [comment]
I checked and can confirm that my Docker build [container](https://github.com/gitfool/Cake.Dungeon/blob/master/.github/workflows/build.yml#L18) ([Dockerfile](https://github.com/gitfool/cake-docker/blob/master/Dockerfile)) has git version 2.17.1 installed.

So I guess that git used to be host mounted into the build container but that is no longer the case? If so, is such a change documented somewhere?

**Comment by ericsciple** [comment]
@gitfool you are correct. V1 was a plugin built-in to the runner. When using the job-container feature, checkout v1 runs on the host. V2 is a javascript action (so will run in the job container). When git 2.18 isnt in the PATH, the action falls back to downloading via the REST API.

I'll update the docs, it's interesting for folks migrating from v1 and using job-container.

**Comment by ValeriuCoban** [comment]
Hey I have the same issue when I run the job on a self hosted runner. The .git folder is just missing.. What can be the reason ? Thanks in advance
