### ISSUE TITLE
The checkout time is too long, resulting in subsequent actions not getting the github.ref_name parameter

### ISSUE THREAD

**Issue by MGMCN** [actions/checkout#1311]
I may have found a bug, but I don't know why. 👇🏻

I have written an action in workflow that triggers when I execute a release.

The same workflow worked on my last release, but failed this time.

I found that the problem was that the checkout took so long that my workflow didn't get the {github.ref_name} parameter after the checkout, so it failed.

Below I've given a link to one of my successful released workflows and a link to one of my failed released workflows.(Both workflows are the same, but the github.ref_name parameter is different.)

succeed -> [url](https://github.com/MGMCN/bilibiliWordCloud/actions/runs/4706638310/jobs/8348008944)
failed -> [url](https://github.com/MGMCN/bilibiliWordCloud/actions/runs/4927515423/jobs/8804789983)

**Comment by MGMCN** [comment]
![261683648442_ pic](https://github.com/actions/checkout/assets/49364055/eff6e061-df80-474b-a51a-608b811e3858)
I rerun many times and as you can see I couldn't get the github.ref_name parameter. 
I would appreciate it if you could answer my question.

**Comment by MGMCN** [comment]
Of course it is possible that I am wrong and this error is not caused by checkout, maybe it is caused by deprecated usage of github.ref_name?

**Comment by MGMCN** [comment]
I will try to contact the github staff to solve my problem, it seems the problem is not related to checkout.

**Comment by bartgras** [comment]
@MGMCN I have run into similar issue.
Have you reported it somewhere else? Do you have a solution?
