### ISSUE TITLE
'Unexpected value' on checkout

### ISSUE THREAD

**Issue by JLLeitschuh** [actions/checkout#137]
I've been using this action in several locations and I've never seen this error before. I'm not certain what's causing it, nor how to resolve it.

https://github.com/ben-manes/gradle-versions-plugin/commit/be05fde714e42adba61d94d4474c80b5a27290dc/checks?check_suite_id=403053837#step:1:7

**Comment by JLLeitschuh** [comment]
Here's the original PR with the change that is causing this failure.

https://github.com/ben-manes/gradle-versions-plugin/pull/370

**Comment by JLLeitschuh** [comment]
Here's another example:
https://github.com/wpilibsuite/allwpilib/runs/392405211#step:1:5

**Comment by lfreneda** [comment]
@JLLeitschuh same issue here, did you fix it?

**Comment by JLLeitschuh** [comment]
Nope. Looking for support from GitHub on this one.

**Comment by JLLeitschuh** [comment]
Here's another case:
https://github.com/ktorio/ktor/pull/1565#event-2953433307

**Comment by lfreneda** [comment]
> Nope. Looking for support from GitHub on this one.

Fixed using checkout@v1 :haircut_man:

**Comment by ericsciple** [comment]
@TingluoHuang @juliobbv issue with runner? checkout v2 hasnt changed in a couple weeks.

**Comment by ericsciple** [comment]
i bet this is b/c of the new scale unit

**Comment by ericsciple** [comment]
@JLLeitschuh i am told this should be fixed now. Reopen if still hitting issues.

**Comment by ericsciple** [comment]
the fix should have rolled out sometime yesterday
