### ISSUE TITLE
Checkout does not work when the server is configured with a sub-path

### ISSUE THREAD

**Issue by psa** [actions/checkout#1370]
I have  a Gitea server configured with sub-paths (e.g. htttp://example.com/path/to/git/owner/repository.git). Checkout attempts to checkout https://example.com/owner/repository.git and throws away the sub-path.

How to replicate:
* Setup a Gitea server (or any other supported git server) behind a reverse proxy with a sub-path
* Have an action which uses `actions/checkout`
* Watch the logs and see that the called URL is missing the sub-path.

My best guess is that it's lost in https://github.com/actions/checkout/blob/f095bcc56b7c2baf48f3ac70d6d6782f4f553222/src/url-helper.ts#LL19C1-L19C1 as, according to the comment, `serviceUrl.origin` is `SCHEME://HOSTNAME[:PORT]`

**Comment by RouxAntoine** [comment]
Hello i can to the same conclusion as you. and that pretty sad, do you have found a workaround ?

**Comment by RouxAntoine** [comment]
tag on fork with a fix https://github.com/RouxAntoine/checkout/tree/v3.5.4

**Comment by kdumontnu** [comment]
Thanks for reporting & the proposed fix. I can confirm your patch fixed the bug for me. Looking forward to seeing it get merged 🤞

**Comment by RouxAntoine** [comment]
Your welcome, I hope too, however I am afraid of the number of issues and pull request on a so used and so simple action.

**Comment by frankli0324** [comment]
I believe this is a dulplicate https://github.com/actions/checkout/issues/1242#issuecomment-1620642360
also the PR is also dulplicated: https://github.com/actions/checkout/pull/1305

**Comment by RouxAntoine** [comment]
indeed it seems, moreover I am not totaly sur that regex parsing is necessary, I close mine 🙂

```
export function getBaseUrl(url: string): string {
  const matcher = url.match(/^[^?]+/)
  return (matcher && matcher[0].replace(/\/+$/g, '')) || ''
}
```

**Comment by RouxAntoine** [comment]
not totally sure, but if yes, so : 

```
export function trimEndingSlash(input: string): string {
  return input.replace(/\/$/, "");
}
```

My point is here is no reason to parse `serverUrl.href` this should be kept simple and use attribute `pathname` of Object `URL` https://developer.mozilla.org/en-US/docs/Web/API/URL/pathname

**Comment by joshmgross** [comment]
Closing as duplicated of #1242, which we're not planning to support at this time.
