### ISSUE TITLE
Can't use 'tar -xzf' extract archive file

### ISSUE THREAD

**Issue by szepeviktor** [actions/checkout#1448]
```
Download action repository 'actions/checkout@v3' (SHA:f43a0e5ff2bd294095638e18286ca9a3d1956744)
Error: Can't use 'tar -xzf' extract archive file: /home/runner/work/_actions/_temp_81e514cc-59b2-4af3-aa4d-6f8210ffde88/752d468e-f00d-474c-af3f-80fbe27b5318.tar.gz. return code: 2.
```
That hash points to v3.6.0

I do not know what to add here.
https://github.com/nunomaduro/larastan/actions/runs/6074130772/job/16477441571

**Comment by shapirus** [comment]
It looks like it affects multiple (to say the least) users :)

For a workaround, is anyone aware how to pin version used in a workflow to an earlier release?

**Comment by jamesmhaley** [comment]
Does this have anything to do with the v4.0 release from @takost @simonbaird?

**Comment by kevinlul** [comment]
Seems to be a transient network-related issue, based on previous instances.

**Comment by mvdan** [comment]
I'm trying to think how this even broke. It must have been on the server side, because we are using `actions/checkout@v3`, so we should not be affected by the recent v4.0.0 tag.

**Comment by ovr** [comment]
`actions/checkout@v4` - v4 works. It can be used as a quick fix.

**Comment by kevinlul** [comment]
The second re-run (third attempt) worked for me: https://github.com/DawnbrandBots/bastion-bot/actions/runs/6074117346
I think it's not related to specifically this repository but with GitHub itself serving the tarball.

**Comment by mvdan** [comment]
> Seems to be a transient network-related issue, based on previous instances.

Interesting - network reliability aside, I wonder why actions/checkout isn't retrying on network errors.

**Comment by pimhakkertgc** [comment]
Oh no... We need this to work today :#

**Comment by msandu62** [comment]
same issue here

**Comment by robmaxwellirl** [comment]
Seems like it's back working for me now anyways.

**Comment by iedu61** [comment]
same issue here

**Comment by candh** [comment]
working again for us!

**Comment by szepeviktor** [comment]
GitHub Status says ✅  All Systems Operational

**Comment by ananni13** [comment]
> > Interesting - network reliability aside, I wonder why actions/checkout isn't retrying on network errors.
> 
> It's not actions/checkout — it's the Actions runner itself downloading and extracting all the used action packages before starting the workflow.

Yeah, this seems completely unrelated to the checkout action and more an issue on the Runner side.

Changing actions/checkout from v3 to v4 is not a fix, I'm getting random outcomes with either tags, some jobs work other fail.

**Comment by janeusz2000** [comment]
> Confirmed, updating to v4 fixes the issue.

confirmed as well

**Comment by gileorn** [comment]
Seems like it's back to normal

**Comment by shealavington** [comment]
I can confirm that the issue did/does exist. 

I can't speak for the v4 upgrade being a fix, but doing github "Retry Failed Jobs" a few times eventually allowed the job to work (even keeping the v3 tag).

**Comment by wiledal** [comment]
Still inconsistent/flaky for us, seems to happen for majority of runs.

**Comment by kevin-studer** [comment]
We have the problem inside matrix builds, but not in our linting job which does not use the matrix declaration

**Comment by dvirsegev** [comment]
Still inconsistent for me also

**Comment by soltanoff** [comment]
`actions/checkout@v4` helps me. But is it safety to use?

**Comment by markus-dobel-fioneer** [comment]
> Looks like intermittent as a couple of rerun seems to make it work

Intermittent, but failing more often then succeeding.

**Comment by gkech** [comment]
same issue here, I'll try the latest version

**Comment by easimon** [comment]
> Looks like intermittent as a couple of rerun seems to make it work

Intermittent, but failing more often then succeeding.

**Comment by SamYuan1990** [comment]
same issue here, try with 4.0

**Comment by bobvanderlinden** [comment]
GitHub Actions probably relies on `https://api.github.com/repos/XXX/XXX/tarball/XXX`, which is what is failing. It doesn't just fail in GitHub Actions, but I ran into `error: unable to download 'https://api.github.com/repos/NixOS/nixpkgs/zipball/57695599bdc4f7bfe5d28cfa23f14b3d8bdf8a5f': HTTP error 500` as well in Nix.

**Comment by fragkakis** [comment]
Upgrade to v4 worked for us too

**Comment by bahaZrelli** [comment]
![image](https://github.com/actions/checkout/assets/90764483/8017f4ed-80cc-46ad-9bdc-3d1b999a2e9a)

**Comment by pinkforest** [comment]
Party on :partying_face:

**Comment by ricardoboss** [comment]
https://xkcd.com/1168/

**Comment by merinofg** [comment]
Updating to v4 is not a solution for companies that have hundreds of workflows and reusable workflows build around the v3 version.

Breaking changes out of the blue are not as easy as "upsy, update to v4"

**Comment by hugovk** [comment]
Now noticed at https://www.githubstatus.com/incidents/76xp2jd3px64

**Comment by ernitingarg09** [comment]
I am also facing the same issue, we are blocked

![image](https://github.com/actions/checkout/assets/20875452/ff2d7782-769d-47bd-bc64-0315fd7d23ca)

**Comment by hluaces** [comment]
This has been updated right now so I guess we have to wait:
 
 
![image](https://github.com/actions/checkout/assets/3204332/d64f4d02-fac0-4aab-b7d7-cb99219cf80b)

**Comment by hluaces** [comment]
While we wait: is anyone watching something interesting?

**Comment by kurtislamb** [comment]
> 
Ted Lasso!

**Comment by bobvanderlinden** [comment]
https://www.githubstatus.com/incidents/76xp2jd3px64

**Comment by Vanilagy** [comment]
@hluaces Watching Black Mirror for the first time on Netflix at the moment; most episodes are very interesting and quite thought-provoking. But this issue is likely fixed after 1 ep :P

**Comment by yardensade** [comment]
The GitHub response time for updating incidents is really slow, this has been happening for over an hour now. This is not an acceptable SLA.

**Comment by xerdink** [comment]
> The GitHub response time for updating incidents is really slow, this has been happening for over an hour now. This is not an acceptable SLA.

%100 correct.

**Comment by pimhakkertgc** [comment]
> The GitHub response time for updating incidents is really slow, this has been happening for over an hour now. This is not an acceptable SLA.

This is standard Github practice these days. We experience issues with deploying our code at least once every month. I never deploy without looking at https://www.githubstatus.com/ anymore. This is sad.

**Comment by hugovk** [comment]
I've got a script to bump actions: https://github.com/hugovk/github-tools/blob/main/upgrade_actions.py

```sh
wget https://raw.githubusercontent.com/hugovk/github-tools/main/upgrade_actions.py
python -m pip install feedparser rich termcolor
python upgrade_actions.py
```

Then check the changes and commit.

**Comment by olivier-zenchef** [comment]
Upgrading to v4 did work for our CI

**Comment by relloyd** [comment]
Same issue here of course. Because of the way we use this action, I now have hundreds of pipelines broken using v3 and potentially 100s of developers blocked 🤦‍♂️

**Comment by antm-pp** [comment]
> While we wait: is anyone watching something interesting?

Yes, I'm watching all the panic'd updates to workflows where they've realised they only wrote the happy path and jobs weren't failing properly.

The problem is intermittent, the move to v4 could be totally anecdotal.  I just kept re-running the job and sometimes they succeed.

**Comment by marcinciarka** [comment]
> move to v4 could be totally anecdotal

v4 is using node 20 by default so everybody updating should take that into account. Most tests will pass, but deployments - not so sure.

I'll wait.

**Comment by flaxel** [comment]
The incident has been resolved. 🤔

**Comment by pinkforest** [comment]
Seems so - my pipeline in v3 works now :tada:

**Comment by ahmadkanj** [comment]
### Title: "The Great GitHub CI Catastrophe: When Cats Took Over the Code"

Once upon a time in the digital kingdom of GitHubtopia, where programmers and their code lived happily ever after, a hilarious disaster struck the land of Continuous Integration (CI). It all began on a seemingly normal Tuesday morning when the GitHub team decided to spice things up.

**Act 1: The Great Cat Invasion**

GitHub's engineers, in a moment of whimsy, decided to replace all the green checkmarks and red crosses of their CI status indicators with pictures of cats. Yes, you heard that right – cats! The builds now showed fluffy kittens for successful builds and grumpy cats for failing ones.

**Act 2: Kitty Confusion**

The moment GitHub deployed the change, chaos ensued. Programmers across the world were baffled as they logged into their repositories to find cats instead of their beloved checkmarks. One developer cried, "I can't tell if my code is working or if it's just adorable!" while another quipped, "My CI is a real 'cat' astrophe now!"

**Act 3: The Catnip Incident**

As the day went on, the situation got even more absurd. Turns out, GitHub had accidentally left a piece of catnip-infused code in their CI script. Suddenly, everyone's builds started attracting cats! One user's CI server got so overrun by felines that it became a literal cat café. They couldn't even push code without tossing treats.

**Act 4: The Paw-sitive Outcomes**

But GitHub didn't just break CI; they also broke the internet. #GitHubKittyCodeBreakdown trended worldwide, and programmers began sharing their own cat-themed builds. "This PR contains purr-fectly optimized code!" declared one coder. "My CI is now the cat's meow!" boasted another.

**Epilogue: The Cleanup**

GitHub eventually fixed the catnip bug, but they decided to keep the cat-themed CI status indicators as an Easter egg. Now, every time a developer's build passes, a cheerful kitten pops up with a "Meow-nificent!" message. Failures are met with a grumpy cat saying, "No code for you!" It's a reminder that even in the world of serious coding, a little humor goes a long way.

And so, the GitHub CI fiasco became a legendary tale told to new programmers, ensuring that, in GitHubtopia, laughter is always the best debugging tool.

**Comment by szepeviktor** [comment]
Fixed https://www.githubstatus.com/incidents/76xp2jd3px64

**Comment by richvdh** [comment]
Doesn't appear to be completely resolved: it's happening again here.

It would be nice if someone from github staff could actually confirm *why* it's breaking, beyond just " This incident has been resolved.".

**Comment by krassowski** [comment]
Apparently this resurfaced right now - within last ten minutes three different repositories linked to this issue and we see this happening on https://github.com/jupyterlab/jupyterlab/pull/15056.

**Comment by shaneward** [comment]
Actions still randomly failing with same error
`Can't use 'tar -xzf' extract archive file`

**Comment by christianbundy** [comment]
I'd imagine that a new incident will be announced soon, I'm keeping an eye on https://www.githubstatus.com/

**Comment by ramosbugs** [comment]
> I'd imagine that a new incident will be announced soon, I'm keeping an eye on https://www.githubstatus.com/

It's up: https://www.githubstatus.com/incidents/tqrmcdmghldw

**Comment by taylorotwell** [comment]
At Laravel we are seeing extremely slow download speeds from tarball download API endpoints as well (100kbps) across hundreds of servers. Started today.

https://codeload.github.com/laravel/forge-docs/legacy.tar.gz/8e810cf16fd7ffc502b3fb87b7fb3525fa5f6bdd

**Comment by iansltx** [comment]
Seeing this on builds still with v3

**Comment by osdiab** [comment]
v3 still fails on my end, v4 worked. Github claims nothing is wrong lol. Guess that's one way to roll out an update

**Comment by tommoyang** [comment]
Seems like there's another incident 😩

**Comment by osdiab** [comment]
And now it's 503 errors 

```
Warning: Failed to download action 'https://api.github.com/repos/actions/checkout/tarball/3df4ab11eba7bda6032a0b82a6bb43b11571feac'. Error: Response status code does not indicate success: 503 (Service Unavailable).
```

and an ongoing incident https://www.githubstatus.com/incidents/frdfpnnt85s8

**Comment by giacomochiarella** [comment]
Still happening Can't use 'tar -xzf' extract archive file: /home/runner/work/_actions... right now

**Comment by YannHulot** [comment]
Still happening for us.

**Comment by ViacheslavKudinov** [comment]
Same here

**Comment by izi-p** [comment]
Upgrading from v3 to v4 for large codebase is not an acceptable solution. Please fix v3 🙏

**Comment by giacomochiarella** [comment]
upgrading checkout to v4 seems working here

**Comment by pimhakkertgc** [comment]
Actions is still not working? Jeez guys, your 99.9% SLA has already been violated.

**Comment by cesarca** [comment]
The error continues to occur: 
`Error: Can't use 'tar -xzf' extract archive file: /home/runner/_work/_actions/_temp_df1ed10d-c92b-4e3b-b959-9aabe0ae5fa0/b247af82-9e91-414c-9b2d-b00291508b18.tar.gz. return code: 2.`

**Comment by janSchumacherPayments** [comment]
We just updated to v4 and getting the `tar -xzf' extract archive file: /home/runner/work/... return code: 2.` as well as in v3

**Comment by agentran** [comment]
<img width="1267" alt="image" src="https://github.com/actions/checkout/assets/35172122/f1959eed-9c51-4791-be4b-61ea3d21d357">

happens on V4 aswell

**Comment by DekelDevunet** [comment]
Live poll on the current issue and which action you guys taking. 
https://github.com/actions/checkout/discussions/1459

Let's see what we are doing!

**Comment by nantiferov** [comment]
There is ongoing incident on status page https://www.githubstatus.com/incidents/frdfpnnt85s8

**Comment by pimhakkertgc** [comment]
According to Status actions are working again... but when I try to use `actions/checkout@v3` it takes forever. I didn't let it do its thing because I'm scared it will ruin my deployments. Kinda need this to be fixed today.

**Comment by markrity** [comment]
Switched all to `checkout@v4` , but jobs fail also on `v4` , with same error.

**Comment by 64J0** [comment]
We're facing this problem too. It fails using either v3 or v4.
