### ISSUE TITLE
Failed to download action repository 'actions/checkout@v3' .Error: Response status code does not indicate success: 503 (Service Unavailable).

### ISSUE THREAD

**Issue by kaungkyawmoe-codigo** [actions/checkout#1456]
Thank you 🙇‍♀ for wanting to create an issue in this repository. Before you do, please ensure you are filing the issue in the right place. Issues should only be opened on if the issue **relates to code in this repository**.

* If you have found a security issue [please submit it here](https://hackerone.com/github)
* If you have questions about writing workflows or action files, then please [visit the GitHub Community Forum's Actions Board](https://github.community/c/code-to-cloud/github-actions)
* If you are having an issue or question about GitHub Actions then please [contact customer support](https://help.github.com/en/articles/about-github-actions#contacting-support)

If your issue is relevant to this repository, please delete this text and continue to create this issue. Thank you in advance.

**Comment by mpskex** [comment]
I am also getting this error.

**Comment by sh-jthorpe** [comment]
Having the same issue - both on checkout@v2 and checkout @v3

**Comment by RidhoIdris** [comment]
same checkout@v2.3.3

**Comment by taco-chen** [comment]
same here at 
```
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
```

**Comment by SongJiyeon** [comment]
same with checkout@v2

**Comment by pipinfitriadi** [comment]
I got this error to for checkout@v3

**Comment by saadbahir** [comment]
same here

**Comment by starcat37** [comment]
Same with checkout@v2 😭

**Comment by saiichihashimoto** [comment]
Doesn't seem version related, happening on v4 as well.

**Comment by copyNdpaste** [comment]
same. I am using self hosted runner with aws ec2
```      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'true'
          token: ${{ secrets.SUBMODULE_GITHUB_TOKEN }}
          ```
                  uses: actions/checkout@v2,         uses: actions/checkout@v2.3.5
                  
```
Warning: Failed to download action 'https://api.github.com/repos/actions/checkout/tarball/f43a0e5ff2bd294095638e18286ca9a3d1956744'. Error: Response status code does not indicate success: 503 (Service Unavailable).
Warning: Back off 23.462 seconds before retry.
Error: Response status code does not indicate success: 503 (Service Unavailable).
```

**Comment by hsbmapa** [comment]
[Github Status Page](https://www.githubstatus.com/incidents/c8zjb9351hlc)

**Comment by zhgchgli0718** [comment]
same

**Comment by tam-pham-ts** [comment]
I have the same issue

**Comment by Kevin-edint** [comment]
I have the same issue

**Comment by janibashamd** [comment]
Seems like issue from github as reported by @hsbmapa 
https://www.githubstatus.com/incidents/c8zjb9351hlc

**Comment by pipinfitriadi** [comment]
> [Github Status Page](https://www.githubstatus.com/incidents/c8zjb9351hlc)

Is this common issue or rarely? How long commonly we wait for this issue until it solved?

I can't continue write my ci/cd T_T

**Comment by Putra-0** [comment]
I have the same issue

**Comment by aloknecessary** [comment]
Same here 
![image](https://github.com/actions/checkout/assets/20293434/d42fdf38-4a6d-44a5-b302-4849e7a3cdb5)

**Comment by CharlieGreenman** [comment]
I am having this issue for checkout v4 as well. I have a feeling that when updating checkout to v4, it updated by default github's internal services to v4. Some of those services weren't made to run on node20+ and then caused github actions itself to fail

**Comment by jellespijker** [comment]
We are also experiencing trouble https://github.com/Ultimaker/Cura/actions/runs/6080219537

**Comment by CarterChen247** [comment]
+1

**Comment by hurricane1026** [comment]
+1

**Comment by truongdnascript** [comment]
+1

**Comment by anLpk** [comment]
+111

**Comment by pipinfitriadi** [comment]
is there any another good alternative for action/checkout? if it takes too long, i want to switch it

**Comment by janibashamd** [comment]
TOP ISSUE OF THE WEEK :)

**Comment by ycluohuang** [comment]
same. maybe github sever has something wrong :(

**Comment by hyeonminkim0625** [comment]
me too.

**Comment by ensia96** [comment]
something must be wrong

actions/checkout@v3

```
Warning: Failed to download action 'https://api.github.com/repos/actions/checkout/tarball/f43a0e5ff2bd294095638e18286ca9a3d1956744'. Error: Response status code does not indicate success: 503 (Service Unavailable).
Warning: Back off 17.942 seconds before retry.
Warning: Failed to download action 'https://api.github.com/repos/actions/checkout/tarball/f43a0e5ff2bd294095638e18286ca9a3d1956744'. Error: Response status code does not indicate success: 503 (Service Unavailable).
Warning: Back off 20.016 seconds before retry.
Error: Response status code does not indicate success: 503 (Service Unavailable).
##[debug]System.Net.Http.HttpRequestException: Response status code does not indicate success: [50](https://github.com/semutong/semutong-backend-main/actions/runs/6080163819/job/16493826489#step:1:50)3 (Service Unavailable).
##[debug]   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
##[debug]   at GitHub.Runner.Worker.ActionManager.DownloadRepositoryActionAsync(IExecutionContext executionContext, ActionDownloadInfo downloadInfo, String destDirectory)
##[debug]   at GitHub.Runner.Worker.ActionManager.DownloadRepositoryActionAsync(IExecutionContext executionContext, ActionDownloadInfo downloadInfo)
##[debug]   at GitHub.Runner.Worker.ActionManager.PrepareActionsRecursiveAsync(IExecutionContext executionContext, PrepareActionsState state, IEnumerable`1 actions, Int32 depth, Guid parentStepId)
##[debug]   at GitHub.Runner.Worker.ActionManager.PrepareActionsAsync(IExecutionContext executionContext, IEnumerable`1 steps, Guid rootStepId)
##[debug]   at GitHub.Runner.Worker.JobExtension.InitializeJob(IExecutionContext jobContext, AgentJobRequestMessage message)
##[debug]Finishing: Set up job
```

**Comment by AabyssZG** [comment]
+111

**Comment by dungtranhoang** [comment]
+1

**Comment by adi-yuu** [comment]
+1
This is a blocker.

**Comment by ParkJongSang** [comment]
+2

**Comment by SaurabhKoverhoop** [comment]
+3

**Comment by milsakim** [comment]
+4

**Comment by JashBook** [comment]
+3

**Comment by back-2-95** [comment]
Our thoughts, prayers and +1's are with you 🙏

**Comment by DeathSy** [comment]
+1 blocker

**Comment by janibashamd** [comment]
Finally seeing a live blocker on public github :)

**Comment by janibashamd** [comment]
Anyone know how to update this ticket to blocker or something to increase priority for resolutions ! @kaungkyawmoe-codigo

**Comment by JaehaSS** [comment]
sam here!

**Comment by AjayKarki** [comment]
+1

**Comment by AhnSeongHyun** [comment]
+1 This is a blocker

**Comment by savion1024** [comment]
hi all, just update the version from v2 or v3 to v4. use the latest verison.

**Comment by xeromank** [comment]
+1

**Comment by tsutsun17** [comment]
+1 こんにちは

**Comment by tam-pham-ts** [comment]
v3 worked

**Comment by nozo-moto** [comment]
+1

**Comment by CharlieGreenman** [comment]
> hi all, just update the version from v2 or v3 to v4. use the latest verison.

^ still doesn't work always with latest version of v4. Been there done that

**Comment by rachlynch** [comment]
It's recently started working for us again (v3)

**Comment by savion1024** [comment]
maybe cuase the other reason, u can check the ci logs, it is what error i meet.
<img width="1123" alt="截屏2023-09-05 13 04 04" src="https://github.com/actions/checkout/assets/41880319/1319bb25-5025-4df5-87ff-ba070b282ea5">

**Comment by copyNdpaste** [comment]
v3 working

**Comment by janibashamd** [comment]
Issue resolved https://www.githubstatus.com/, check now !

**Comment by so1ve** [comment]
https://twitter.com/githubstatus/status/1698926411816345959 Should work now!

**Comment by kaungkyawmoe-co** [comment]
It is working well .May I close issue.

**Comment by SaurabhKoverhoop** [comment]
working now for v3 for me

**Comment by aloknecessary** [comment]
Stopped working again :(
`Warning: Failed to download action 'https://api.github.com/repos/docker/setup-buildx-action/tarball/2fbc37fd36befb06934864c4601db361dbe295d3'. Error: Response status code does not indicate success: 503 (Service Unavailable).
Warning: Back off 12.96 seconds before retry.`

**Comment by nonzzz** [comment]
But now. It stop working again :( 

`Failed to download action 'https://api.github.com/repos/akhilmhdh/contributors-readme-action/tarball/098389139f2fabed92e52606268941dbff381edb'. Error: Response status code does not indicate success: 503 (Service Unavailable).`

**Comment by Kesha123** [comment]
Seems to be working v3

**Comment by aloknecessary** [comment]
> Stopped working again :( `Warning: Failed to download action 'https://api.github.com/repos/docker/setup-buildx-action/tarball/2fbc37fd36befb06934864c4601db361dbe295d3'. Error: Response status code does not indicate success: 503 (Service Unavailable). Warning: Back off 12.96 seconds before retry.`

Worked now!

**Comment by Lyokolux** [comment]
It seems to fail from time to time. As the checkout didn't change and it works partially, maybe something is going on by Github.

**Comment by KurtisIvey** [comment]
currently experiencing this issue still as well 😢

**Comment by cory-miller** [comment]
I'm closing this issue since it is not related to `actions/checkout`. 

Please reference https://www.githubstatus.com/incidents/frdfpnnt85s8 and https://www.githubstatus.com/incidents/smdz34v7j8q0 for incident details and contact GitHub support or community boards.
