### ISSUE TITLE
Docs improvement

### ISSUE THREAD

**Issue by eng-dibo** [actions/checkout#146]
I'm trying to now exactly what is "checkout repo" mean and what this packages exactly do.
I see it in many examples (in my case, I see it used with an action to deploy to firebase) but actually I don't know what is does.

**Comment by ericsciple** [comment]
This action checks-out your repository under $GITHUB_WORKSPACE, so your workflow can access it.

https://help.github.com/en/actions/configuring-and-managing-workflows/configuring-a-workflow#using-the-checkout-action

**Comment by ericsciple** [comment]
I dont see "checkout repo" in the README. Let me know if there are any specific enhancements that would help.
