### ISSUE TITLE
S̤̮m̤̮i̤̮k̤̮e̤̮ i̤̮k̤̮k̤̮e̤̮ h̤̮e̤̮r̤̮

### ISSUE THREAD

**Issue by fock1666-32** [actions/checkout#1469]
/T
![IMG_0144](https://github.com/actions/checkout/assets/144352129/a86fed2b-7e3a-414c-9694-87aed89a8228)
[hvor mange har bein - Google-søk.pdf](https://github.com/actions/checkout/files/12551755/hvor.mange.har.bein.-.Google-sok.pdf)
hank you 🙇‍♀ for wanting to create an issue in this repository. Before you do, please ensure you are filing the issue in the right place. Issues should only be opened on if the issue **relates to code in this repository**.

* If you have found a security issue [please submit it here](https://hackerone.com/github)
* If you have questions about writing workflows or action files, then please [visit the GitHub Community Forum's Actions Board](https://github.community/c/code-to-cloud/github-actions)
* If you are having an issue or question about GitHub Actions then please [contact customer support](https://help.github.com/en/articles/about-github-actions#contacting-support)

If your issue is relevant to this repository, please delete this text and continue to create this issue. Thank you in advance.
[LICENSE.txt](https://github.com/actions/checkout/files/12551756/LICENSE.txt)
![IMG_3554](https://github.com/actions/checkout/assets/144352129/0d9c83f6-9b87-47c7-a0ad-028aee04c485)
![IMG_0145](https://github.com/actions/checkout/assets/144352129/d247ca9d-2a88-431d-9374-535d991574f9)
[Creep - Radiohead (Lyrics) - YouTube.pdf](https://github.com/actions/checkout/files/12551757/Creep.-.Radiohead.Lyrics.-.YouTube.pdf)

**Comment by Abelkrijgtalles** [comment]
tf

**Comment by userbradley** [comment]
wtf???

**Comment by Abelkrijgtalles** [comment]
it's just not getting deleted

**Comment by dedobbin** [comment]
fair
