### ISSUE TITLE
Bug in path, or incorrect README

### ISSUE THREAD

**Issue by eduncan911** [actions/checkout#150]
The `README` has this bit about the `path` attribute:

    # Relative path under $GITHUB_WORKSPACE to place the repository
        path: ''

When I set this path to the following:

    - name: checkout
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
        path: go/src/github.com/${{ github.repository }}

It creates a dir structure here:

    $ pwd
    /home/runner/work/podcast/go/src/github.com/eduncan911/podcast

That's all expected, fine and dandy.  Or so I thought because now I need to access this location, and I cannot using the ENV vars.  

`$GITHUB_WORKSPACE` points to:

    /home/runner/work/podcast/podcast

Notice the duplicate `podcast/podcast`.  It is not `/home/runner/work/podcast/`, which is what was downloaded to during the checkout with the `path` override.

Also, if I print out the entire `env`, there's not a single location I can reference for `/home/runner/work/podcast/` - which doesn't allow me to `cd` back into and work in.

So at a minimal, this is a problem with the README/docs, in that `path` is not set to `$GITHUB_WORKSPACE` but instead a custom path of `/home/runner/work/` that cannot be accessed with ENV vars and has to be hardcoded for other actions to use.

Or at the worse, and possibly breaking change, `path` should honor the `$GITHUB_WORKSPACE` location as stated in the README.

**Comment by ericsciple** [comment]
`- uses: actions/checkout@v2` you are using v1 :)

**Comment by eduncan911** [comment]
Confirmed @v2 resolved it.  WORKSPACE remained the same, and now it downloads correctly to:

```
$ pwd
/home/runner/work/podcast/podcast/go/src/github.com/eduncan911/podcast
```

Thanks!
