### ISSUE TITLE
problem with eiface.h

### ISSUE THREAD

**Issue by N1eLLsmesh** [actions/checkout#1549]
Hello, I have a problem compiling my project (I use your hl2sdk), two days ago everything compiled without problems, but today I have this error, what could this be related to, is the problem on your side?

/home/runner/work/cs2_weapons_skin/cs2_weapons_skin/hl2sdk-cs2/public/eiface.h:31:10: fatal error: 'network_connection.pb.h' file not found
#include "network_connection.pb.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
Build failed: Skin/linux-x86_64/_home_runner_work_cs2_weapons_skin_cs2_weapons_skin_hl2sdk_cs2_entity2_entitysystem.d
Error: Process completed with exit code 1.

**Comment by metacop** [comment]
![image](https://github.com/actions/checkout/assets/56640826/e85e14fd-ccba-4569-928c-9d690a7bbf0d)
i have same problem.

**Comment by ljfp** [comment]
I have the same issue, any update on this?
