### ISSUE TITLE
question: checkout be used without owner/repo ?

### ISSUE THREAD

**Issue by terekete** [actions/checkout#1560]
Thank you 🙇‍♀ for wanting to create an issue in this repository. Before you do, please ensure you are filing the issue in the right place. Issues should only be opened on if the issue **relates to code in this repository**.

* If you have found a security issue [please submit it here](https://hackerone.com/github)
* If you have questions about writing workflows or action files, then please [visit the GitHub Community Forum's Actions Board](https://github.community/c/code-to-cloud/github-actions)
* If you are having an issue or question about GitHub Actions then please [contact customer support](https://help.github.com/en/articles/about-github-actions#contacting-support)

If your issue is relevant to this repository, please delete this text and continue to create this issue. Thank you in advance.

## issue
Looking to use this github action to pull from a public repository that is not Github. One of the repos I am trying to checkout has the url as: https://company.co/<repo name>. There is no 'owner'. I get the error: 
Invalid repository '<repo name>'. Expected format {owner}/{repo}.

Is there a way to pull the repo without specifying the owner?

Thanks!

**Comment by cory-miller** [comment]
We have no plans to support non-GitHub related usage.

I recommend that you use shell commands directly in your workflow for this.
