### ISSUE TITLE
Suddenly an error started to appear -- EACCES: permission denied, unlink

### ISSUE THREAD

**Issue by stuzonahornyi** [actions/checkout#1566]
Hello! Well today my  pipelines for the tests starts failing with error:
![image](https://github.com/actions/checkout/assets/114428119/c65423a2-c9b7-4bbe-8ed2-da2c2456abf2)
Are there any ideas what could have happened?
step for checkout at pipeline simply described as 
`steps:`
      `- name: Git checkout`
        `uses: actions/checkout@v3`

**Comment by dfilipov-glitnor** [comment]
@stuzonahornyi can you please share how you fixed this problem ?
