### ISSUE TITLE
Error: The process '/usr/bin/git' failed with exit code 128

### ISSUE THREAD

**Issue by Bhagwatilal** [actions/checkout#1580]
I am having this issue when i am generating a snack from below code in workflows.
name: Generate snake animation

on:
  schedule: # execute every 12 hours
    - cron: "* */06 * * *"

  workflow_dispatch:

  push:
    branches:
    - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: generate snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: username
          outputs: dist/snake.svg?palette=github-dark

      - name: push snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: Access token
          
          any one have solution for this help me😣

**Comment by cory-miller** [comment]
Unrelated to `actions/checkout`
