### ISSUE TITLE
Node.js 16 actions are deprecated

### ISSUE THREAD

**Issue by maapteh** [actions/checkout#1596]
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

please provide a new major :) if needed i can make the pr

**Comment by milosbaran** [comment]
I see this message despite having `uses: actions/checkout@v4` in my workflow file

**Comment by maapteh** [comment]
ah, https://github.com/actions/checkout/issues/1464#issuecomment-1706619056 i will close this one :)
