### ISSUE TITLE
Diff between PR and master

### ISSUE THREAD

**Issue by grst** [actions/checkout#160]
Hi,

I am trying to obtain a diff between the current HEAD of a PR and the master branch. 
I understand that `checkout` only fetches the latest revision of the current branch only, so 
I tried the approach to fetch all branches from the README. 

```
- uses: actions/checkout@v2
- run: |
    git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
- run: git diff master HEAD    
```

This fails with
```
Run git diff master HEAD
fatal: ambiguous argument 'master': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
##[error]Process completed with exit code 128.
```

Running `git diff master HEAD` on a local copy of the repository works fine:  
```
git clone <repo>
git checkout pr-branch
git diff master HEAD
```

What am I doing wrong?

**Comment by mbargull** [comment]
`git diff origin/master HEAD`

**Comment by grst** [comment]
This works, thanks! 
(Feeling a bit stupid now...)

**Comment by mbargull** [comment]
You're very welcome ;)
How about the mindset of "We are all stupid -- but we manage to do brilliant things from time to time!" (<-- me, justifying that I do much stupider things all the time XD )
