### ISSUE TITLE
git diff with v2

### ISSUE THREAD

**Issue by arturomf94** [actions/checkout#161]
As suggested [here](https://github.community/t5/GitHub-Actions/GitHub-actions-does-not-print-git-diff/td-p/43755) getting a diff works fine with v1, but not with v2. Was this overlooked? How could one get a diff with v2? 

https://github.com/actions/checkout/issues/160 seems to indicate that this can be done by fetching first. Could one get a git diff without fetching previously?

**Comment by ericsciple** [comment]
V2 was optimized to download the single commit. Proposal [here](https://github.com/actions/checkout/pull/155) for additional control over which refs are fetched.

**Comment by ericsciple** [comment]
Also scenarios in readme for fetching more branches/history

**Comment by ericsciple** [comment]
related to https://github.com/actions/checkout/pull/155
