### ISSUE TITLE
Checkout folked branch but pull request's `github.event.pull_request.base.sha` is synced with origin repo's main branch, not folked repo's main branch.

### ISSUE THREAD

**Issue by AllyW** [actions/checkout#1621]
I checkout a test-branch from a folked repo of a repo, and then make a pull request to the original repo's main branch. 

But pull request's `github.event.pull_request.base.sha` is shown as original repo's head commit of main branch, not folked repo's head commit of main branch (original main branch's head commit might have changed cause someone may have merged some code into it, so folked repo's main branch is behind the original repo main branch).

Thank you 🙇‍♀ for wanting to create an issue in this repository. Before you do, please ensure you are filing the issue in the right place. Issues should only be opened on if the issue **relates to code in this repository**.

* If you have found a security issue [please submit it here](https://hackerone.com/github)
* If you have questions about writing workflows or action files, then please [visit the GitHub Community Forum's Actions Board](https://github.community/c/code-to-cloud/github-actions)
* If you are having an issue or question about GitHub Actions then please [contact customer support](https://help.github.com/en/articles/about-github-actions#contacting-support)

If your issue is relevant to this repository, please delete this text and continue to create this issue. Thank you in advance.

**Comment by cory-miller** [comment]
This is working as intended (it also it not related to actions/checkout).

If you open a PR against the original repository, then the "base" is the original repository.

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests
https://docs.github.com/en/webhooks/webhook-events-and-payloads#pull_request
