### ISSUE TITLE
Code signing key has expired

### ISSUE THREAD

**Issue by lpar** [actions/checkout#1645]
While checking signatures on [the latest release](https://github.com/actions/checkout/releases/tag/v4.1.1):

![CleanShot 2024-03-07 at 09 36 57@2x](https://github.com/actions/checkout/assets/857035/e9ee7cdf-8cf6-43db-80be-1d8351979318)

Text:

> This commit was created on GitHub.com and signed with GitHub's verified signature.
> The key has expired.
>
> GPG key ID: 4AEE18F83AFDEB23

**Comment by cory-miller** [comment]
Later releases no longer have this issue. I'm not sure there's anything we can do for v4.1.1. The GPG key itself is not exposed to us. We create the release through the GitHub UI.
