### ISSUE TITLE
checkout not overriding GITHUB_SHA

### ISSUE THREAD

**Issue by bakoontz2** [actions/checkout#1646]
When this action is invoked, the workspace SHA is no longer the same as the SHA of the triggering workflow, and therefore GITHUB_SHA is no longer correct.

**Comment by cory-miller** [comment]
It's not intended to do this. The docs specify the GITHUB_SHA is tied to the sha that triggered the workflow.

https://docs.github.com/en/actions/learn-github-actions/contexts#github-context

If you need the sha from the checkout step, you should use an environment variable to track it.
