### ISSUE TITLE
Last release failing due to sparse-checkout

### ISSUE THREAD

**Issue by joseotoro** [actions/checkout#1651]
```
/usr/bin/git sparse-checkout disable
git: 'sparse-checkout' is not a git command. See 'git --help'.
Error: The process '/usr/bin/git' failed with exit code 1
```

Job template:
```yaml
jobs:
  FlakyTests:
    runs-on: ubuntu-20.04
    container:
      image: python:2.7.18-buster
    name: Tests
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.BOT_TOKEN }}
        submodules: 'recursive'
```

**Comment by bewinsnw** [comment]
Adding detail from my closed bug (also ubuntu-20.04)
```~$ git --version
git version 2.25.1```

**Comment by jww3** [comment]
We are investigating.  As a workaround, you can pin to v4.1.1

**Comment by clausbuchwald** [comment]
it looks like an outdated git version is being used:

```
Run actions/checkout@v4.1.2
[...]
  /usr/bin/git version
  git version 2.20.1
```

**Comment by bewinsnw** [comment]
Indeed... my bad - the step of my build that fails was the windows build which is older: `git version 2.22.0.windows.1`

But https://github.com/actions/checkout/issues/1386 reports that sparse-checkout wasn't working here until 2.28 and there's a check in the code that the min version for sparse is 2.25 already
https://github.com/actions/checkout/blob/8410ad0602e1e429cee44a835ae9f77f654a6694/src/git-command-manager.ts#L610

**Comment by bewinsnw** [comment]
https://github.com/actions/checkout/blob/main/src/git-source-provider.ts#L212 this is where it's failing in ours - if sparseCheckout isn't enabled it calls `disableSparseCheckout()` which runs `git sparse-checkout disable`, boom

**Comment by fhammerl** [comment]
Rolled back from `v4.1.2` to `v4.1.1`: `actions/checkout@v4` and `actions/checkout@v4.1.1` is ‘latest’ again: https://github.com/actions/checkout/releases

**Comment by credfeto** [comment]
Any reason why 

> Rolled back from `v4.1.2` to `v4.1.1`: `actions/checkout@v4` and `actions/checkout@v4.1.1` is ‘latest’ again: https://github.com/actions/checkout/releases

Any reason why this was rolled back rather than a v4.1.3 to revert?  Dependabot keeps bringing this in as a suggested update, and then I get an error in one of our tools that uses libgit2 (https://github.com/libgit2/libgit2/issues/6044) which doesn't handle the ``extensions.worktreeconfig`` that 4.1.2 brings in.  Being on self hosted runners - i have to delete all the repos from the disk for each runner every single time as nothing will build with a repo that has this enabled

**Comment by norrisjeremy** [comment]
> > Rolled back from `v4.1.2` to `v4.1.1`: `actions/checkout@v4` and `actions/checkout@v4.1.1` is ‘latest’ again: https://github.com/actions/checkout/releases
> 
> Any reason why this was rolled back rather than a v4.1.3 to revert? Dependabot keeps bringing this in as a suggested update, and then I get an error in one of our tools that uses libgit2 ([libgit2/libgit2#6044](https://github.com/libgit2/libgit2/issues/6044)) which doesn't handle the `extensions.worktreeconfig` that 4.1.2 brings in. Being on self hosted runners - i have to delete all the repos from the disk for each runner every single time as nothing will build with a repo that has this enabled
> 
> Looks like the release is still here and still tagged, so whatever rollback was done isn't complete:
> 
> https://github.com/actions/checkout/releases/tag/v4.1.2

Yes, if v4.1.2 is fatally flawed, than a new v4.1.3 release needs to be tagged, not slipping the v4 tag.

**Comment by credfeto** [comment]
Dependabot has tried to update to 4.1.3 which is pre-release and also has this issue https://github.com/funfair-tech/funfair-server-code-analysis/pull/218

**Comment by cory-miller** [comment]
v4.1.4 should have the fix for this issue.

As for dependabot, we reached out to that team about pre-release being included in their updates. On the actions/checkout side we will avoid use pre-release until that's been looked at.
