### ISSUE TITLE
Please upgrade to node20, thank you.

### ISSUE THREAD

**Issue by xiaomeng9597** [actions/checkout#1674]
Error log

Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v2, peaceiris/actions-gh-pages@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/

**Comment by bjosv** [comment]
I believe you need to start using a newer major-version, use `actions/checkout@v4` to get node20,
see https://github.com/actions/checkout/releases/tag/v4.0.0

**Comment by cory-miller** [comment]
`actions/checkout@v2` exists for users who do not have support for Node 16+ on their runner (e.g. perhaps they are on GHES). Similarly `actions/checkout@v3` is meant for Node 16. To get rid of the warning annotation, please update to the latest version of `actions/checkout@v4`.
