### ISSUE TITLE
Issue with github packages not working as expected

### ISSUE THREAD

**Issue by CharlieGreenman** [actions/checkout#1675]
All of a sudden one of my private packages are no longer working for my github 

>  enoent ENOENT: no such file or directory, open '/download/@***/***

Github token re-generated so confirmed not an issue with expiration date

**Comment by CharlieGreenman** [comment]
It's not just me https://x.com/megatrontz/status/1777484232203624507

**Comment by ryanhinojosa** [comment]
We are running into the same issue. We are getting the error with "corrupted tarballs"

**Comment by dylanvorster** [comment]
same issue this side. Looks like issue with downloading packages that were published within the last hour or so

**Comment by ryzr** [comment]
> same issue this side. Looks like an issue with downloading packages that were published within the last hour or so (older packages from private repos seem to be downloading fine)

We're having issues with packages published 2 weeks ago :-(

**Comment by dylanvorster** [comment]
oh noes :( Maybe unrelated?

**Comment by ryzr** [comment]
Discussion: https://github.com/orgs/community/discussions/118352
