### ISSUE TITLE
jobs sporadically failing with: "Fail to load actions\checkout\v4\action.yml"

### ISSUE THREAD

**Issue by Ari-Kishon** [actions/checkout#1677]
Today we have started to experience sporadic failures for our GitHub jobs originating in ``actions/checkout/v4``
(We are using self-hosted runners)

It fails the setup step:
![Screenshot 2024-04-09 at 17 08 35](https://github.com/actions/checkout/assets/37385467/891bc117-1670-46a8-b1e3-d4e5beb885d6)

and we get the following error:
![Screenshot 2024-04-09 at 17 11 27](https://github.com/actions/checkout/assets/37385467/b976532f-d595-47aa-9f81-3eb991b00a58)

```
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter ''using: node20' is not supported, use 'docker', 'node12' or 'node16' instead.')
   at GitHub.Runner.Worker.ActionManifestManager.ConvertRuns(IExecutionContext executionContext, TemplateContext templateContext, TemplateToken inputsToken, String fileRelativePath, MappingToken outputs)
   at GitHub.Runner.Worker.ActionManifestManager.Load(IExecutionContext executionContext, String manifestFile)
```

We havent changed anything on our side in the last few days.

**Comment by alokgpta** [comment]
+1

**Comment by cory-miller** [comment]
This error comes from the github.com/actions/runner software and indicates you do not have Node 20 installed. Make sure the runner version matches https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/#for-self-hosted-runner-administrators

If you need to support runners without Node 20, then you should fallback to `actions/checkout@v3` in your workflow.
