### ISSUE TITLE
Jobs randomly failing with Host key verification failed.

### ISSUE THREAD

**Issue by shubhamoli** [actions/checkout#1682]
Hi,

We're facing a weird issue where _some_ of our jobs are failing randomly with the following error.

```
Fetching the repository
  /usr/bin/git -c protocol.version=2 fetch --no-tags --prune --no-recurse-submodules --depth=2 origin +<redacted>:refs/remotes/origin/xyz-581
  Host key verification failed.
  Error: fatal: Could not read from remote repository.
  
  Please make sure you have the correct access rights
  and the repository exists.
  The process '/usr/bin/git' failed with exit code 128
  Waiting 11 seconds before trying again
  /usr/bin/git -c protocol.version=2 fetch --no-tags --prune --no-recurse-submodules --depth=2 origin +<redacted>:refs/remotes/origin/xyz-[58](https://github.com/our/repo/actions/runs/<id>/job/<id>?pr=3431#step:2:65)1
  Host key verification failed.
  Error: fatal: Could not read from remote repository.
  
  Please make sure you have the correct access rights
  and the repository exists.
  The process '/usr/bin/git' failed with exit code 128
```

**How to reproduce?**
Unfortunately, It is very hard to reproduce as it's random. The same self hosted runner VM works fine normally but then suddenly the next job fails with `Host key verification failed`.

**Version** - actions/checkoutv4. Previously it was v3 but it's the same behaviour with v4.

---
Any help or pointers to debug this issue will be highly appreciated. Thank you! in advance 🙏

**Comment by RoadToDream** [comment]
Before doing that, check if the key is setup correctly, one can try if the checkout action works on a single git repo

```
- uses: actions/checkout@v4
  with:
    repository: ORG/REPO
    ssh-key: ${{ secrets.PRIVATE_KEY }}
```
If the key is correctly setup then action should be able to retrieve it. 

Then we can go to the next step.
One possible reason is that ssh is asking for confirming adding the host to known_hosts.
To check, you may manually set the key
```
- name: Retrieve private key
  run: |
    eval "$(ssh-agent -s)"
    ssh-add - <<< '${{ secrets.PRIVATE_KEY }}'
  shell: bash
```
and pull the repo using 
```
- name: Retrieve submodule
  run: GIT_SSH_COMMAND='ssh -v"' git clone SUBMODULE_GIT_LINK
  shell: bash
```

and see if it returns 

```
debug1: read_passphrase: can't open /dev/tty: No such device or address
Host key verification failed.
fatal: Could not read from remote repository.
```

If so, it means the ssh client hangs and exit as you didn't enter yes for adding the host and this can be fixed by specifying 

```
- name: Retrieve submodule
  run: GIT_SSH_COMMAND='ssh -v -o "StrictHostKeyChecking no"' git clone SUBMODULE_GIT_LINK
  shell: bash
```

this also works for pulling submodules
```
- name: Retrieve submodule
  run: GIT_SSH_COMMAND='ssh -v -o "StrictHostKeyChecking no"' git submodule update --init --recursive
  shell: bash
```

**Comment by shubhamoli** [comment]
Thanks a lot for the tips. We're finally able to identify the issue, and it
was actually a misconfiguration from our side.

It was due to a job messing up our ~/.gitconfig, and causing issues in the
runners where this misconfigured job gets executed leading to subsequent
jobs failing.

I will mark the Github issue as resolved for now.
