### ISSUE TITLE
what does `plugin` mean?

### ISSUE THREAD

**Issue by sunt05** [actions/checkout#17]
For the code here:
https://github.com/actions/checkout/blob/7f0669ca1fd955c0e0fd85ee8d5b8d16978be97e/action.yml#L21-L22

What does `plugin` mean?

I cannot find any reference on the [help page](https://help.github.com/en/articles/metadata-syntax-for-github-actions).

**Comment by dougnukem** [comment]
I'm curious about this one, is it referencing some built-in native action commands or something?

**Comment by TingluoHuang** [comment]
it's a built-in action, we plan to make it as a javascript action so everyone can see how it work. 😄

**Comment by sunt05** [comment]
Thanks for the explanation! @TingluoHuang 
Any reference for the js-based actions?
