### ISSUE TITLE
Fails with SyntaxError after recent NPM dependencies update

### ISSUE THREAD

**Issue by dylanhand** [actions/checkout#1712]
~As of version 4.1.4~ As of commit 9c1e94e0ad997d618b6113a2171b055037589028 (#1703), my CI builders are broken with the following error:

```
Running clone
Running:  node $HOME/tasks/$TASK_ID/_temp/actions/checkout/dist/index.js
+ node /root/tasks/xxxxx/_temp/actions/checkout/dist/index.js
/root/tasks/xxxxx/_temp/actions/checkout/dist/index.js:7620
static {
^
SyntaxError: Unexpected token '{'
at wrapSafe (internal/modules/cjs/loader.js:915:16)
at Module._compile (internal/modules/cjs/loader.js:963:27)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
at Module.load (internal/modules/cjs/loader.js:863:32)
at Function.Module._load (internal/modules/cjs/loader.js:708:14)
at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
at internal/main/run_main_module.js:17:47
Process exited with code: 1
```

Caused by [line 7620 in dist/index.js](https://github.com/actions/checkout/blob/8459bc0c7e3759cdf591f513d9f141a95fef0a8f/dist/index.js#L7620), introduced 5 days ago.

I'm guessing the solution is to upgrade node, but thought I'd mention it in case this is unexpected.

**Comment by jww3** [comment]
The changes to `index.js` were [minimal in v4.1.4](https://github.com/actions/checkout/compare/v4.1.3...v4.1.4#diff-3d2b59189eeedc2d428ddd632e97658fe310f587f7cb63b01f9b98ffc11c0197R585).  They were also [pretty minimal over the past several releases](https://github.com/actions/checkout/compare/v4.1.1...v4.1.4#diff-3d2b59189eeedc2d428ddd632e97658fe310f587f7cb63b01f9b98ffc11c0197R470) with no changes beyond line 2410.

Since releasing `v4.1.4`, `index.js` has changed much more extensively as the result of #1703, but those changes are yet to be released.

How are you referencing `actions/checkout` in your workflow?  Can you please include a YML snippet?

**Comment by dylanhand** [comment]
Good catch, I wrongly indicated this was because of v4.1.4, but you're right that it was the following commit that broke things for me (#1703) :)

We're using [Taskcluster](https://github.com/taskcluster/taskcluster) for CI and currently access `actions/checkout` by simply cloning the repo and using the `main` branch. We should probably make it possible to pin to a version/tag, but it's never been a problem before.

My current workaround is to checkout the `releases/v4.0.0` branch.

The CI machine that has issues is running node v16, which I'm guessing needs an update to support the latest changes.

**Comment by jww3** [comment]
In the meantime, referencing the commit by SHA should also work (e.g.  `yourfork/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b`)

**Comment by cory-miller** [comment]
> The CI machine that has issues is running node v16, which I'm guessing needs an update to support the latest changes.

If your runners are on Node 16, you should stick with the `v3` tag until you can update the Node version. Checkout (and most first party GH actions) typically use these major version bumps with changes to the available Node runtime. e.g. https://github.com/actions/checkout/releases/tag/v4.0.0

**Comment by dylanhand** [comment]
> If your runners are on Node 16, you should stick with the `v3` tag until you can update the Node version. Checkout (and most first party GH actions) typically use these major version bumps with changes to the available Node runtime. e.g. https://github.com/actions/checkout/releases/tag/v4.0.0

Good to know, thanks for the info :)

**Comment by Magdihamed** [comment]
🤝🥰تم الإرسال من Galaxy الخاص بي
-------- الرسالة الأصلية --------من: Dylan Hand ***@***.***> التاريخ: ٣٠‏/٤‏/٢٠٢٤  ٤:٥١ م  (GMT+03:00) إلى: actions/checkout ***@***.***> نسخة: Subscribed ***@***.***> الموضوع: Re: [actions/checkout] Fails with SyntaxError after recent NPM dependencies update (Issue #1712) 

If your runners are on Node 16, you should stick with the v3 tag until you can update the Node version. Checkout (and most first party GH actions) typically use these major version bumps with changes to the available Node runtime. e.g. https://github.com/actions/checkout/releases/tag/v4.0.0

Good to know, thanks for the info :)
