### ISSUE TITLE
.gz is not a supported archive file format error on Windows with new version 9c1e94e0

### ISSUE THREAD

**Issue by dbronish-cfs** [actions/checkout#1721]
Previously (at version 0ad4b8fa), it would generate this extract command, which works properly:

```
Extracting the archive
C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoLogo -Sta -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command "$ErrorActionPreference = 'Stop' ; try { Add-Type -AssemblyName System.IO.Compression.FileSystem } catch { } ; [System.IO.Compression.ZipFile]::ExtractToDirectory('C:\actions-runner\_work\redacted.tar.gz', 'C:\actions-runner\_work\redacted')"
```

Now at 9c1e94e0, it generates this command, which fails:

```
Extracting the archive
C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoLogo -Sta -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command "$ErrorActionPreference = 'Stop' ; try { Add-Type -AssemblyName System.IO.Compression.FileSystem } catch { } ; if ((Get-Command -Name Expand-Archive -Module Microsoft.PowerShell.Archive -ErrorAction Ignore)) { Expand-Archive -LiteralPath 'C:\actions-runner\_work\redacted.tar.gz' -DestinationPath 'C:\actions-runner\_work\redacted' -Force } else {[System.IO.Compression.ZipFile]::ExtractToDirectory('C:\actions-runner\_work\redacted.tar.gz', 'C:\actions-runner\_work\redacted', $true) }"
Expand-Archive : .gz is not a supported archive file format. .zip is the only supported archive file format.
```

**Comment by dbronish-cfs** [comment]
In https://github.com/actions/checkout/commit/9c1e94e0ad997d618b6113a2171b055037589028, on line 7098 of `dist/index.js`, logic was added to attempt to use `Expand-Archive`, which is obviously what's failing. The previous behavior of just using `ExtractToDirectory` is now the fall-through behavior if `Expand-Archive` is not found.

Taking a step back, I'm curious why a tarball was downloaded in the first place. It looks like a zipball should be downloaded, when running on Windows. Perhaps the issue lies there.

**Comment by lmshek** [comment]
I got this error too. Do we have any alternatives?

**Comment by AdamSmith-BT** [comment]
Also seeing this issue, explictly using v4.1.4 resolves the issue for now.

**Comment by PedroMiguelFigueiredo** [comment]
Same problem...

**Comment by cory-miller** [comment]
I reverted `v4` to point to `v4.1.4` while I take a look at this.

**Comment by cory-miller** [comment]
> Taking a step back, I'm curious why a tarball was downloaded in the first place. It looks like a zipball should be downloaded, when running on Windows. Perhaps the issue lies there.

I'm not actually sure if it's a tarball. On Windows we should be using `downloadZipballArchive` from Octokit (https://github.com/actions/checkout/blob/44c2b7a8a4ea60a981eaca3cf939b5f4305c123b/src/github-api-helper.ts#L134-L136).

The problem may come from the fact that the file extension was hardcoded at https://github.com/actions/checkout/blob/44c2b7a8a4ea60a981eaca3cf939b5f4305c123b/src/github-api-helper.ts#L38 and then updating the `@actions/tool-cache` dependency we see a change to the command used for extracting zip archives (https://github.com/actions/toolkit/blob/ae38557bb0dba824cdda26ce787bd6b66cf07a83/packages/tool-cache/src/tool-cache.ts#L377). It seems like `Expand-Archive` checks the filename for `.zip` at the end.

If that's the case, it should be as simple as I have https://github.com/actions/checkout/compare/main...users/cory-miller/windows-test to fix.

I don't have easy access to a Windows machine where `actions/checkout` won't be able to find Git. I'll look into getting one setup and try this branch against `v4.1.5`

**Comment by tehpsalmist** [comment]
@cory-miller Will you be submitting that PR soon? Is it waiting on a review or testing?

**Comment by cory-miller** [comment]
@tehpsalmist delay was due to needing but not having a Windows machine without Git.exe handy. I was able to set one up and tested the change. PR is up now. 

https://github.com/actions/checkout/pull/1732

**Comment by cory-miller** [comment]
I've created https://github.com/actions/checkout/releases/tag/v4.1.6 and cannot reproduce this issue on that tag. I'm going to do some additional testing before promoting that to v4 (I'll do that on Monday).

Feel free to try against `uses: actions/checkout@v4.1.6` and reopen this if that fix did not work for your setup.

**Comment by dbronish-cfs** [comment]
I testing v4.1.6 in the same environment in which I first observed this issue.

With v4.1.6, the file is a zip and the extract is successful:

```
C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoLogo -Sta -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command "$ErrorActionPreference = 'Stop' ; try { Add-Type -AssemblyName System.IO.Compression.FileSystem } catch { } ; if ((Get-Command -Name Expand-Archive -Module Microsoft.PowerShell.Archive -ErrorAction Ignore)) { Expand-Archive -LiteralPath 'C:\actions-runner\_work\redacted.zip' -DestinationPath 'C:\actions-runner\_work\redacted' -Force } else {[System.IO.Compression.ZipFile]::ExtractToDirectory('C:\actions-runner\_work\redacted.zip', 'C:\actions-runner\_work\redacted', $true) }"
```

Looks good, thanks!

**Comment by cory-miller** [comment]
`v4` has been updated to `v4.1.6`
