### ISSUE TITLE
how soon v3 will not be supported

### ISSUE THREAD

**Issue by fjiang-aamc** [actions/checkout#1728]
Our services are running on a self-host that cannot upgrade Node.js to version 20 until next summer. My question is: how soon will version 3 no longer be supported, and when will updating to version 20 become mandatory to continue using this action?

best
James

**Comment by cory-miller** [comment]
We don't have any plans to remove the tag. That said, this is also going to be tied to the version of github.com/actions/runner you are using. 

As far as I know there's been no announcement that Node 12 and Node 16 actions will be disabled at the runner level. Until that time, `actions/checkout@v3` will continue to work with Node 16 (and `actions/checkout@v2` with Node 12).

Here's the announcement for when the runner software began to support Node 20. There should be a similar announcement when Node 12 and Node 16 will stop working.

https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/
