### ISSUE TITLE
Thank you for your quick response.

### ISSUE THREAD

**Issue by Shayan1191** [actions/checkout#1767]
Thank you for your quick response.
We have confirmed that it works in Draft PR :)

_Originally posted by @chibicco in https://github.com/anc95/ChatGPT-CodeReview/issues/140#issuecomment-1972490468_

**Comment by chibicco** [comment]
@Shayan1191 

Hi there,

I believe there might have been a mistake with the mention in this issue (#1767). It seems I was tagged inadvertently. Could you please check and confirm?

Thank you for looking into this!

Kind regards.

**Comment by chibicco** [comment]
@Shayan1191 

Hi there,

I believe there might have been a mistake with the mention in this issue. It seems I was tagged inadvertently. Could you please check and confirm?

Thank you for looking into this!

Kind regards.
