### ISSUE TITLE
API Version

### ISSUE THREAD

**Issue by Mai0313** [actions/checkout#1771]
I found that gitea api is using `v1` like `https://gitea.mediatek.inc/api/v1/repos/...`, but `action/checkout` uses `v3`. If we can change the version manually, I think it will have a better capability for both gitea and github.

For example, we can add one more variable for api_version, then we can decide if I wanna use v1 or v*; default is `v3` for github.

**Comment by cory-miller** [comment]
`v3` in `actions/checkout` refers to the checkout release. It's not the API of GitHub repositories or Gitea.
