### ISSUE TITLE
actions/checkout@v3

### ISSUE THREAD

**Issue by sesa766683** [actions/checkout#1772]
I am using actions/checkout@v3 in self-hosted runner in checkout task getting below error:

Kindly help me to resolve this issue

Error: File was unable to be removed Error: EBUSY: resource busy or locked, rmdir 'D:\actions-runner\_work\_temp\a2a6d78f-6fe3-4933-8e23-8053d64c1297'
    at Object.<anonymous> (D:\actions-runner\_work\_actions\actions\checkout\v3\dist\index.js:5982:19)
    at Generator.throw (<anonymous>)
    at rejected (D:\actions-runner\_work\_actions\actions\checkout\v3\dist\index.js:5876:65)

**Comment by cory-miller** [comment]
You tend to get these kinds of messages when having something on the OS locks files checked out, like a virus scanner for example. Please take a look at your settings and see what you can configure or do to prevent the scanner from running when actions/checkout attempts to perform post-job steps.
