### ISSUE TITLE
missing v2.0.1 tag?

### ISSUE THREAD

**Issue by ltalirz** [actions/checkout#180]
Just noticed that the version number was bumped to 2.0.1 in https://github.com/actions/checkout/commit/dfd70d4a2dece5f4a1af8dc99e1508a16e916b60 without releasing a new tag.

Since there are improvements in `master` over `v2` that matter to us (even after dfd70d4a2dece5f4a1af8dc99e1508a16e916b60), a new release would be greatly appreciated!

**Comment by ericsciple** [comment]
@ltalirz v2 has still moved forward. Which functionality in particular are you looking for? The only thing not in v2 is the submodule/ssh stuff which is intentionally in master only while collecting feedback (effectively preview)

**Comment by csadorf** [comment]
@ericsciple I'm confused. What do you mean by "it moved forward"? Are you updating the tag?

**Comment by ericsciple** [comment]
yes v2 is latest v2

**Comment by ltalirz** [comment]
Dear @ericsciple , I'm afraid my original comment was based on some misinterpretation of results we were seeing, and it turns out `v2` is working just fine. Sorry for the trouble!
