### ISSUE TITLE
Header Token overrides user token

### ISSUE THREAD

**Issue by hipstersmoothie** [actions/checkout#181]
My automated release tool `auto` will inject a GitHub PAT into the remote url so it looks something like

```
https://TOKEN@github.com/your/project
```

This allows us to push to the remote more reliably. With the .extraHeader configuration it seems to override the user supplied token and my users see:

```
At least 1 approving review is required by reviewers with write access.        
```

This seems to be coming from this line 

```
/usr/bin/git config --local http.https://github.com/.extraheader AUTHORIZATION: basic ***
```

Which makes git always use the GITHUB_TOKEN, which is not a collaborator on the repo, which then triggers branch protection.

---

[works](https://github.com/hipstersmoothie/auto-config-hipstersmoothie/runs/495974453?check_suite_focus=true)

```
      - uses: actions/checkout@v1

      - name: Prepare repository
        run: git checkout "${GITHUB_REF:11}"
```

[doesn't work](https://github.com/hipstersmoothie/auto-config-hipstersmoothie/runs/495978339?check_suite_focus=true)

```
      - uses: actions/checkout@v2

      - name: Prepare repository
        run: git fetch --tags --unshallow
```

**Comment by hipstersmoothie** [comment]
This line seems to have changed between v1 and v2 

```
/usr/bin/git config --local http.https://github.com/.extraheader AUTHORIZATION: basic ***
```

Maybe this is affecting the push I'm trying to do later in the workflow?

**Comment by hipstersmoothie** [comment]
That [was it](https://github.com/hipstersmoothie/auto-config-hipstersmoothie/runs/496060628?check_suite_focus=true) added `git config --local --unset http.https://github.com/.extraheader` after checkout and it worked.

For more context my tool `auto` will inject eh GithubToken into the remote url so it looks something like

```
https://TOKEN@github.com/your/project
```

This allows us to push to the remote more reliably. With the .extraHeader configuration it seems to override the user supplied token and my users see:

```
At least 1 approving review is required by reviewers with write access.        
```

**Comment by hipstersmoothie** [comment]
Still can't get `--unshallow` to fetch all commits and tags though

https://github.com/hipstersmoothie/auto-config-hipstersmoothie/runs/496073901?check_suite_focus=true

**Comment by thboop** [comment]
@hipstersmoothie 
We intended `v2` to persist the credentials for you to make pushing to the remote easier! If you want to persist your pat you can pass it in via the `token` parameter (it is currently defaulting to the github token). See [Creating and storing secrets](https://help.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets#creating-encrypted-secrets) for more information on how to do this.

If you don't want `actions/checkout` to set the extra header, you can set `persist-credentials` to `false`. You can read more about why we do this via our [ADR on the subject](https://github.com/actions/checkout/blob/b4626ce19ce1106186ddf9bb20e706842f11a7c3/adrs/0153-checkout-v2.md#persist-credentials)

**Comment by hipstersmoothie** [comment]
Thanks! That should def clear this up. Added it to my docs 🚀

**Comment by nevir** [comment]
FWIW, even with persist-credentials: false, it still appears to be writing that header (ex workflow: https://github.com/ficsit/data-engineering/actions/runs/60011603/workflow#L20)
