### ISSUE TITLE
"Post Checkout repository" hangs for more than one hour

### ISSUE THREAD

**Issue by williamdes** [actions/checkout#187]
Hi
I just had https://github.com/actions/cache/issues/95 and had no other solution but to remove the cache support.
But now it is the turn of checkout.
I see no valid reason to keep hanging like it does.

![image](https://user-images.githubusercontent.com/7784660/76763176-e6020680-6792-11ea-8366-c3c83cc5a5e7.png)

Please help me
Cancelling runs takes a lot of tries to "complete" (cf: screenshot "Runner Hosted Agent did not respond to a cancelation request with 00:05:00.")
Because even when the run is cancelled "Post Checkout repository" still runs for ever.

I have other workflows that use exactly the same everything:
- services
- cache
- checkout

This one only has 2 more services **and takes more then 10 min to complete.**

**Comment by williamdes** [comment]
And I added `ACTIONS_STEP_DEBUG` but the step does not unfold to show me the logs..

**Comment by ericsciple** [comment]
@williamdes which version are you using? `actions/checkout@v2`?

**Comment by williamdes** [comment]
@ericsciple Yes, latest version

**Comment by ericsciple** [comment]
Do logs eventually show up? After the run is completed if you refresh the page? Curious which command is hanging.

**Comment by williamdes** [comment]
> Do logs eventually show up? After the run is completed if you refresh the page? Curious which command is hanging.

I am sorry but I could not obtain any logs from the hanging steps..
The run never did end completely
They are still in a running state
![image](https://user-images.githubusercontent.com/7784660/76987606-bf370200-6943-11ea-8dd7-e11527a54251.png)


Today I removed the line that runs our tests and the CIs did success without any issue
Time seems to be the issue

**Comment by ericsciple** [comment]
Can you try placing a simple step after "Run end-to-end test"

```yaml
  run: git config --local --get remote.origin.url
```

Does it also hang?

**Comment by williamdes** [comment]
![image](https://user-images.githubusercontent.com/7784660/77050695-6e1e2100-69ca-11ea-8ffe-efd02d48b4af.png)

No more hanging :tada: 

Do you have an idea of where the issue ?

**Comment by ericsciple** [comment]
No idea :)

Since you also experienced it on a different step, it doesnt sound specific to checkout. I wonder if the machine was losing connectivity or runner process was getting killed or something.

Closing for now

**Comment by gojanpaolo** [comment]
We are getting a similar issue with a self-hosted runner

**Comment by gojanpaolo** [comment]
[# 56](https://github.com/gojanpaolo/wm-pipeline-sb/actions/runs/225570240) just finished. Took 11m 27s. It's interesting that it says only 3s on `Post Run actions/checkout@v2` when it was stuck there for at least 10 minutes

**Comment by demisx** [comment]
We occasionally run into similar issue, but it usually goes away after re-running workflow. I think it's an issue on the GitHub end:

![Screen Shot 2021-09-21 at 10 35 54 AM](https://user-images.githubusercontent.com/4452412/134221272-319c8f2e-2377-4d79-92ed-c760e2a96bbf.gif)
