### ISSUE TITLE
Fatal: easly EOF RPC failed

### ISSUE THREAD

**Issue by martiix-admin** [actions/checkout#1871]
Hi, on a regular basis we face issues with checking out code, and it seems to be happening more frequently in the past couple of weeks. 

We use the checkout action like this:
```                       - name: Check out code
              uses: actions/checkout@v4
              with:
                  lfs: false
                  token: ${{ secrets.CHECKOUT_BOT_PERSONAL_ACCESS_TOKEN }}
                  fetch-depth: 0
```

Under fetching the repository, this is the log output:
```
Fetching the repository
  /usr/bin/git -c protocol.version=2 fetch --prune --no-recurse-submodules --unshallow origin +refs/heads/*:refs/remotes/origin/* +refs/tags/*:refs/tags/*
  Error: error: RPC failed; curl 92 HTTP/2 stream 0 was not closed cleanly: CANCEL (err 8)
  Error: error: 2000 bytes of body are still expected
  fetch-pack: unexpected disconnect while reading sideband packet
  Error: fatal: early EOF
  Error: fatal: fetch-pack: invalid index-pack output
  The process '/usr/bin/git' failed with exit code 128
  Waiting 14 seconds before trying again
  /usr/bin/git -c protocol.version=2 fetch --prune --no-recurse-submodules --unshallow origin +refs/heads/*:refs/remotes/origin/* +refs/tags/*:refs/tags/*
  Error: error: RPC failed; curl 92 HTTP/2 stream 0 was not closed cleanly: CANCEL (err 8)
  Error: error: 4209 bytes of body are still expected
  fetch-pack: unexpected disconnect while reading sideband packet
  Error: fatal: early EOF
  Error: fatal: fetch-pack: invalid index-pack output
  The process '/usr/bin/git' failed with exit code 128
  Waiting 13 seconds before trying again
  /usr/bin/git -c protocol.version=2 fetch --prune --no-recurse-submodules --unshallow origin +refs/heads/*:refs/remotes/origin/* +refs/tags/*:refs/tags/*
  Error: error: RPC failed; curl 92 HTTP/2 stream 0 was not closed cleanly: CANCEL (err 8)
  Error: error: 5193 bytes of body are still expected
  fetch-pack: unexpected disconnect while reading sideband packet
  Error: fatal: early EOF
  Error: fatal: fetch-pack: invalid index-pack output
  Error: The process '/usr/bin/git' failed with exit code 128
```

Any clue why this might be happning? We have seen this 4 times in master only in the last 24 hours, so it's becoming annoying.

**Comment by ceo-roblox-jun** [comment]
Fetching the repository
  /usr/bin/git -c protocol.version=2 fetch --prune --no-recurse-submodules --unshallow origin +refs/heads/*:refs/remotes/origin/* +refs/tags/*:refs/tags/*
  Error: error: RPC failed; curl 92 HTTP/2 stream 0 was not closed cleanly: CANCEL (err 8)
  Error: error: 2000 bytes of body are still expected
  fetch-pack: unexpected disconnect while reading sideband packet
  Error: fatal: early EOF
  Error: fatal: fetch-pack: invalid index-pack output
  The process '/usr/bin/git' failed with exit code 128
  Waiting 14 seconds before trying again
  /usr/bin/git -c protocol.version=2 fetch --prune --no-recurse-submodules --unshallow origin +refs/heads/*:refs/remotes/origin/* +refs/tags/*:refs/tags/*
  Error: error: RPC failed; curl 92 HTTP/2 stream 0 was not closed cleanly: CANCEL (err 8)
  Error: error: 4209 bytes of body are still expected
  fetch-pack: unexpected disconnect while reading sideband packet
  Error: fatal: early EOF
  Error: fatal: fetch-pack: invalid index-pack output
  The process '/usr/bin/git' failed with exit code 128
  Waiting 13 seconds before trying again
  /usr/bin/git -c protocol.version=2 fetch --prune --no-recurse-submodules --unshallow origin +refs/heads/*:refs/remotes/origin/* +refs/tags/*:refs/tags/*
  Error: error: RPC failed; curl 92 HTTP/2 stream 0 was not closed cleanly: CANCEL (err 8)
  Error: error: 5193 bytes of body are still expected
  fetch-pack: unexpected disconnect while reading sideband packet
  Error: fatal: early EOF
  Error: fatal: fetch-pack: invalid index-pack output
  Error: The process '/usr/bin/git' failed with exit code 128922000014128134209135193              uses: actions/checkout@v4
              with:
                  lfs: false
                  token: ${{ secrets.CHECKOUT_BOT_PERSONAL_ACCESS_TOKEN }}
                  fetch-depth: 0on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          date > generated.txt
          # Note: the following account information will not work on GHES
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "generated"
          git pushgenerated.txtuser.nameuser.emailon:
  pull_request:
    branches: [main]
    types: [opened, synchronize, closed]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4- uses: actions/checkout@v4
  with:
    ref: ${{ github.event.pull_request.head.sha }}github.event.pull_request.head.sha

**Comment by ceo-roblox-jun** [comment]
Fetching the repository
  /usr/bin/git -c protocol.version=2 fetch --prune --no-recurse-submodules --unshallow origin +refs/heads/*:refs/remotes/origin/* +refs/tags/*:refs/tags/*
  Error: error: RPC failed; curl 92 HTTP/2 stream 0 was not closed cleanly: CANCEL (err 8)
  Error: error: 2000 bytes of body are still expected
  fetch-pack: unexpected disconnect while reading sideband packet
  Error: fatal: early EOF
  Error: fatal: fetch-pack: invalid index-pack output
  The process '/usr/bin/git' failed with exit code 128
  Waiting 14 seconds before trying again
  /usr/bin/git -c protocol.version=2 fetch --prune --no-recurse-submodules --unshallow origin +refs/heads/*:refs/remotes/origin/* +refs/tags/*:refs/tags/*
  Error: error: RPC failed; curl 92 HTTP/2 stream 0 was not closed cleanly: CANCEL (err 8)
  Error: error: 4209 bytes of body are still expected
  fetch-pack: unexpected disconnect while reading sideband packet
  Error: fatal: early EOF
  Error: fatal: fetch-pack: invalid index-pack output
  The process '/usr/bin/git' failed with exit code 128
  Waiting 13 seconds before trying again
  /usr/bin/git -c protocol.version=2 fetch --prune --no-recurse-submodules --unshallow origin +refs/heads/*:refs/remotes/origin/* +refs/tags/*:refs/tags/*
  Error: error: RPC failed; curl 92 HTTP/2 stream 0 was not closed cleanly: CANCEL (err 8)
  Error: error: 5193 bytes of body are still expected
  fetch-pack: unexpected disconnect while reading sideband packet
  Error: fatal: early EOF
  Error: fatal: fetch-pack: invalid index-pack output
  Error: The process '/usr/bin/git' failed with exit code 128

**Comment by ceo-roblox-jun** [comment]
> Hi, on a regular basis we face issues with checking out code, and it seems to be happening more frequently in the past couple of weeks.
> 
> We use the checkout action like this:
> 
> ```
>               uses: actions/checkout@v4
>               with:
>                   lfs: false
>                   token: ${{ secrets.CHECKOUT_BOT_PERSONAL_ACCESS_TOKEN }}
>                   fetch-depth: 0
> ```
> 
> Under fetching the repository, this is the log output:
> 
> ```
> Fetching the repository
>   /usr/bin/git -c protocol.version=2 fetch --prune --no-recurse-submodules --unshallow origin +refs/heads/*:refs/remotes/origin/* +refs/tags/*:refs/tags/*
>   Error: error: RPC failed; curl 92 HTTP/2 stream 0 was not closed cleanly: CANCEL (err 8)
>   Error: error: 2000 bytes of body are still expected
>   fetch-pack: unexpected disconnect while reading sideband packet
>   Error: fatal: early EOF
>   Error: fatal: fetch-pack: invalid index-pack output
>   The process '/usr/bin/git' failed with exit code 128
>   Waiting 14 seconds before trying again
>   /usr/bin/git -c protocol.version=2 fetch --prune --no-recurse-submodules --unshallow origin +refs/heads/*:refs/remotes/origin/* +refs/tags/*:refs/tags/*
>   Error: error: RPC failed; curl 92 HTTP/2 stream 0 was not closed cleanly: CANCEL (err 8)
>   Error: error: 4209 bytes of body are still expected
>   fetch-pack: unexpected disconnect while reading sideband packet
>   Error: fatal: early EOF
>   Error: fatal: fetch-pack: invalid index-pack output
>   The process '/usr/bin/git' failed with exit code 128
>   Waiting 13 seconds before trying again
>   /usr/bin/git -c protocol.version=2 fetch --prune --no-recurse-submodules --unshallow origin +refs/heads/*:refs/remotes/origin/* +refs/tags/*:refs/tags/*
>   Error: error: RPC failed; curl 92 HTTP/2 stream 0 was not closed cleanly: CANCEL (err 8)
>   Error: error: 5193 bytes of body are still expected
>   fetch-pack: unexpected disconnect while reading sideband packet
>   Error: fatal: early EOF
>   Error: fatal: fetch-pack: invalid index-pack output
>   Error: The process '/usr/bin/git' failed with exit code 128
> ```
> 
> Any clue why this might be happning? We have seen this 4 times in master only in the last 24 hours, so it's becoming annoying.

🧩

**Comment by ceo-roblox-jun** [comment]
.patch

**Comment by sayaliM0412** [comment]
Seems like Github had an issue on Aug 29 with API Rate limit but it was resolved: https://www.githubstatus.com/incidents/djwfzglh2dyq

I get a _somewhat_ similar error for code:
```
job_name:
    name: Build and deploy code
    runs-on: ubuntu-latest
    env:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha || github.event.after}
```

Error:

```
Fetching the repository
  /usr/bin/git -c protocol.version=2 fetch --no-tags --prune --no-recurse-submodules --depth=1 origin e30bfe795b0493e6117f60a7eeea878695810f49
  remote: Repository not found.
  Error: fatal: repository 'https://github.com/demo/demo-pro/' not found
  The process '/usr/bin/git' failed with exit code 128
  Waiting 16 seconds before trying again
  /usr/bin/git -c protocol.version=2 fetch --no-tags --prune --no-recurse-submodules --depth=1 origin e30bfe795b0493e6117f60a7eeea878695810f49
  remote: Repository not found.
  Error: fatal: repository 'https://github.com/demo/demo-pro/' not found
  The process '/usr/bin/git' failed with exit code 128
  Waiting 20 seconds before trying again
  /usr/bin/git -c protocol.version=2 fetch --no-tags --prune --no-recurse-submodules --depth=1 origin e30bfe795b0493e6117f60a7eeea878695810f49
  remote: Repository not found.
  Error: fatal: repository 'https://github.com/demo/demo-pro/' not found
  Error: The process '/usr/bin/git' failed with exit code 128
```

At this point I have tried without a PAT, `github-token` with a PAT having full access and with `GITHUB_TOKEN`.

**Comment by Martiix** [comment]
Appernanlty this error happens on weak / low cpu and ram self-hosted agents. Our solution is to run these jobs elsewhere, if anyone stumbles upon this post later on.
