### ISSUE TITLE
Execute authenticate git command in the next step after @actions/checkout

### ISSUE THREAD

**Issue by fmontada** [actions/checkout#194]
Hi team 
As part of our CI/CD workflow we are using [Lerna](https://github.com/lerna/lerna) to handle our Javascript mono repo 

So we build, test, deploy and tag/release every-time something get merge to master 

Our question is using @actions/checkout@v2 it is posible to do not delete the Github token in order for us execute git authenticated commands for the tag/release ? 

Cleaning the token make sense but could be great if there is a way to add a toggle for the cleanup in case the workflow need to execute git authenticate commands after the git checkout 

https://github.com/actions/checkout/commit/58070a9fc3a91197fc9cbf24841ea31a2ab19980

```
- uses: actions/checkout@v2
  with:
    token: {{OUR_TOKEN_WITH_GIT_TAG_PERMISION}}
```

**Comment by jsg2021** [comment]
Same as my issue. https://github.com/actions/checkout/issues/166

**Comment by ericsciple** [comment]
@fmontada the input `persist-credentials` controls whether the token is persisted in the local git config. Does that help?

**Comment by gmazzo** [comment]
The doc states that `persist-credentials` is enabled by default. Is that accurate? 

Because in the source code I'm seeing the opposite:
https://github.com/actions/checkout/blob/v2/src/input-helper.ts#L123

And I'm getting this when running a `git push` inside a `Gradle` task:
```
fatal: could not read Username for 'https://***.com': Device not configured
```

**Comment by ericsciple** [comment]
@gmazzo  are you using `actions/checkout@v2` or a different version?

**Comment by gmazzo** [comment]
Yes, I have it like this:
```
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GPR_TOKEN }}
```
But, I just wanted to double-check, because if my understanding of the source code is that it's `false` by default, not `true` as the documentation states...

**Comment by ericsciple** [comment]
The default is `true`. The runner applies [the default](https://github.com/actions/checkout/blob/94c2de77cccf605d74201a8aec6dd8fc0717ad66/action.yml#L50) from the action yaml
