### ISSUE TITLE
Unexpected Results from Checkout for the Commit Hash

### ISSUE THREAD

**Issue by iamrecursion** [actions/checkout#198]
I've recently swapped our CI to use actions rather than Azure, and something very odd is happening when we read the `$GITHUB_SHA` environment variable (used as a key for build artefacts and also in the built binary as metadata). 

The value stored in the environment variable doesn't match the head of the branch, or any commit on the branch, meaning that we can't reliably find the built artefact for any given commit. 

The workflow in question is [this one](https://github.com/luna/enso/blob/master/.github/workflows/scala.yml), and it's very possible that I'm missing something obvious, so any help is appreciated!

**Comment by jsg2021** [comment]
I think you're looking for the [context expression](https://help.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#about-contexts-and-expressions):
```
${{ github.sha }}
```

**Comment by iamrecursion** [comment]
Is that true even if the variable is read in a shell script? I’m getting a commit hash out of `$GITHUB_SHA` in the script, just not the one I expect. 

Please see [here](https://github.com/luna/enso/blob/2edede781d31e1c4443e850eef9c1f21eb852af5/.github/workflows/scala.yml#L114) for the usage in question.

**Comment by ericsciple** [comment]
@iamrecursion is it happening only on pull request builds?

**Comment by ericsciple** [comment]
if so, on a pull request workflow, you might want this SHA instead: https://github.com/actions/checkout#Checkout-pull-request-HEAD-commit-instead-of-merge-commit

**Comment by jsg2021** [comment]
> Is that true even if the variable is read in a shell script? I’m getting a commit hash out of `$GITHUB_SHA` in the script, just not the one I expect. 
> 
> Please see [here](https://github.com/luna/enso/blob/2edede781d31e1c4443e850eef9c1f21eb852af5/.github/workflows/scala.yml#L114) for the usage in question. 

@iamrecursion idk, but the context expression will be interpolated into the script before run, and the env var will be handled by the shell. I would personally prefer the context over the shell.

**Comment by iamrecursion** [comment]
> if so, on a pull request workflow, you might want this SHA instead: https://github.com/actions/checkout#Checkout-pull-request-HEAD-commit-instead-of-merge-commit

This was exactly the issue, thank you Eric!
