### ISSUE TITLE
How to checkout the current branch?

### ISSUE THREAD

**Issue by zeke** [actions/checkout#20]
I want to set up a job that checks out the branch that was pushed. Is it possible to do something like this?

```yml
- uses: actions/checkout@${GITHUB_REF}
```

Reference: https://help.github.com/en/articles/virtual-environments-for-github-actions#environment-variables

**Comment by TingluoHuang** [comment]
try:
```
- uses: actions/checkout@master
  with:
    ref: ${{ github.ref }}
```

**Comment by TingluoHuang** [comment]
BTW, if you just do `- uses: actions/checkout@master`, it will checkout the `GITHUB_SHA`, the `@master` is for versioning this `checkout` action

**Comment by zeke** [comment]
Ah thanks! Should I open a PR to add something to the README for this use case?

**Comment by TingluoHuang** [comment]
sure.

**Comment by zeke** [comment]
Opened a PR: https://github.com/actions/checkout/pull/21

**Comment by fbartho** [comment]
PR is already merged, so this issue could be closed!

**Comment by ethomson** [comment]
Thanks, @zeke!
