### ISSUE TITLE
Using actions/checkout@v1 downloading the repo source for every job run

### ISSUE THREAD

**Issue by manivel-nagarajan** [actions/checkout#208]
Is there any way we can speed up this process? Why actions/checkout@v1 process is happening every time from scratch? Is there any way to fetch only changes and perform lint? For me, It takes around 5 minutes for checkout along in every job run.

Does checkout@v2 solves this problem? Please help me if my understanding is wrong.

**Comment by ericsciple** [comment]
Yes checkout@v2 fetches only a single commit by default

**Comment by manivel-nagarajan** [comment]
Thanks for the clarification!
