### ISSUE TITLE
support renamed default branches

### ISSUE THREAD

**Issue by staabm** [actions/checkout#210]
the `ref:` input parameter seems to be hardcoded falling back to `master`.

https://github.com/actions/checkout/blob/master/README.md#L43-L46

since github support renaming the default branch, IMO the actions/checkout action should take this into account and therefore use the 'default-branch' as a fallback instead of always `master`

**Comment by ericsciple** [comment]
I wonder whether the default branch can be determined from the github event payload. Would enable implementing without making an extra call to the rest api.

**Comment by ericsciple** [comment]
It looks like the default branch can be retrieved from the event payload on disk:

```yaml
      - run: |
          node -p "require(process.env.GITHUB_EVENT_PATH).repository.default_branch"
```

However that would only work for the workflow repo. For other repositories, would need to either query REST API or fallback to master

**Comment by mkalkbrenner** [comment]
An example is drupal/drupal which doesn't have a master branch at all which leads to this error:
```
  /usr/bin/git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin +refs/heads/master:refs/remotes/origin/master
  ##[error]fatal: couldn't find remote ref refs/heads/master
  The process '/usr/bin/git' failed with exit code 128
```
So from my pint of view this is rather a bug than an enhancement.

**Comment by ericsciple** [comment]
I played with the REST API a little bit. The default branch can be retrieved from the REST API.

I'm in favor of doing this feature, just havent gotten to it yet.

**Comment by brettwgreen** [comment]
A lot of people renaming their master branches lately... Haven't looked at this code, but maybe I'll take a look this weekend at making a PR unless you're close to picking this up.

**Comment by ericsciple** [comment]
looking into this now

**Comment by ericsciple** [comment]
PR https://github.com/actions/checkout/pull/278 (testing now)
