### ISSUE TITLE
Provide capability to use a ff-merge as part of checkout only.

### ISSUE THREAD

**Issue by rverma-jm** [actions/checkout#218]
Wondering if we can allow an option as `strategy`, which can do fast-forward merge to base branch in case of we are using this step in a pull-request.

**Comment by ericsciple** [comment]
Scenarios in readme for fetching more branches/history. Also this related to this proposal https://github.com/actions/checkout/pull/155 for additional inputs to fetch additional refs.

**Comment by ericsciple** [comment]
Let me know if ^ solves it. Today workaround would be to write a script that runs the necessary git commands (fetch additional refs, checkout specific branch).

During a PR, let's say i'm merging `my-branch` into `master`, by default a merge commit created by the server, and is checked out. Instead do you want to checkout `my-branch` or `master`?

**Comment by ericsciple** [comment]
Also do you want to only checkout the other branch? Or do you want to have both available locally (e.g. to diff)

**Comment by rverma-jm** [comment]
>During a PR, let's say i'm merging my-branch into master, by default a merge commit created by the server, and is checked out. Instead do you want to checkout my-branch or master?

is a merge commit always equal to state of master branch after merging this PR? If yes then we can close this issue.

**Comment by ericsciple** [comment]
Yep on a pull request, the merge commit (is checked out).

https://help.github.com/en/actions/reference/events-that-trigger-workflows#pull-request-event-pull_request

GITHUB_SHA is a merge commit created from the user branch, onto the base branch.
