### ISSUE TITLE
Invalid path error (Windows only)

### ISSUE THREAD

**Issue by matextrem** [actions/checkout#219]
I'm getting the following error on Windows when checking out the repo: 

```
Checking out the ref
  "C:\Program Files\Git\bin\git.exe" checkout --progress --force -B feature/desktop-app refs/remotes/origin/feature/desktop-app
  ##[error]error: invalid path 'src/test/safe.dom.funds.threshold>1.test.js'
  ##[error]The process 'C:\Program Files\Git\bin\git.exe' failed with exit code 128
```

Build link: https://github.com/gnosis/safe-react/runs/593178948#step:2:397

On Linux and MacOS work perfectly. Any idea what's going on?  

Thanks in advance!

**Comment by mc-perry** [comment]
Why closed? Not fixed.

**Comment by ohsayan** [comment]
+1 here. I'm having the same issue

**Comment by qarlosalberto** [comment]
Same problem

**Comment by acro5piano** [comment]
For anyone who is new to Windows: `>` is not correct a file name in Windows so checkout is failing. renameing 
 `src/test/safe.dom.funds.threshold>1.test.js` to more normal name like `src/test/safe.dom.funds.threshold.test.js` will fix the issue.
