### ISSUE TITLE
suggestions for large repository

### ISSUE THREAD

**Issue by softprops** [actions/checkout#22]
I'm experimenting with Github Actions on a large code repository at `$WORK`. We use a mix of Concourse ci and Jenkins and are looking towards Github Actions as a potential CI/CD tool with less hosting maintenance. 

In some simple experiments we found the actions/checkout command to be slower that expected. A checkout step takes `~6m 53s` using `with.fetch-depth: 1`, and that's before my job can do anything useful.

In our Jenkins set up we have a persistent clone that we do local clones from. In concourse we use the [git resource](https://github.com/concourse/git-resource). In both cases the process of fetching a given version of the code feels faster than actions/checkout and was wondering if there as any actions tuning parameters would could apply to speed up the process

I can see a glimpse into what the action is doing in the output.

```
git remote add origin https://github.com/{org}/{repo}
 git config gc.auto 0
git config --get-all http.https://github.com/{org}/{repo}.extraheader
git config --get-all http.proxy
git -c http.extraheader="AUTHORIZATION: basic ***" fetch --tags --prune --progress --no-recurse-submodules --depth=1 origin +refs/heads/*:refs/remotes/origin/*
```
Is there a way we can opt out of features like fetching all of the tags (we have a lot of tags) or submodules (we don't use submodules)?

I started looking at want concourse git resource does to draw some comparisons. Looking [here](https://github.com/concourse/git-resource/blob/d99b8e5e824f0c4ee4aa096b2ce83894bcf0d2c3/assets/in#L81-L91) I can see it does something like a clone +  checkout operation

```sh
git clone --single-branch $depthflag $uri $branchflag $destination $tagflag

cd $destination

git fetch origin refs/notes/*:refs/notes/* $tagflag

if [ "$depth" -gt 0 ]; then
  "$bin_dir"/deepen_shallow_clone_until_ref_is_found_then_check_out "$depth" "$ref" "$tagflag"
else
  git checkout -q "$ref"
fi
```

I'm not sure if that's any better or worse our experience is that it "feels" more performance that what we see with github actions/checkout.

**Comment by zoispag** [comment]
I have similar problem.
Is there a way to do something like `git clone --single-branch --branch ${{ github.head_ref }} --depth 1 https://github.com/${{ github.repository }}.git` ?

**Comment by softprops** [comment]
@zoispag just curious what was the scope applied to `secrets. CLONE_TOKEN` vs the default GITHUB_TOKEN that GitHub provides to each action?

**Comment by zoispag** [comment]
@softprops I gave repo access.
![image](https://user-images.githubusercontent.com/21138205/65836944-15ab7800-e2f3-11e9-8716-4854b85a1524.png)
Because I needed to clone via https from a private repo, I used the OAuth key of an actual account/github user

**Comment by softprops** [comment]
Thanks. It would be great if `GITHUB_TOKEN` had access to do that. I feel hesitant about these personal access tokens with repo status because they give access to **all** of the repos your github user has access to. I believe `GITHUB_TOKEN` provided by GitHub is scoped to only permissions for the specific repo.

In any case I tried your solution and it worked! down from 7 minutes  I'm at about 1m 22s. That's a huge savings. Thank for for posting a reply and sorry I was late to notice it!

**Comment by zoispag** [comment]
No worries for late replying!
I feel the same about the `CLONE_TOKEN`, but `GITHUB_TOKEN` did not allow to perform this task. 😞Though I am using a "dedicated" GitHub account, which generally acts as a bot, so by definition has access only to this repo.

7m to 1m22s is a huge improvement, so happy to help! 🎉 😁

**Comment by softprops** [comment]
Codified what worked for us here 
 https://github.com/meetup/express-checkout

**Comment by zoispag** [comment]
@softprops I wanted to do the same, but didn't have the time yet.
It would be great to include me as a contributor in your README though ;)

**Comment by softprops** [comment]
@zoispag done! https://github.com/meetup/express-checkout/pull/2

**Comment by XhmikosR** [comment]
This is definitely something that needs to be improved. Fetching all tags and branches can be slow.

**Comment by ericsciple** [comment]
fixing this in [v2](https://github.com/actions/checkout/pull/70), will hopefully merge early next week

**Comment by ericsciple** [comment]
@softprops @XhmikosR checkout `v2-beta` (now in master). waiting for feedback/stabilization, then will push `v2` tag. v2 fetches only a single commit by default

**Comment by stayallive** [comment]
@ericsciple I've enabled it in our repo and we went from 30-40 seconds checkouts to 5-7 ❤️ (even in our teeny tiny 12k commits repo) this is gut! I can only imagine what actual bug repo's will see as improvements!

Thanks for all the work from you and everyone involved!

**Comment by softprops** [comment]
I haven't had a change to take a look yet but would it be possible to post a comment to this issue when there's an official v2 release published?

**Comment by softprops** [comment]
I just ran a benchmark on our largest repo. This now comparable in performance to [our work around](https://github.com/meetup/express-checkout). As soon as the beta version changes to v2 we're just going to switch to actions/checkout proper

**Comment by ericsciple** [comment]
published `v2` tag

**Comment by softprops** [comment]
Works great! Thanks folks

**Comment by gregwym** [comment]
with `checkout@v2` it indeed saves a lot of bandwidth but seems much slower on the download speed. Please see the comparison bellow. I suspect it is because GitHub has to do the compression on the fly when fetching with `--depth=1`?

V1
![image](https://user-images.githubusercontent.com/510089/71149998-27097e00-226b-11ea-9a09-1baec170ffae.png)

V2
![image](https://user-images.githubusercontent.com/510089/71150013-2f61b900-226b-11ea-818a-f38c390d99eb.png)
