### ISSUE TITLE
Post Checkout sources fails

### ISSUE THREAD

**Issue by D4nte** [actions/checkout#223]
In this [run](https://github.com/comit-network/comit-rs/pull/2496/checks?check_run_id=603609140), "Post Checkout sources" fails but I cannot seem to find any error or log related to the failure.

Can you please review and point me to the right direction (or fix the issue).

Thanks!

**Comment by ericsciple** [comment]
Is it a one-off occurrence? I noticed the logs aren't available even for the previous step. I wonder if the agent lost connectivity and never finished uploading logs.

**Comment by D4nte** [comment]
It happened few times but it seems to be stable now. I wonder if it's related to the disk space issues that recently happened.
