### ISSUE TITLE
'/tarball/v2' status code 500

### ISSUE THREAD

**Issue by Juu-** [actions/checkout#225]
Hi everyone,

I'm having some issues with actions/checkout@v2

It worked yesterday and I don't change anything in the workflow file.
Here is the console output:

```shell
Current runner version: '2.169.0'
Operating System
  Ubuntu
  18.04.4
  LTS
Virtual Environment
Prepare workflow directory
Prepare all required actions
Download action repository 'actions/checkout@v2'
##[warning]Failed to download action 'https://api.github.com/repos/actions/checkout/tarball/v2'. Error Response status code does not indicate success: 500 (Internal Server Error).
##[warning]Back off 20.741 seconds before retry.
##[warning]Failed to download action 'https://api.github.com/repos/actions/checkout/tarball/v2'. Error Response status code does not indicate success: 500 (Internal Server Error).
##[warning]Back off 21.909 seconds before retry.
##[error]Response status code does not indicate success: 500 (Internal Server Error).
```

I'm available for any questions,
Julien

**Comment by aniketdharia** [comment]
same error actions stopped working

**Comment by Paul1365972** [comment]
I have exactly the same problem

**Comment by aniketdharia** [comment]
Current runner version: '2.169.1'
Operating System
  Ubuntu
  18.04.4
  LTS
Virtual Environment
  Environment: ubuntu-18.04
  Version: 20200406.2
  Included Software: https://github.com/actions/virtual-environments/blob/ubuntu18/20200406.2/images/linux/Ubuntu1804-README.md
Prepare workflow directory
Prepare all required actions
Download action repository 'actions/checkout@v2'
##[warning]Failed to download action 'https://api.github.com/repos/actions/checkout/tarball/v2'. Error Response status code does not indicate success: 500 (Internal Server Error).
##[warning]Back off 14.66 seconds before retry.
##[warning]Failed to download action 'https://api.github.com/repos/actions/checkout/tarball/v2'. Error Response status code does not indicate success: 500 (Internal Server Error).
##[warning]Back off 18.172 seconds before retry.
##[error]Response status code does not indicate success: 500 (Internal Server Error).

**Comment by fabian-laine** [comment]
Idem here

**Comment by bitbreakr** [comment]
Same here 
<img width="1310" alt="Screenshot 2020-04-23 at 16 21 40" src="https://user-images.githubusercontent.com/3123986/80110031-86abc900-857e-11ea-857b-03489bfd4b03.png">

**Comment by aniketdharia** [comment]
> it suddenly started running now.

**Comment by Juu-** [comment]
> > it suddenly started running now.

Workflow started too 👍

**Comment by wrdaigle** [comment]
I have a cron job that runs every 5 minutes and this happens about once a day for up to an hour, usually in the middle of the night.

**Comment by Juu-** [comment]
Github have some issues right now :/
[https://www.githubstatus.com/](https://www.githubstatus.com/)

**Comment by ericsciple** [comment]
Sorry for the disruption. Sounds like this aligned with a disruption on the service side.

Good to open issues here when it's happening (community benefits). Closing now since that incident has passed.

**Comment by jbir789** [comment]
We're seeing the same issue as of yesterday. Is there another disruption?

**Comment by joshuapinter** [comment]
Seeing this issue now. Best thing to do is keep an eye on [GitHub Status](https://www.githubstatus.com/): 

![image](https://user-images.githubusercontent.com/180819/107246070-1d058a00-69ed-11eb-9637-1af0337f9ca0.png)

We only switched to GitHub Actions this year. Wasn't expecting our workflow to be halted because of this.
