### ISSUE TITLE
Checkout times out after 45 min in a large repository

### ISSUE THREAD

**Issue by epicfaace** [actions/checkout#231]
Here's the github actions workflow file:

https://github.com/TheStanfordDaily/archives-text/commit/5655720c67a8028a56c2efd66f9a75794355107b

Here are the workflow results:

https://github.com/TheStanfordDaily/archives-text/runs/635248983?check_suite_focus=true

Note that the checkout times out after 45 minutes.

![image](https://user-images.githubusercontent.com/1689183/80806801-a009d200-8b89-11ea-86dc-32dbeb2a8b93.png)

**Comment by ericsciple** [comment]
Was it a one time thing? Or does it consistently happen? Looks like the machine may have gotten disconnected since none of the logs are available.

**Comment by epicfaace** [comment]
Right -- probably a one-time thing. It's working fine now.
