### ISSUE TITLE
Configure git

### ISSUE THREAD

**Issue by davidkarlsen** [actions/checkout#233]
Prior to running git-commands I have to configure git:
```
        git config --global committer.email "noreply@github.com"
        git config --global committer.name "GitHub"
        git config --global author.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git config --global author.name "${GITHUB_ACTOR}"
```
Could this be fixed by the action instead - it seems as sane default, and could be opt-in. Having to configure it manually is painful.

**Comment by peaceiris** [comment]
How about `git config --local`, not `--global`?

**Comment by davidkarlsen** [comment]
Yes. Local makes more sense.

**Comment by davidkarlsen** [comment]
I guess this duplicates:
* https://github.com/actions/checkout/issues/13
* https://github.com/actions/checkout/pull/158

Maybe it would even make sense to have the job-environment initialized with the variables: https://git-scm.com/book/en/v2/Git-Internals-Environment-Variables in default variables: https://help.github.com/en/actions/configuring-and-managing-workflows/using-environment-variables#default-environment-variables

**Comment by ericsciple** [comment]
Closing since duplicate. Add any feedback to ADR. It's something I think should be added, just havent gotten to it yet.

**Comment by ericsciple** [comment]
Also `+1` the ADR :)

**Comment by davidkarlsen** [comment]
@ericsciple Maybe link the ADR? There are several issues link to this (#233) issue.
