### ISSUE TITLE
Fetch tags by default

### ISSUE THREAD

**Issue by tamalsaha** [actions/checkout#240]
checkout@v1 used to pull all tags by default. It seems that checkout@v2 passes --no-tags flag and does not pull the tags by default. Can you bring back the old behavior because we use those tags to tag docker images etc. This seems like an unusual default.

**Comment by ericsciple** [comment]
Checkout v2 is optimized for perf for mainline scenario (fetches single commit). Updating to make it easy with this PR: https://github.com/actions/checkout/pull/258

**Comment by atDTSystemsLtd** [comment]
>Checkout v2 is optimized for perf for mainline scenario (fetches single commit).

This is very strange "mainline scenario". 

I have to agree with author of this issue, `--no-tag` is (for the lack of better word) unusual default.
