### ISSUE TITLE
Git version must 2.18 or higher??!!

### ISSUE THREAD

**Issue by yeasinhossain-dsi** [actions/checkout#255]
I have updated my git version to 2.18. But still getting following error:

```
The repository will be downloaded using the GitHub REST API
To create a local Git repository instead, add Git 2.18 or higher to the PATH
Downloading the archive
Not Found
Waiting 11 seconds before trying again
Downloading the archive
Not Found
Waiting 13 seconds before trying again
Downloading the archive
##[error]Not Found
```

Git hub action has really disappointed me, it always fails when it had to perform the best. Few days ago i got another issue with the action/scp, all of a sudden it just stopped working showing time out. Now i moved on to use self hosted so that i will not get this timeout issue, it stopped working because of git version. Totally frustrating.

**Comment by ericsciple** [comment]
Sorry for the disruption. It's not the git version. When Git 2.18 or higher is not in the path, it falls back to the REST API to download the tarball. There is an active incident right now, issue with the token permission. It's not limited to the checkout action.

**Comment by ericsciple** [comment]
Related to https://github.com/actions/checkout/issues/254

**Comment by NZSmartie** [comment]
I'm having a similar issue. however, the main repository checkouts just fine. but the wiki repository fails. (i.e. `user/repository.wiki`)

**Comment by ericsciple** [comment]
Closing since this was related to the indicident last week. Please reopen if still having issues.

@NZSmartie sounds like a different issue. Responded on the other issue [here](https://github.com/actions/checkout/issues/254#issuecomment-633161158).

**Comment by mhemken-vts** [comment]
I'm having this issue now, but the github status page is green across the board. Could it be that there are lingering side effects to the outages recently?
