### ISSUE TITLE
Github actions checkout failing

### ISSUE THREAD

**Issue by damntrecky** [actions/checkout#256]
The native checkout v1 seems to be failing the last two days. Is there any major updates to your system that would cause this? We have had stable builds for 6+ months and all of our repositories are failing to checkout in actions/ci.

Our private repositories are failing. The earliest I can find the issue is 2 days ago.

<img width="992" alt="Image 2020-05-22 at 3 52 02 PM" src="https://user-images.githubusercontent.com/38665452/82714630-5d955b80-9c44-11ea-8c5b-853983a2ca22.png">

Git version:

<img width="405" alt="Image 2020-05-22 at 3 58 00 PM" src="https://user-images.githubusercontent.com/38665452/82714779-0ba10580-9c45-11ea-9e17-4adbf482e54f.png">

I don't even know how to debug more since the runner is not ours and the actions repository is open source here. Any help to track this down would be useful.

<img width="579" alt="Image 2020-05-22 at 4 00 17 PM" src="https://user-images.githubusercontent.com/38665452/82714858-72262380-9c45-11ea-9336-a65859a88694.png">

**Comment by medienlampe** [comment]
This is a duplicate of #254 and caused by an incident at Github itself.

**Comment by damntrecky** [comment]
Thanks. I'll close this issue out and move discussion in to that ticket.
