### ISSUE TITLE
Hi I am trying to fetch the remote commit id before pushing my local/branch to remote/branch during on push option. Do we have any way to get remote commit id before we synch local branch to remote branch

### ISSUE THREAD

**Issue by ajishikea** [actions/checkout#260]
Thank you 🙇‍♀ for wanting to create an issue in this repository. Before you do, please ensure you are filing the issue in the right place. Issues should only be opened on if the issue **relates to code in this repository**.

* If you have found a security issue [please submit it here](https://hackerone.com/github)
* If you have questions about writing workflows or action files, then please [visit the GitHub Community Forum's Actions Board](https://github.community/t5/GitHub-Actions/bd-p/actions)
* If you are having an issue or question about GitHub Actions then please [contact customer support](https://help.github.com/en/articles/about-github-actions#contacting-support)

If your issue is relevant to this repository, please delete this text and continue to create this issue. Thank you in advance.

**Comment by ericsciple** [comment]
Can you help me understand the scenario better?

**Comment by ajishikea** [comment]
Hi,

Thanks for your response. Kindly check the yml file I have attached. I have not compiled but hope you understand the concept.

I am trying to get a remote branch commit id on push action before my local branch commit changes get Synchronize.

For example:
              We have a branch name called v1_dev. When we have clone into our local it will have two references one remotes/origin/v1_dev and another v1_dev.
              If I do any changes locally and commit it will available into v1_dev branch until I have execute push. Once I have execute push it will be synchronize with remotes/origin/v1_dev (remote branch).
              I am trying to fetch the remote branch commit id before pushing my local branch changes to remote branch.
              Imagine remotes/origin/v1_dev has commit id (abcdef) and when we clone local branch it also have same commit reference. Now I have made some changes a done commit1(aaaaaa) again I have done some changes and It has second commit as (bbbbbb). When I am trying to push in git action I can able to get the local branch commit id only ie, (bbbbbb). Using GITHUB_SHA. But we I need to get remote branch commit id before synchronizing any function available in git hub action?

Our Scenario:
              Imagine we have multiple modules in a single git repository like Dataflow, Functions, Pusub for each modules.
              When developer trying to push local commit (N number of commits) to remote branch need to fetch what all files got change. Usually in git we can use git diff --name-only remote/HEAD HEAD.
              Above git comment I need to pass remote branch commit id and local branch commit id. I can able to fetch now remote branch commit id after synchronize. But need to get commit Id before synchronize as well.
So I able to get it I will compile only those module instead of all the modules.
              Reason for compiling only those is we have 300+ modules. Might be 1 or 2 module got changes. So we will be compiling only those modules and deploy into Artifactory.

Thanks
Ajish.R

**Comment by ericsciple** [comment]
You can use this snippet to dump the github context:

```yaml
     - name: Dump GitHub context
       env:
         GITHUB_CONTEXT: ${{ toJson(github) }}
       run: echo "$GITHUB_CONTEXT"
```

For a push event, it will look something like this:

```
{
  "ref": "refs/heads/testing",
  "sha": "bd84898f78861ae16c53f765c342ba639dac38ec",
  "event_name": "push",
  [...]
  "event": {
    "after": "bd84898f78861ae16c53f765c342ba639dac38ec",
    "before": "ae6fd5ce6629d6c7aa98b2ae4cc54130de599461",
    [...]
```

It sounds like the `before` value is what you are looking for. You can access the context values using the workflow expression syntax:

```
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # fetch all history
      - run: |
          git diff ${{ github.event.before }}..${{ github.event.after }}
```

**Comment by ericsciple** [comment]
Hope that helps, let me know. Forgot to include a link to the [contexts and expressions doc](https://help.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions)

**Comment by ajishikea** [comment]
Thanks Eri. Thanks solved my issues. I am new to this might be i will reach again if i need any help on other events. Thanks a lot for quick response.

**Comment by ajishikea** [comment]
Can i able to revert back to github.event.before commit id if some things goes wrong? For example i am trying to compile my source code for only modified modules. If any compilation failed i need to revert back the changes. As a CI i will try to upload to Artifactory(Jfrog) if push action fail in middle can i able to delete the Artifcatory using the events or we need to write custom script?

**Comment by ericsciple** [comment]
I would suggest validating in a workflow that runs on PR events, before merging into the default branch (for example `master`).

Otherwise you could use [`git revert`](https://git-scm.com/docs/git-revert), if the changes were already merged to the default branch.

Hope that helps.

Folks on the [GitHub Community Forum](https://github.community/) may have better suggestions. This repo is specific to the checkout action.

**Comment by vanZeben** [comment]
Going to close this issue as it seems to have been answered already. If you're still having a problem, please feel free to reopen this :)
