### ISSUE TITLE
Wrong commit hash when an opening a pull request

### ISSUE THREAD

**Issue by leoniloris** [actions/checkout#261]
When I open a pull request, the commit hash pointed in the checked out repository is not the correct one.

Test repository:
https://github.com/leoniloris/test

Test with the correct commit hash 
https://github.com/leoniloris/test/actions/runs/119262915
![image](https://user-images.githubusercontent.com/22769167/83290015-55956880-a1bc-11ea-9953-7503787333b0.png)

Test with the wrong commit hash
https://github.com/leoniloris/test/runs/721273157
![image](https://user-images.githubusercontent.com/22769167/83289966-3eef1180-a1bc-11ea-811f-f6a448f87752.png)

**Comment by ericsciple** [comment]
The commit `a97a919d9c70932a5d9bc96e11255704cd12395c` is the merge commit created for the pull request.

Check the log in the checkout step, it prints `git log -1` to dump info about the current commit:

```
/usr/bin/git log -1
commit a97a919d9c70932a5d9bc96e11255704cd12395c
Author: Leoni Mota Loris <leoniloris1@hotmail.com>
Date:   Fri May 29 17:52:34 2020 +0000

    Merge 39030f648fce8cd95969e8152652cbae90ed47e7 into 1f36c07b6e539f160b7a19bca587f6e260d0e499
```

The message `Merge 39030f648fce8cd95969e8152652cbae90ed47e7 into 1f36c07b6e539f160b7a19bca587f6e260d0e499` matches your expected SHA (`39030f6`)

**Comment by aeneasr** [comment]
How do I get the non-merge commit?

**Comment by aeneasr** [comment]
RTFM :) https://github.com/actions/checkout#Checkout-pull-request-HEAD-commit-instead-of-merge-commit
