### ISSUE TITLE
Checkout Local Repo without using actions/checkout

### ISSUE THREAD

**Issue by amasingh7168** [actions/checkout#269]
Is there a way to access local repo without using actions/checkout@v2 ? I ask this because there is an 'Actions' setting : **Enable local Actions only for this repository** and if that setting is enabled, I am not able to use actions/checkout, hence cannot access my local repo. Either the setting contradicts github docs or I am doing something wrong. 
Thanks for your help. 

PS: I had to post this question here because the below link doesn't exist.

* If you have questions about writing workflows or action files, then please [visit the GitHub Community Forum's Actions Board](https://github.community/t5/GitHub-Actions/bd-p/actions)

**Comment by ericsciple** [comment]
That's a good question. I dont know :(

Perhaps you could use curl to download the tarball for `$GITHUB_SHA`

From the broken link I was able to follow the [Support Community](https://github.community/) link near the top, and found a link to the category GitHub Actions currently [pointing here](https://github.community/c/github-actions/41)

**Comment by ericsciple** [comment]
Looks like someone provided an [answer here](https://github.community/t/how-can-i-check-out-code-with-enable-local-actions-only-for-this-repository-permission/16682)
