### ISSUE TITLE
Reuse credentials

### ISSUE THREAD

**Issue by eine** [actions/checkout#300]
I'm currently using v2 of this action to clone a repo. In the workflow, some assets are generated, and I want to upload them to a branch (either in the same repo or in a different repo). I am using [release.sh](https://github.com/buildthedocs/sphinx.theme/blob/master/release.sh) to copy sources to a new directory, create a new git repo there, create an orphan branch (`gh-pages`) and push it. Currently, I need to set the origin as https://github.com/buildthedocs/sphinx.theme/blob/e1a0dbe8ba6843322194607aad45195d38f5ce5d/.github/workflows/doc.yml#L17. I saw that this action creates the following configuration:

```
remote.origin.url=https://github.com/buildthedocs/sphinx.theme
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
http.https://github.com/.extraheader=AUTHORIZATION: basic ***
```

Unfortunately, I could not reuse `http` to configure the new clean/orphan repo that is created in the workflow. I'd like to know which is the recommended approach to replace https://github.com/buildthedocs/sphinx.theme/blob/e1a0dbe8ba6843322194607aad45195d38f5ce5d/.github/workflows/doc.yml#L17 and https://github.com/buildthedocs/sphinx.theme/blob/master/release.sh#L12-L13 with the credentials created by this action.

/cc @ericsciple

**Comment by ericsciple** [comment]
If you add another remote, the `http.https://github.com/.extraheader` setting should apply to that remote also. It applies to all remotes that start with `https://github.com/`.

Otherwise if you are initializing a new repo, you could add the `https://github.com/.extraheader` setting to that repo's local git config.

Does that help?

**Comment by ericsciple** [comment]
Otherwise [here's the code](https://github.com/actions/checkout/blob/01aecccf739ca6ff86c0539fbc67a7a5007bbc81/src/git-auth-helper.ts#L56) that that formats the auth header. Hope that helps, let me know.

**Comment by eine** [comment]
> If you add another remote, the `http.https://github.com/.extraheader` setting should apply to that remote also. It applies to all remotes that start with `https://github.com/`.

Yes, this works. However, I want to create a new repo...

> Otherwise if you are initializing a new repo, you could add the `https://github.com/.extraheader` setting to that repo's local git config.

Exactly, this is what I want to do. How do I save the content of `https://github.com/.extraheader` to an envvar and then apply that to a new repo? I tried something such as `GIT_EXTRA="$(git config -l | grep "http\.")`, but then I don't know how to apply it. `git config "$GIT_EXTRA"` does not work, for obvious reasons (the envvar contains `http.https://github.com/.extraheader=AUTHORIZATION: basic ***`, so the arguments are not correctly interpreted).

> Otherwise [here's the code](https://github.com/actions/checkout/blob/01aecccf739ca6ff86c0539fbc67a7a5007bbc81/src/git-auth-helper.ts#L56) that that formats the auth header. Hope that helps, let me know.

I believe what I'm missing is how to apply it with `git config`, not how to generate it, since my purpose is precisely to avoid generating it and reuse it instead.

**Comment by ericsciple** [comment]
The env var does not really contain `***`. Secrets are scrubbed from the log and replaced with `***`.

This should work to get the value-only:

`GIT_EXTRA="$(git config --local --get 'http.https://github.com/.extraheader')"`

And then in the other repo, can set it using: `git config 'http.https://github.com/.extraheader' "$GIT_EXTRA"`

In the code I linked, a little bit different approach is taken to avoid the secret being logged by [Windows process creation audit events](https://docs.microsoft.com/en-us/windows-server/identity/ad-ds/manage/component-updates/command-line-process-auditing). Large enterprises commonly capture those events to the security log, so any credential passed via the command-line (i.e. the `git` command) would get recorded. Instead I configure a placeholder value, then use javascript to find/replace the placeholder in the file `.git/config`.

**Comment by eine** [comment]
@ericsciple always fast and effective. Thanks a lot for those guidelines! That's precisely what I was asking.

So, I assume that I need to copy the value from one `.git/config` to another. However, if `git` is logged, I would expect `sed` and `cat` to be logged too. Hence, I need to use any (scripting) language that allows to read/write/modify files without calling any external command. Is this correct?

**Comment by ericsciple** [comment]
That's what i would recommend as a best practice. It's best to keep credentials off the command line.

Note, `cat` wouldn't matter because the command line would just be `cat the-file-name` (captured by audit event) and the sensitive data would flow through the stdout stream (not captured).

**Comment by eine** [comment]
Thanks! In the end, just copying the config file worked (https://github.com/buildthedocs/sphinx.theme/commit/c3ed1178e6e849f6055f688fc29e3201cd4aa5e5) because it is the same repo after all.
