### ISSUE TITLE
Check warning: What is the call to action about?

### ISSUE THREAD

**Issue by peterjuras** [actions/checkout#313]
Hi,

I started seeing annotations with warnings from this action:

<img width="1083" alt="Screenshot 2020-07-29 at 10 20 53" src="https://user-images.githubusercontent.com/3640638/88775653-419ec080-d185-11ea-849f-f953c838be4d.png">

I'm assuming that this is due to the default branch name change, however I don't understand how this is relevant to my repositories and why this is displayed. Does it not take the default branch name automatically? Why should I need to hardcode a branch name?

**Comment by ericsciple** [comment]
Best to pin to a major-version `uses: actions/checkout@v2` (v2 tag slides forward to receive bug fixes)

`master`/`main` is unstable, and will eventually become v3 (compat breaking changes)

**Comment by peterjuras** [comment]
Hi @ericsciple 

thanks for the response, now I understand what the warning is about. I understood it as a change in the functionality of how checkout works and which branch it uses for a feature.

It might be worth it to make the annotation clearer, e.g.:
```
The "master" branch is no longer the default branch name for actions/checkout
Please update your GitHub action job steps and pin `actions/checkout` to a specific version. It is recommended to pin to a major version.
Example:
```
```yml
steps:
      - uses: actions/checkout@v2
      - run: # ...
```
