### ISSUE TITLE
Checkout fails in docker runner

### ISSUE THREAD

**Issue by zacker150** [actions/checkout#315]
When running with `git version 2.28.0.windows.1`with 

```
    - uses: actions/checkout@v2
```

 checkoutv2 fails with error 
```
  ##[error]error: RPC failed; curl 56 Failure when receiving data from the peer
  ##[error]error: 174 bytes of body are still expected
  ##[error]fatal: the remote end hung up unexpectedly
  ##[error]fatal: early EOF
  ##[error]fatal: index-pack failed
  warning: unable to unlink '(NULL)': Invalid argument
  ##[error]The process 'C:\Program Files\Git\cmd\git.exe' failed with exit code 128
```

**Comment by ericsciple** [comment]
Can you clarify what you mean by \"docker runner\"?

It looks like one of the git commands failed. Not enough of the log was shown, was it fetch? Are you able to reproduce the issue by manually running the git commands? I'm wondering whether it's an issue with git on the machine/container?

**Comment by zacker150** [comment]
I did some testing, and it looks like the issue was an issue with docker networking. I'll close the issue now.
