### ISSUE TITLE
Is this action magic? Where's the code that does the work?

### ISSUE THREAD

**Issue by fearphage** [actions/checkout#32]
I'm just wondering how this works at all and if I can make similar code-free actions.

**Comment by thomaseizinger** [comment]
I guess this line in the `action.yml` explains things:

https://github.com/actions/checkout/blob/94d077c24971944d312dd9197c1bdfba62b39878/action.yml#L21-L23

**Comment by fearphage** [comment]
Ahh, that was added after my issue. Thanks for the heads up.
