### ISSUE TITLE
caching the action itself

### ISSUE THREAD

**Issue by merou** [actions/checkout#322]
I was wondering if there a way to cache the action (actions/checkout@v2) itself?
I am using `self-hosted` runners.

I often get this message:
Download action repository 'actions/checkout@v2'
##[warning]Failed to download action 'https://api.github.com/repos/actions/checkout/tarball/v2'. Error: The operation was canceled.
##[warning]Back off 21.619 seconds before retry.****

After a few retries it works but it considerably delay the whole workflow.

I am thinking of writing my own run commands to checkout a repository, but I would rather use this action.

**Comment by cory-miller** [comment]
This is now possible using the scripts at https://github.com/actions/action-versions
