### ISSUE TITLE
Recursive Submodules

### ISSUE THREAD

**Issue by thorker** [actions/checkout#34]
Is it possible to extend the parameters to update submodules by **--recursive** or make it configurable?

**Comment by TingluoHuang** [comment]
try:
```
- uses: actions/checkout@v1
  with:
    submodules: recursive
```

**Comment by thorker** [comment]
ah, that´s it. thx

**Comment by jlxdp** [comment]
I ran into this issue too, I think other configuration options should be updated into the README, since the `action.yml` only mentioned that the value for this input will be false, I assumed it will only be a choice between `true` or `false` to fetch the submodules
