### ISSUE TITLE
"No such file or directory" on any command after checkout@v1 with path: main

### ISSUE THREAD

**Issue by Warchant** [actions/checkout#348]
When checkout@v1 is used with `path: main`, first bash command after that will fail.

Here is repo with bug reproduction: https://github.com/Warchant/actions-checkout-path-bug/actions

V2 is not affected.
V1 build fails with "No such file or directory": https://github.com/Warchant/actions-checkout-path-bug/runs/1116280208?check_suite_focus=true

**Comment by ericsciple** [comment]
Fixed with runner [v2.273.2](https://github.com/actions/runner/releases/tag/v2.273.2) which finished rolling out everywhere now
