### ISSUE TITLE
Question: git clean with double `-f`

### ISSUE THREAD

**Issue by exalted** [actions/checkout#378]
What's the difference between `git clean -ffdx` and `git clean -fdx` (note single `f`)?

**Comment by Margen67** [comment]
> 
> 
> What's the difference between `git clean -ffdx` and `git clean -fdx` (note single `f`)?

@exalted https://github.com/capistrano/capistrano/issues/135#issuecomment-19792899

**Comment by exalted** [comment]
Thanks @Margen67 🙏
