### ISSUE TITLE
Possible Bump Needed in actions/core

### ISSUE THREAD

**Issue by oliveirafilipe** [actions/checkout#380]
Hi Folks!

As you guys at Github may know, there is a [security vulnerability](https://github.com/advisories/GHSA-mfwh-5m23-j46w) involving `add-path` and `set-env`.

The recommended is:

_For now, users should upgrade to `@actions/core v1.2.6` or later, and replace any instance of the set-env or add-path commands in their workflows with the new Environment File Syntax._

Is there any reason why this action is still using an old version of `@actions/core`?

https://github.com/actions/checkout/blob/5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f/package.json#L29
https://github.com/actions/checkout/blob/5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f/package-lock.json#L6-L11

**Comment by oliveirafilipe** [comment]
Sorry guys, I didn't see that already there is an PR with this bump: https://github.com/actions/checkout/pull/361

**Comment by peaceiris** [comment]
Actually, the `actions/checkout` does not use the `core.addPath` and `core.exportVariable` so I do not think this action throws the error message. Maybe, you need to check which action returns the message.

**Comment by oliveirafilipe** [comment]
Hi @peaceiris , indeed this action does not use the `core.addPath` and `core.exportVariable`. I was just reviewing all the actions in my pipeline and seeing if they already had updated their `action/core` version since it is a very important patch. 

Since there is already an PR with this bump, I will close this issue.
