### ISSUE TITLE
Action stopped working

### ISSUE THREAD

**Issue by zoispag** [actions/checkout#394]
Action stopped working a few minutes ago. All builds are failing. (Private repo)

![image](https://user-images.githubusercontent.com/21138205/100465622-ec8d9f80-30cf-11eb-922a-9162c8f93e22.png)

Is there something happening?

**Comment by kyler-hyuna** [comment]
Can confirm. Sent a ticket to enterprise support, no response yet

**Comment by EPMatt** [comment]
Same issue here, the action suddenly stopped working.

**Comment by hfhbd** [comment]
Me too, but only at private repos. At public repos, the actions runs fine...

**Comment by Brunier** [comment]
Same here

**Comment by eujoy** [comment]
Same here

**Comment by louislefebvre** [comment]
> Me too, but only at private repos. At public repos, the actions runs fine...

Same here, our repo is private. Not public. Might be a reason thus?

**Comment by EPMatt** [comment]
It looks like it has already happened back in May this year. #254

**Comment by anton-brass** [comment]
same here

**Comment by aosorio-avilez** [comment]
Same here

**Comment by jerbob** [comment]
Same here

**Comment by rogaha** [comment]
same here

**Comment by otukutun** [comment]
I came across this issue with private repo.

**Comment by menisy** [comment]
same here

**Comment by kamyar** [comment]
failing also here for a private repository.
can you please update: https://www.githubstatus.com/ ?
Wasted time trying to debug when it was showing green

**Comment by KrystianBalwierzJorsek** [comment]
same here

**Comment by ramondelafuente** [comment]
same here

**Comment by delete-44** [comment]
+1. Thought I was going mad, this thread is a relief 😆

**Comment by Giorgiosaud** [comment]
same here

**Comment by turing95** [comment]
Same here, I think Github's intern screwed up

**Comment by chingc** [comment]
Same.  Can confirm this is affecting private repos.  I tried it in a [personal public repo](https://github.com/chingc/gha-test/runs/1464490861?check_suite_focus=true#step:2:1) and it worked fine.

```
name: test

on: push

jobs:
  checkout-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
```

**Comment by kyler-hyuna** [comment]
Seems self-hosted actions are also affected https://twitter.com/CryptoChybro/status/1332352039800680448?s=20

**Comment by xinatcg** [comment]
oh .. is it the GitHub internal mistake for this issue? so annoying

**Comment by fractos** [comment]
Sigh.

**Comment by xinatcg** [comment]
i just push several version, just think it is unlucky for me for first several fail...

**Comment by makedirectory** [comment]
Also experiencing this issue. Seems like there is an extra forward slash added to the repo URL?

**Comment by fparisima** [comment]
Same here.

**Comment by NeoHuang** [comment]
same issue here

**Comment by beInDev** [comment]
Ditto.

**Comment by jethas-bennettjones** [comment]
Looks like they're aware of it and they're looking into it: https://www.githubstatus.com/incidents/vts24q167tc8

**Comment by theobolo** [comment]
Seems that something bigger is happening on internet right now, not only Github.

As @kyler-hyuna mentioned it, my own self-hosted pipelines are not running on AWS (Paris), can't deal with the checkout process. 

Btw, in France lot of people complained about DNS problems, affecting Orange (internet provider) on several websites (Amazon / Twitch / Github / Paypal / etc...)

**Comment by beInDev** [comment]
> Seems that something bigger is happening on internet right now, not only Github.
> 
> As @kyler-hyuna mentioned it, my own self-hosted pipelines are not running on AWS (Paris), can't deal with the checkout process.
> 
> Btw, in France lot of people complained about DNS problems, affecting Orange (internet provider) on several websites (Amazon / Twitch / Github / Paypal / etc...)

Source please, directly interested by this

**Comment by nanaones** [comment]
same here...

**Comment by theobolo** [comment]
> > Seems that something bigger is happening on internet right now, not only Github.
> > As @kyler-hyuna mentioned it, my own self-hosted pipelines are not running on AWS (Paris), can't deal with the checkout process.
> > Btw, in France lot of people complained about DNS problems, affecting Orange (internet provider) on several websites (Amazon / Twitch / Github / Paypal / etc...)
> 
> Source please, directly interested by this

Source ? Just my own investigations, and twitter feed by searching 'github down orange' on twitter :D

**Comment by ptheohar** [comment]
same here...

**Comment by amiriun** [comment]
same here ...

**Comment by dilip-panwar-by** [comment]
We are also facing same issue

**Comment by hfhbd** [comment]
It is working again

**Comment by socheatsok78** [comment]
https://www.githubstatus.com/incidents/vts24q167tc8

**Comment by beInDev** [comment]
> > > Seems that something bigger is happening on internet right now, not only Github.
> > > As @kyler-hyuna mentioned it, my own self-hosted pipelines are not running on AWS (Paris), can't deal with the checkout process.
> > > Btw, in France lot of people complained about DNS problems, affecting Orange (internet provider) on several websites (Amazon / Twitch / Github / Paypal / etc...)
> > 
> > 
> > Source please, directly interested by this
> 
> Source ? Just my own investigations, and twitter feed by searching 'github down orange' on twitter :D
> 
> It started with a "potential" orange dns issue, i wasn't able to reach any github.com source IP.
> Then, all my Github Actions self hosted pipelines, went down, not able to checkout any of my private repository.
> 
> On Twitter some people with Orange provider were also arguing that they weren't able to reach some other website like Paypal / Amazon / Twitch / Etc ...
> 
> I moved to Google DNS on IPv4, same thing
> I moved to Cloudflare DNS on IPv4, and it worked again
> 
> But basically, it's more than a DNS issue, since AWS has the same problem on their own infrastructure.
> 
> The only common thing is that i'm using the french AWS Datacenter. So ...

Had no issue as an Orange user personally, might be because I'm always on OpenDNS servers though, thanks for the update 👌

**Comment by socheatsok78** [comment]
> Seems that something bigger is happening on internet right now, not only Github.
> 
> As @kyler-hyuna mentioned it, my own self-hosted pipelines are not running on AWS (Paris), can't deal with the checkout process.
> 
> Btw, in France lot of people complained about DNS problems, affecting Orange (internet provider) on several websites (Amazon / Twitch / Github / Paypal / etc...)

My self-hosted runner is not working either. New jobs pick up by runner, all failed.
But re-running a job from previous one that was working, it ran just fine.

So now i'm not sure what is going on xD

**Comment by volcanioo** [comment]
same

**Comment by theobolo** [comment]
> It is working again, at least for some repos 🤔

For the moment my pipelines are still not able to checkout any private source code : 

![image](https://user-images.githubusercontent.com/7281773/100468417-aedf4580-30d4-11eb-9b09-fe430a627b08.png)

**Comment by nanaones** [comment]
https://www.githubstatus.com/

check this.

**Comment by delete-44** [comment]
Just a heads up for anybody finding this thread now, seems like service is coming back 😁

**Comment by socheatsok78** [comment]
> Just a heads up for anybody finding this thread now, seems like service is coming back 😁

Confirm

**Comment by zoispag** [comment]
> Just a heads up for anybody finding this thread now, seems like service is coming back 😁 

Indeed! 🙂

**Comment by p-bojkowski** [comment]
Is Down again :(

![image](https://user-images.githubusercontent.com/74313141/100550219-c8b98d80-3278-11eb-8369-07dcb1d8af65.png)

**Comment by rickstaa** [comment]
@zoispag Still not working for me. I think it is down again.

**Comment by rickstaa** [comment]
@zoispag Correction. It appears to work when I create a new GitHub action token (see #238).

**Comment by pjakubczyk** [comment]
I'm having same issue now with corporate repo.
Cloning doesn't work for most of the workflows.
Only PR checks are fine.
