### ISSUE TITLE
What determines if `--no-tags` or `--tags` is used in the git fetch of this action?

### ISSUE THREAD

**Issue by nelsonjchen** [actions/checkout#40]
I'm trying to introduce GitHub actions to a repository that uses `git describe --tags` as a step. For some reason, the fetches on a private repository of my organization does a fetch with `--no-tags`. 
 My experiments in an experimental repo with the tagging feature inside GitHub show it fetching with `--tags`. The logic of this action isn't contained in the source code of this repo so I'm not sure why it's doing this kind of fetch. If this is a difference in behavior between lightweight tags and annotated tags, this behavior should be documented.

**Comment by xt0rted** [comment]
@TingluoHuang I'm looking for a way to use `--no-tags` but only see a `v1` of this action, will a `v2` be released with this option?
