### ISSUE TITLE
package not checked out?

### ISSUE THREAD

**Issue by jGaboardi** [actions/checkout#410]
We are using `actions/checkout@v2` for many of the submodules in [PySAL](http://pysal.org) with varying success. For example, in [`spaghetti`](https://github.com/pysal/spaghetti) using [`actions/checkout@v2` in `unittests.yml`](https://github.com/pysal/spaghetti/blob/main/.github/workflows/unittests.yml) runs smoothly without issue. However, in [`tobler`](https://github.com/pysal/tobler) using [`actions/checkout@v2` in `unittests.yml`](https://github.com/pysal/tobler/pull/116/files) we are getting a [`ModuleNotFoundError: No module named 'tobler'`](https://github.com/pysal/tobler/pull/116/checks?check_run_id=1617713834#step:9:43). I am wondering if I can get any insight as to why this is happening in `tobler` but not `spaghetti`, or if there is something we are doing obviously wrong. I tried the [GitHub Community Forum's Actions Board](https://github.community/t5/GitHub-Actions/bd-p/actions) first, but got a "missing page" there.

**Comment by jGaboardi** [comment]
pysal/tobler#116

**Comment by knaaptime** [comment]
it needs the line `run: pip install -e . --no-deps --force-reinstall` otherwise the package doesnt get installed

**Comment by jGaboardi** [comment]
> it needs the line `run: pip install -e . --no-deps --force-reinstall` otherwise the package doesnt get installed

But doing this negates the purpose of using `actions/checkout@v2`. From the docs:
> This action checks-out your repository under $GITHUB_WORKSPACE, so your workflow can access it.

As far as I know, `tobler` is the only package where this is necessary so I think we may doing something wrong there. Do we know *why* simply using `actions/checkout@v2` doesn't install `tobler` as it should?

**Comment by knaaptime** [comment]
>But doing this negates the purpose of using actions/checkout@v2. From the docs:

>> This action checks-out your repository under $GITHUB_WORKSPACE, so your workflow can access it.

i dont follow... the purpose of the action is to *check out*, but checking out just means cloning the repo so that the source code is available, it doesnt actually install the package unless you explicitly ask it to (and the action can be used by lots of other repos that arent python packages, so it's definitely not *supposed* to install)

i have no idea why the other packages work without that step, but i think the action itself is working as intended

**Comment by jGaboardi** [comment]
@ericsciple I am wondering if it would be possible to get some clarification on the need for `run: pip install -e . --no-deps --force-reinstall` in some repos (e.g. [`pysal/tobler`](https://github.com/pysal/tobler/blob/master/.github/workflows/unittests.yml#L47)), while others are fine without it (e.g. [`pysal/spaghetti`](https://github.com/pysal/spaghetti/blob/main/.github/workflows/unittests.yml)). It seems that something is happening differently in these two cases (though I am quite possibly incorrect), but I can't pin down what exactly it is. It may not even be happening in `actions/checkout`, but I haven't been able to determine that for sure.
