### ISSUE TITLE
I got an error : Command failed: rm -rf <Path> rm: <Path>: Directory not empty

### ISSUE THREAD

**Issue by muukii** [actions/checkout#422]
I'm using a self-hosted runner.
And running `actions/checkout@v2`, it sometimes fails to clean the repository.

like this:
```
Command failed: rm -rf <Path> rm: <Path>: Directory not empty
```

I'm not sure about this happen exactly.
I'd like to get your advice to investigate this issue.

Thanks for the super convenient package!
And self-hosted runner is awesome!

**Comment by gagalago** [comment]
how did you solved that issue?
