### ISSUE TITLE
Fix `submodules` documentation

### ISSUE THREAD

**Issue by mattrubin** [actions/checkout#43]
I just spent the better part of an hour debugging a failing workflow, and it turned out the root cause was that the project's submodules had not been checked out recursively.

I had configured the checkout with:
``` yaml
    - uses: actions/checkout@v1
      with:
        submodules: true
```

I had inferred the `true` value for the `submodules` input from the action's documentation, which [described the input](https://github.com/actions/checkout/blob/94d077c24971944d312dd9197c1bdfba62b39878/action.yml#L14) as "Whether to recursively clone submodules; defaults to false". It turns out, setting the value to `true` checks out submodules, _but not recursively_. After searching through the closed issues, I discovered that for recursive checkout of submodules, [the value needs to be `recursive`](https://github.com/actions/checkout/issues/34).

It would be very helpful if the action documentation could be updated to correctly indicate what value needs to be passed to get the documented behavior.

**Comment by ethomson** [comment]
Thanks for the suggestion, I opened #48 to update the information in `actions.yml`.
