### ISSUE TITLE
Allow fetch-depth to fetch tags within that depth

### ISSUE THREAD

**Issue by Christewart** [actions/checkout#448]
I'm using github actions to push docker images to dockerhub and require tags to make sure my artifacts version is correct. 

I'm using `fetch-depth: 500` to avoid really long fetch times with my repo (yes, I know this is a problem on it's own). 

I would expected the default behavior of the action is to checkout tags _within_ that 500 depth limit, not use `--no-tags`

```
 /usr/bin/git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --depth=500 origin +cd1e2e1b5d307b7f4a2c6e49113da14cfc7b1c36:refs/remotes/origin/master
```

is the command that gets run

https://github.com/bitcoin-s/bitcoin-s/runs/1947728258#step:2:40

**Comment by freddyrios** [comment]
Got hit by this and I don't get why no-tags is used in the first place.

Local testing shows:

1. removing the no-tags only fetches the tags within the depth limit specified.
2. the default of 1 commit still only pulls 1 commit (in line with the above)

Can't see the downside, just some extra metadata being pulled?

**Comment by hairyhenderson** [comment]
I'm also seeing this behaviour with `fetch-depth: 0`, which contradicts what the docs say... Maybe something broke since https://github.com/actions/checkout/pull/258?

/cc @ericsciple

**Comment by RobertWieczoreck** [comment]
I forged a pull request that fixes this issue by introducing a `fetch-tags` option: https://github.com/actions/checkout/pull/579
Reviews and thumbs-ups are very welcome :)
