### ISSUE TITLE
Fetch latest commit

### ISSUE THREAD

**Issue by LukasWallrich** [actions/checkout#461]
Thanks for this helpful workflow. However, I am facing an issue that I can't work out - I would like to include two steps into the same workflow: *checkout -> document -> commit -> checkout -> test*

However, I can't get the second checkout to get the more recent commit rather than the commit that started the action. Any chance to get that to work? Given that it can sometimes be difficult to coordinate across GH Actions, this would seem to be a helpful functionality if not yet present ...

**Comment by ericsciple** [comment]
You might need to provide the [ref input](https://github.com/actions/checkout#usage), for example `ref: ${{ github.ref }}`. By default the SHA that triggered the event is checked out.

**Comment by bauergeorg** [comment]
I had the same problem... ```ref: ${{ github.ref }}``` works

**Comment by bauergeorg** [comment]
I think this hint should be added into the readme.
