### ISSUE TITLE
Always checking out main instead of the PR merge commit

### ISSUE THREAD

**Issue by samouri** [actions/checkout#486]
**summary**
👋   &nbsp; hi!

I work on the [amp-toolbox](https://github.com/ampproject/amp-toolbox) which utilizes `actions/checkout@v2` as part of its CI. I've noticed that the `ref` checked out in each CI invocation is always the SHA for `main` instead of the the SHA from the relevant PR ([example](https://github.com/ampproject/amp-toolbox/pull/1219/checks)).

Is this expected? 
Do we have it configured incorrectly (we have none of the optional configuration set)

**screenshot**

![Screen Shot 2021-04-27 at 4 45 37 PM](https://user-images.githubusercontent.com/4656974/116310576-2b577c80-a778-11eb-8220-3add265a312c.png)

**Comment by jonapap** [comment]
I seem to be having the same issue in one of my projects.

**Comment by jonapap** [comment]
I just had a similar issue. It seems that the trigger `pull_request_target` only checkout the base commit instead of the merge commit. Therefore, you might want to use `pull_request` instead. Look here for more info: https://docs.github.com/en/actions/reference/events-that-trigger-workflows

**Comment by samouri** [comment]
@jonapap that worked! thank you for the advice!
