### ISSUE TITLE
Run git fetch with `--quiet` by default

### ISSUE THREAD

**Issue by oowekyala** [actions/checkout#489]
The log output would be cleaner if the clone/fetch command used the [`--quiet`](https://git-scm.com/docs/git-fetch#Documentation/git-fetch.txt---quiet) option. This way, the download progress would not be output in logs:
```
 remote: Counting objects:   0% (1/459)        
 remote: Counting objects:   1% (5/459)        
 remote: Counting objects:   2% (10/459)        
 remote: Counting objects:   3% (14/459)        
 remote: Counting objects:   4% (19/459)        
 remote: Counting objects:   5% (23/459)        
 remote: Counting objects:   6% (28/459)        
```

Currently this prints one line per 1 or 2 % progress, for each of `remote: Counting objects`, `remote: Compressing objects`, `Receiving objects`, and `Resolving deltas`. This is as much as 400 lines of useless logs, maybe more for very big repos.

**Comment by oowekyala** [comment]
Found #18...

**Comment by swharden** [comment]
>  This is as much as 400 lines of useless logs, maybe more for very big repos

I find this jarring to the viewer (the text scrolls faster than it can be read). It is also a waste of bandwidth. It's not that much bandwidth individually, but at scale the waste must be impressive. 

Has a way been implemented/documented for disabling this noisy output?

**Comment by Allon-Guralnek** [comment]
@oowekyala I don't think this should be closed because #18 was closed as "resolved" due to them adding log grouping/collapsing to the UI. But the fact is, it doesn't solve the huge amount of logs this needlessly generates. So I think there should be some open issue about this so it's addressed.

**Comment by oowekyala** [comment]
@Allon-Guralnek I think you're right, but I think it would be more appropriate for the original ticket to be reopened

**Comment by simonbaird** [comment]
FYI there's a PR for this at #1067.
