### ISSUE TITLE
actions/checkout is checking out the wrong SHA

### ISSUE THREAD

**Issue by jwalton** [actions/checkout#49]
Note the SHA at the top of my build:

<img width="331" alt="image" src="https://user-images.githubusercontent.com/1771003/65891075-f56ece00-e371-11e9-9d39-ef2da2486fe4.png">

But this is the output from the end of `actions/checkout`:

```
 HEAD is now at c28ff3a5b fix: Use React 16.9.0.
Removed matchers: 'checkout-git'
##[remove-matcher owner=checkout-git]
```

It seems to be checking out the latest master, instead of the branch I'm actually on.  This was working on Saturday.

**Comment by jwalton** [comment]
Actually, I think perhaps something more fundamental is broken here:

```
      - run: 'echo Sha is: $SHA'
        env:
          SHA: ${{ github.sha }}
```

results in:

```
Sha is:
```

Where's my sha?  O_o

**Comment by jwalton** [comment]
The default `$GITHUB_SHA` is also empty.

**Comment by nulano** [comment]
Even the ref is missing! Running `cmd /c "set"` on Windows gives:

```
[...]
GITHUB_BASE_REF=
GITHUB_EVENT_NAME=push
GITHUB_EVENT_PATH=d:\a\_temp\_github_workflow\event.json
GITHUB_HEAD_REF=
GITHUB_REF=
GITHUB_REPOSITORY=nulano/Pillow
GITHUB_SHA=
[...]
```

This broke about an hour ago.

**Comment by nulano** [comment]
Reported here as well: https://github.community/t5/GitHub-Actions/GITHUB-REF-and-GITHUB-SHA-no-longer-work/m-p/33283/highlight/true#M1439

**Comment by jwalton** [comment]
@nulano I beat you to it by a minute, I'm afraid: https://github.community/t5/GitHub-Actions/PSA-GitHub-Actions-are-a-bit-broken-this-morning-missing-SHAs/m-p/33282#M1438  ;)

**Comment by TingluoHuang** [comment]
ACK

**Comment by timruffles** [comment]
We have deployed a fix for this. Sorry! 😓 @jwalton how is it looking for you?

**Comment by nulano** [comment]
Looks OK for me now.

**Comment by jwalton** [comment]
@timruffles Working for me now!  Don't worry, you're still beta, you can break stuff.  ;)  Thanks for the quick fix!

**Comment by rela589n** [comment]
It seems that currently it doesn't work.

```
- name: Build docker images
        run: |
          $tag = '${{ env.GITHUB_SHA }}' | cut --characters=1-15
```

Results in:

```
 $tag = '' | cut --characters=1-15
```
