### ISSUE TITLE
actions/checkout@v1 does not check out branch that originated event

### ISSUE THREAD

**Issue by coderbyheart** [actions/checkout#50]
Maybe related to #49.

The originating branch is `saga`, however `actions/checkout@v1` tries to check out `master` and fails here because this repo has no `master` branch:

```
error: pathspec 'refs/remotes/origin/master' did not match any file(s) known to git
```

https://github.com/NordicSemiconductor/modemtalk/commit/e9006f32481bd2bc97a35403fcb6342b8f964874/checks#step:2:586

**Comment by TingluoHuang** [comment]
ACK, dup with #49
