### ISSUE TITLE
[2.3.4] Private (ssh) submodule not found

### ISSUE THREAD

**Issue by MatthijsBurgh** [actions/checkout#501]
Since today my repo started to use `2.3.4` of the checkout action. Now it gives me errors on cloning a private ssh submodule. To be sure, I tested it with fixed `2.3.3`, which still works.

The log of `2.3.3`: https://github.com/tue-robotics/tue-env-targets/runs/2564039606?check_suite_focus=true#step:2:39
The log of `2.3.4`: https://github.com/tue-robotics/tue-env-targets/runs/2563014343?check_suite_focus=true#step:2:38

`2.3.3` is temporarily overriding the `GIT_SSH_COMMAND`. This doesn't show in `2.3.4`, I think this is the cause of the cloning of the submodule fails later on.

**Comment by MatthijsBurgh** [comment]
I see that the specific action run didn't use the `ssh-key` option. Probably an issue with GH actions itself instead of the checkout actions.

**Comment by TamaMcGlinn** [comment]
It appears this still doesn't work for private submodules. Using 2.3.3 doesn't help either.
