### ISSUE TITLE
The requested URL returned error: 500

### ISSUE THREAD

**Issue by tekumara** [actions/checkout#505]
```
Fetching the repository
  /usr/bin/git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --depth=2 origin +7a912623c6832c7590fd43672aa822a8302b2c29:refs/remotes/origin/volume-size-default
  remote: Internal Server Error.
  remote: 
  Error: fatal: unable to access 'https://github.com/seek-oss/aec/': The requested URL returned error: 500
  The process '/usr/bin/git' failed with exit code 128
  Waiting 12 seconds before trying again
 ```
 
See run [Python application #617](https://github.com/seek-oss/aec/runs/2593881333?check_suite_focus=true#step:2:39)

This used to work.

**Comment by tekumara** [comment]
I've tried re-running the job multiple times and it still fails.

**Comment by Covernel** [comment]
I have the similar issue started 7 hours ago.
There is no change on my server, workflow files or repos. All workflow on self-hosted / github-hosted server throw error on actions/checkout.
Does anyone have a solution to this problem? or is it just temporary failure on github-side?

**Comment by juannorris** [comment]
There seems to be an outage in [GH actions and pages](https://www.githubstatus.com/incidents/zbpwygxwb3gw):

<img width="527" alt="Screen Shot 2021-05-16 at 10 45 46" src="https://user-images.githubusercontent.com/1682951/118399507-e1094300-b633-11eb-996e-465a8273b9a6.png">

**Comment by iranzo** [comment]
Incident now appears as repaired but the problem still persists.

**Comment by tekumara** [comment]
Now resolved for me.
