### ISSUE TITLE
Need clarify: use in release workflow

### ISSUE THREAD

**Issue by scegg** [actions/checkout#507]
Hi.

Please clarify on the doc:
When use this action in ```release``` workflow, does it checkout the code related to the same tag of the release?
Or, how to checkout the code of the release?

Thanks.

**Comment by martpet** [comment]
Hi, I also want to know if it checks out the code related to the tag of the release. Did you find an answer?

**Comment by martpet** [comment]
> nope, sadly.

I hope you are wrong, the Readme says:

> When checking out the repository that triggered a workflow, this defaults to the reference or SHA for that event.

From GitHub docs for the `release` event:

`GITHUB_REF` - Tag ref of release refs/tags/<tag_name>
`GITHUB_SHA` - Last commit in the tagged release
