### ISSUE TITLE
Submodule option not working

### ISSUE THREAD

**Issue by giordi91** [actions/checkout#51]
Good afternoon, I am using the checkout with sumbodule cloning like this:

```
- uses: actions/checkout@v1
      with:
        submodules: true
```
It does not seem to be recrusive, I have submodule that has submodules of its own. 
If I run git submodule update --init --recursive then I get everything I need, with just the submodule:true flag that does not seem to be the case. 

Am I doing something wrong?
My submodule is this one:
https://github.com/GPUOpen-Tools/Compressonator

**Comment by nulano** [comment]
#48 suggests using `submodules: recursive` for this.

**Comment by giordi91** [comment]
Ah thank you!I only checked for the open issues not for the closed one. Thank you!
I am just a bit confused from the merged PR seems it should have made it to master but can't see it in the action.yml file?

**Comment by nulano** [comment]
Those PRs are still open.
