### ISSUE TITLE
Confused with checkout@master when base branch is not master

### ISSUE THREAD

**Issue by Shekharrajak** [actions/checkout#52]
We are creating an action called `deploy` and current branch is `newsite` so as per [this](https://github.com/actions/checkout#usage) documentation we want to use `newsite` branch but if I don't specify the branch then also it works.

Refer: https://github.com/numpy/numpy.org/pull/46#discussion_r331747032

**Comment by thboop** [comment]
Hey @Shekharrajak ,

When you invoke an action using `uses: actions/checkout@master`
You are saying, I would like to run the checkout action's master branch code. The comment chain here is correct:
https://github.com/numpy/numpy.org/pull/46#discussion_r331748901

We are working an on update to allow you to more easily run other git commands inside git, such as fetching a different remote branch. You can see the status of that work here: https://github.com/actions/checkout/pull/56

I'm going to close this issue, but feel free to reopen it if you have any more questions!
