### ISSUE TITLE
Show the checked out commit

### ISSUE THREAD

**Issue by fulldecent** [actions/checkout#53]
Please print out the commit hash for the commit which is successfully checked out by this action.

**Comment by ericsciple** [comment]
@fulldecent i think this makes a lot of sense. refs can slide, showing what was actually checked out is good to have in the log.

i'll add `git log -1` after checkout. sound good?

**Comment by fulldecent** [comment]
Sounds great, thank you.

**Comment by ericsciple** [comment]
fixed in master (`v2-beta`)
