### ISSUE TITLE
Fails to clone private repo when running from Actions (in same repo)

### ISSUE THREAD

**Issue by BanTheRewind** [actions/checkout#546]
I used the Azure Kubernetes Service (AKS) Deployment Center to create my deployment pipeline from Github. Everything worked until earlier today when this message started appearing:

```
/usr/bin/git remote add origin https://github.com/myaccount/myprivaterepo
/usr/bin/git config --local gc.auto 0
/usr/bin/git config --local --name-only --get-regexp http\.https\:\/\/github\.com\/\.extraheader
/usr/bin/git config --local http.https://github.com/.extraheader AUTHORIZATION: basic ***
/usr/bin/git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin +a68375c71a1bc2e93d149534598be84261d0c9ca:refs/remotes/origin/prod
remote: Repository not found.
Error: fatal: repository 'https://github.com/myaccount/myprivaterepo/' not found
```

The script generated by Azure has `- uses actions/checkout@master`, which I thought may be deprecated. I tried a few versions to no avail.

**Comment by mikeldking** [comment]
Very similar error on our private repo as well.
```terminal
  /usr/bin/git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin +hashgoeshere:refs/remotes/origin/main
  remote: Repository not found.
  Error: fatal: repository 'https://github.com/myorg/myrepo/' not found
  Error: The process '/usr/bin/git' failed with exit code 128
```

**Comment by mikeldking** [comment]
> Very similar error on our private repo as well.
> 
> ```
>   /usr/bin/git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin +hashgoeshere:refs/remotes/origin/main
>   remote: Repository not found.
>   Error: fatal: repository 'https://github.com/myorg/myrepo/' not found
>   Error: The process '/usr/bin/git' failed with exit code 128
> ```

Actions functionality restored on my end

**Comment by BanTheRewind** [comment]
Same here. Will close.

**Comment by TamaMcGlinn** [comment]
I'm getting exactly this error today, but for private submodules, using:

```
      - uses: actions/checkout@v2
        with:
            submodules: recursive
```

**Comment by MisterTimn** [comment]
We are running into this error as well now... Private repository. Both v2 and v3 erroring.
