### ISSUE TITLE
error: pathspec 'feature/github-actions' did not match any file(s) known to git

### ISSUE THREAD

**Issue by panw3i** [actions/checkout#55]
* [new branch]      master     -> origin/master
git checkout --progress --force feature/github-actions
error: pathspec 'feature/github-actions' did not match any file(s) known to git
Removed matchers: 'checkout-git'
##[remove-matcher owner=checkout-git]
##[error]Git checkout failed with exit code: 1
##[error]Exit code 1 returned from process: file name 'c:\runners\2.159.0\bin\Runner.PluginHost.exe', arguments 'action "GitHub.Runner.Plugins.Repository.v1_0.CheckoutTask, Runner.Plugins"'.

**Comment by ericsciple** [comment]
@panw3i does the branch exist?

**Comment by ericsciple** [comment]
havent heard of other folks running into this issue. assuming the branch doesnt exist?
