### ISSUE TITLE
I'm using stock OP 0.8.8. When I hit the LKAS button after OP is engaged using the set button, I get the lkas solid lines on the dash. After a few moments, I get "steering required" on the dashboard, if I don't grab the steering wheel within a few seconds, those solid lines become broken lines. The steering required message stays on until I grab the wheel. My C2 can see my face during this whole ordeal. My understanding is that the LKAS button is not suppose to do anything when OP is engaged.

### ISSUE THREAD

**Issue by jmayes41** [actions/checkout#572]
I'm using stock OP 0.8.8. When I hit the LKAS button after OP is engaged using the set button, I get the lkas solid lines on the dash. After a few moments, I get "steering required" on the dashboard, if I don't grab the steering wheel within a few seconds, those solid lines become broken lines. The steering required message stays on until I grab the wheel. My C2 can see my face during this whole ordeal. My understanding is that the LKAS button is not suppose to do anything when OP is engaged. 

__Originally posted by @bobbygg in https://github.com/commaai/openpilot/issues/22073__![image](https://user-images.githubusercontent.com/48909228/132360243-8f782837-8900-4220-b1d3-ab83c132253a.jpeg)

**Comment by chrisjohnson00** [comment]
This issue is sus.
