### ISSUE TITLE
Documenting all possible inputs in the README

### ISSUE THREAD

**Issue by francisfuzz** [actions/checkout#59]
:wave: Actions team,

I think it's great that we publish the description for each of the inputs for this action in the `action.yml` file: https://github.com/actions/checkout/blob/master/action.yml

One opportunity I see here is to publish them in the README. This would be very helpful for any user leveraging this Action and make them aware that such inputs exist, especially those who leverage accompanying features (submodules, LFS, and so forth).

Would the team be open to contributions for updating the README file to include these inputs? In this way, consumers don't need to worry about "digging in the code" and can just get all the information they need up front in the documentation.

Thanks for hearing me out! 🙇

**Comment by ericsciple** [comment]
thanks @francisfuzz. i'm going to make some changes to the readme shortly... getting close to releasing a v2 version of checkout (behavioral changes). i'll take a stab at this as part of those changes

**Comment by francisfuzz** [comment]
Sweet, thanks for that @ericsciple 😎

**Comment by ericsciple** [comment]
i'm planning to fix this in V2. I wrote a script to update the docs during the build process (so the two dont get out of sync)

**Comment by francisfuzz** [comment]
> i'm planning to fix this in V2. I wrote a script to update the docs during the build process (so the two dont get out of sync)

Thanks Eric!

(Where v2 is currently being worked on: https://github.com/actions/checkout/pull/70)

**Comment by ericsciple** [comment]
fixed in master
