### ISSUE TITLE
Docs Tweak: Edit `GitHub_PAT` to something GitHub accepts

### ISSUE THREAD

**Issue by gauntface** [actions/checkout#627]
The README has an example using `GitHub_PAT` as the name for the token. 

GitHub doesn't let you set a secret with the prefix `GITHUB` and throws an error. Would be helpful to recommend an alternative variable name so folks don't hit this speedbump.

**Comment by ericsciple** [comment]
Fixed with https://github.com/actions/checkout/pull/623
