### ISSUE TITLE
Can I pull repositories other than the current repository?

### ISSUE THREAD

**Issue by bbhxwl** [actions/checkout#634]
Can I pull repositories other than the current repository?

**Comment by kenorb** [comment]
Specify `repository`, e.g. `actions/checkout`.

**Comment by sam-m-m** [comment]
Yes. You'll need to create a Personal Access Token for a private repo. Example here --https://github.com/actions/checkout/issues/24

**Comment by kenorb** [comment]
> Yes. You'll need to create a Personal Access Token for a private repo. Example here --> #24

I mean to pull from the local dir, not the private repo.

E.g. I've repo at `./some/path`, and I'm trying to do:

```
- uses: actions/checkout@v2
  with:
    repository: ./some/path
```

Normally you can pull with local paths, e.g.: `git init && git pull ./some/path`.
