### ISSUE TITLE
Failed to Download

### ISSUE THREAD

**Issue by donzee529** [actions/checkout#672]
Warning: Failed to download action 'https://api.github.com/repos/actions/checkout/tarball/ec3a7ce113134d7a93b817d10a8272cb61118579'. Error: Response status code does not indicate success: 503 (Service Unavailable).

**Comment by shenweiyan** [comment]
I got the same error:
```
Download action repository 'actions/checkout@v2' (SHA:ec3a7ce113134d7a93b817d10a8272cb61118579)
Warning: Failed to download action 'https://api.github.com/repos/actions/checkout/tarball/ec3a7ce113134d7a93b817d10a8272cb61118579'. Error: Response status code does not indicate success: 503 (Service Unavailable).
```

**Comment by softprops** [comment]
Same

**Comment by MacTanomsup** [comment]
Same here

```Warning: Failed to download action 'https://api.github.com/repos/actions/checkout/tarball/ec3a7ce113134d7a93b817d10a8272cb61118579'. Error: Response status code does not indicate success: 503 (Service Unavailable).
Warning: Back off 29.799 seconds before retry.
Warning: Failed to download action 'https://api.github.com/repos/actions/checkout/tarball/ec3a7ce113134d7a93b817d10a8272cb61118579'. Error: Response status code does not indicate success: 503 (Service Unavailable).
Warning: Back off 10.67 seconds before retry.
Error: Response status code does not indicate success: 503 (Service Unavailable).```

**Comment by keijeon** [comment]
Plz......

**Comment by bitbw** [comment]
Same

**Comment by northes** [comment]
Same

**Comment by kozross** [comment]
Same.

**Comment by jhpung** [comment]
Same

**Comment by yardasol** [comment]
Same

**Comment by xueyongg** [comment]
Same

**Comment by danieladarve** [comment]
Same

**Comment by SamGhAu** [comment]
Same

**Comment by bokyung-kang** [comment]
Same (TT)

**Comment by komahori** [comment]
same

**Comment by seungwoohong** [comment]
Same

**Comment by denielaa** [comment]
same here

**Comment by kozross** [comment]
[Senpai noticed us](https://www.githubstatus.com/incidents/cypv026dr23w).

**Comment by dvengers** [comment]
https://www.githubstatus.com/

Update - GitHub Actions is experiencing degraded performance. We are continuing to investigate.
Jan 12, 02:28 UTC

**Comment by glatiuden** [comment]
same

**Comment by zi-gae** [comment]
same

**Comment by jeremyjone** [comment]
same

**Comment by cksal0805** [comment]
same

**Comment by r3cha** [comment]
Lock latest worked version 
```
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.5
```

**Comment by donzee529** [comment]
> [Senpai noticed us](https://www.githubstatus.com/incidents/cypv026dr23w).

Whos Senpai

**Comment by dominicarrojado** [comment]
Having similar issue:
```
Error: Can't use 'tar -xzf' extract archive file: /home/runner/work/_actions/_temp_be30aa3d-8cff-4889-89cf-6c08c43fc8c1/3583c51f-8c7a-46d3-9f46-147edce097c4.tar.gz. return code: 2.
```

**Comment by giapnhdev** [comment]
Same here!

**Comment by donzee529** [comment]
> Having similar issue:
> 
> ```
> Error: Can't use 'tar -xzf' extract archive file: /home/runner/work/_actions/_temp_be30aa3d-8cff-4889-89cf-6c08c43fc8c1/3583c51f-8c7a-46d3-9f46-147edce097c4.tar.gz. return code: 2.
> ```

Yeah thats the error I get now

**Comment by r3cha** [comment]
@donzee529 thanks I got successfully run checkout at 2.3.5 but its may be just a coincidence that everything start works for me

**Comment by kozross** [comment]
> > [Senpai noticed us](https://www.githubstatus.com/incidents/cypv026dr23w).
> 
> Whos Senpai

It's a joking reference to Github, by way of [this meme](https://knowyourmeme.com/memes/i-hope-senpai-will-notice-me).

**Comment by caiotavaresdito** [comment]
Working only with v2.3.5

**Comment by jeremyjone** [comment]
> Lock latest worked version
> 
> ```
>     steps:
>       - name: Checkout
>         uses: actions/checkout@v2.3.5
> ```

Oh Yeah, v2.3.5 looks work.

**Comment by giapnhdev** [comment]
Yes, v2.3.5 works like a charm :)))

**Comment by donzee529** [comment]
Yes 2.3.5 works for me as well

**Comment by kozross** [comment]
Can confirm 2.3.5 also worked for me.

**Comment by northes** [comment]
thanks, 2.3.5 worded

**Comment by mpyw** [comment]
Seems to be fixed

**Comment by donzee529** [comment]
I won't close this since we'll post when its officially fixed.

**Comment by cksal0805** [comment]
Seems to be fixed !

**Comment by donzee529** [comment]
Lets keep this a bit more organized, we dont need everyone commenting. React if its fixed for you or still broken. 👎 👍 still broken or fixed respectively.

**Comment by Weibw162** [comment]
Error: Can't use 'tar -xzf' extract archive file: /home/runner/work/_actions/_temp_8428ad1b-2d43-440d-836e-4f3938611a97/de7619b5-211e-4e93-bf8b-2bb3ab71ace2.tar.gz

**Comment by donzee529** [comment]
GitHub marked the issues as solved and there was a Workaround this issue that was Merged in a PR, so I will now go ahead and close this.

**Comment by softprops** [comment]
This seems fixed for me now w/o a work around

**Comment by ozgurnevres** [comment]
I'm getting the same error right now.
![err](https://user-images.githubusercontent.com/13433906/171574266-897561b9-9e90-48aa-91e1-04072f6c7432.jpg)

**Comment by Thor-wl** [comment]
It seems that v2.3.5 don't work for me. Have someone met this problem recently again?

**Comment by devriez** [comment]
i met.  v2.3.5 worked for me only for one commit, after that breake again

**Comment by Thor-wl** [comment]
> i met. v2.3.5 worked for me only for one commit, after that breake again

Excuse me, have you resolved it now?

**Comment by michalgozdowski** [comment]
> 

Have you really tried version v2.3.5? In your PR I can see change from v2 to v3:
`      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          path: ./src/github.com/${{ github.repository }}`

**Comment by devriez** [comment]
no. met it half an hour ago

> > i met. v2.3.5 worked for me only for one commit, after that breake again
> 
> Excuse me, have you resolved it now?

**Comment by Thor-wl** [comment]
> > 
> 
> Have you really tried version v2.3.5? In your PR I can see change from v2 to v3: ` - name: Checkout code uses: actions/checkout@v3 with: fetch-depth: 0 path: ./src/github.com/${{ github.repository }}`

Yes, I tried but failed. So I'm trying to convert it to v3 and have a try. Unfortunly, it fails again.

**Comment by Thor-wl** [comment]
> no. met it half an hour ago
> 
> > > i met. v2.3.5 worked for me only for one commit, after that breake again
> > 
> > 
> > Excuse me, have you resolved it now?

Yes, it is broken about half an hour ago for me, too. It worked well yesterday.

**Comment by jonyjalfon94** [comment]
> It appears it started to work now...

It started working again for me as well

**Comment by Thor-wl** [comment]
Yes, it works well for me now, too.

**Comment by radiomix** [comment]
I got this issue today! ;-// `Error: Can't use 'tar -xzf' extract archive file: /home/runner/work/****`
Solution: Re-run the job manually! THAT IS GREAT! (or maybe not?)

**Comment by singhkrshivam** [comment]
I got the same issue as well. `Can't use 'tar -xzf' extract archive file: /home/user/actions-runner/_work/_actions/**.tar.gz. return code: 2`

I tried re-running the job but no luck yet. Can someone please suggest what is wrong?

**Comment by singhkrshivam** [comment]
> > I got the same issue as well. `Can't use 'tar -xzf' extract archive file: /home/user/actions-runner/_work/_actions/**.tar.gz. return code: 2`
> > I tried re-running the job but no luck yet. Can someone please suggest how to fix this issue?
> 
> Try to re-run multiple times, it will work eventually..

Thanks for the quick response @glichtner. Is there any permanent solution we can use? It's impacting our production CI as well.

**Comment by HydraShield** [comment]
Download action repository 'actions/checkout@v3' (SHA:f43a0e5ff2bd294095638e18286ca9a3d1956744)
Warning: Failed to download action 'https://api.github.com/repos/actions/checkout/tarball/f43a0e5ff2bd294095638e18286ca9a3d1956744'. Error: Response status code does not indicate success: 503 (Service Unavailable).
Warning: Back off 19.414 seconds before retry.
Warning: Failed to download action 'https://api.github.com/repos/actions/checkout/tarball/f43a0e5ff2bd294095638e18286ca9a3d1956744'. Error: Response status code does not indicate success: 503 (Service Unavailable).
Warning: Back off 18.061 seconds before retry.
Error: Response status code does not indicate success: 503 (Service Unavailable).

same here

**Comment by theapache64** [comment]
Facing now!!

**Comment by HydraShield** [comment]
yes
try with v3 and v2.3.5

**Comment by onimushapooh** [comment]
same

**Comment by luisoala** [comment]
+1

**Comment by leland-86** [comment]
same for me as well. 

Didn't occur an hour ago for me but happening now

**Comment by bnx-SatoshiAkiyama** [comment]
same

**Comment by robertraf** [comment]
same

**Comment by aditya1OG** [comment]
how can i fix this

**Comment by hwc9169** [comment]
same here

**Comment by AndSonder** [comment]
same here QAQ

**Comment by taziksh** [comment]
same

**Comment by reubencww** [comment]
Is it down again?

**Comment by shilongjaycui** [comment]
same

**Comment by BRUHItsABunny** [comment]
yup, here again

**Comment by zhgchgli0718** [comment]
> Is it down again?
> 
> 

same..

**Comment by kooyunmo** [comment]
same 🤯

**Comment by brobro10000** [comment]
same

**Comment by radzivil** [comment]
+1

**Comment by markschad** [comment]
+1

**Comment by johnreyev** [comment]
+1

**Comment by Risk-taker0501** [comment]
same

**Comment by gayuru** [comment]
same sis

**Comment by fentresspaul61B** [comment]
Getting same error.

**Comment by 72kb** [comment]
same too, it cant be a coincidence right?

**Comment by DaviReisVieira** [comment]
same here

**Comment by mfaizan-wx** [comment]
+1

**Comment by dj-luis198** [comment]
+1

**Comment by ashikur-rahman-shad** [comment]
Same here T-T

**Comment by rohanvachheta** [comment]
+1

**Comment by zealgt** [comment]
+100

**Comment by justzino** [comment]
+1

**Comment by 7oxP** [comment]
same, I've tried different versions but still got an error

**Comment by ellamurii** [comment]
+1

**Comment by seungbohong94** [comment]
Is it temporal issue in  github action now?

**Comment by shivambhatia5432** [comment]
+1

**Comment by DaviReisVieira** [comment]
Hey, @everyone! It's an API error on GitHub, not in this Repo. Let's wait for service return.

<img width="794" alt="image" src="https://github.com/actions/checkout/assets/36394034/c1252202-0a23-4f05-a24c-6f359b1c7a68">

**Comment by luisoala** [comment]
works again

**Comment by ahmedmajidgit** [comment]
As @glichtner mentioned, I tried re-run it multiple times and it works, after doing it times, i switch to re-run failed jobs

**Comment by juliet-gobran** [comment]
Same

**Comment by meaghanfitzgerald** [comment]
not working for me

**Comment by akeematthread** [comment]
+1

**Comment by ji-seung-ryu** [comment]
Same

**Comment by BlackRoach** [comment]
pls fix it

**Comment by DaviReisVieira** [comment]
@everyone Let's wait, people :/

https://www.githubstatus.com/

<img width="607" alt="image" src="https://github.com/actions/checkout/assets/36394034/677f8a2a-6f81-4a03-b4f6-745618f5eeba">

**Comment by BiosPlus** [comment]
No. 

༼ つ ◕_◕ ༽つ Give worker

**Comment by DaviReisVieira** [comment]
Done, people!

<img width="615" alt="image" src="https://github.com/actions/checkout/assets/36394034/c2720492-6d96-4ec0-a24c-c6df479f57fc">

**Comment by BiosPlus** [comment]
\ ༼ ◕_◕ ༽ / Worker working!

**Comment by HydraShield** [comment]
v3.1 is working for me :)

**Comment by laurensk** [comment]
Still not working for me. Waiting a bit...

**Comment by arleme-idweb** [comment]
It's working now :)

**Comment by yuurrii** [comment]
it's working now 🙊

**Comment by slavik-pastushenko** [comment]
v3 is not working :(

**Comment by slavik-pastushenko** [comment]
v4 as well.

**Comment by slavik-pastushenko** [comment]
Helped me: https://github.com/orgs/community/discussions/66444#discussioncomment-6944823

**Comment by cb-krishnapatel** [comment]
Any one facing the same issue again? We are seeing 429s on all github workflow runs.
