### ISSUE TITLE
Can't use 'tar -xzf' extract archive file

### ISSUE THREAD

**Issue by PtPrashantTripathi** [actions/checkout#673]
Hi I am using checkout in my repo action,
So today morning my pipeline have me an error  
​https://github.com/vedicscriptures/twitter_bot/runs/4784317504

![Screenshot_2022-01-12-09-30-05-092_com android chrome](https://user-images.githubusercontent.com/26687933/149061951-ce0fa86a-ea51-48d0-b3e5-4881ff43a3b6.jpg)

**Comment by hidetatz** [comment]
I guess this is already fixed in https://github.com/actions/checkout/issues/672#issuecomment-1010606946 ?

**Comment by PtPrashantTripathi** [comment]
> I guess this is already fixed in [#672 (comment)](https://github.com/actions/checkout/issues/672#issuecomment-1010606946) ?

Yes it got fixed

**Comment by jmatusevich** [comment]
This is happening to me right now

**Comment by raulfdm** [comment]
Same for me. No idea why but it suddenly started

**Comment by PtPrashantTripathi** [comment]
@raulfdm @jmatusevich for me it's working fine.

**Comment by kaspar-p** [comment]
Happening for me right now

**Comment by jszklarz** [comment]
This started happening to me just now.

**Comment by circles-png** [comment]
Same.

**Comment by jmahenriques** [comment]
Same BUT it multiplies every time I re-run. 🤷🏻‍♂️

**Comment by vikvrn** [comment]
Same - but works after **a number of times** re-run. :)

**Comment by pawelradzinski** [comment]
Isn't it [this fresh incident](https://www.githubstatus.com/incidents/gq1x0j8bv67v)?

**Comment by jmahenriques** [comment]
Yes, it has been [resolved](https://www.githubstatus.com/incidents/gq1x0j8bv67v).

**Comment by muratdogan17** [comment]
It's happening to me now :/

**Comment by bartblokhuis** [comment]
It's happening too me as well :(

**Comment by martinkocjan-medaica** [comment]
Same here, It started 10 minutes ago for me as well.

**Comment by michailbgk** [comment]
Same here, just started now

**Comment by jiqicn** [comment]
Same here, just happend right now

**Comment by PixelWeaver** [comment]
Same here 🙃

**Comment by vaidik** [comment]
Same her

**Comment by gabrielmocanu** [comment]
Same here

**Comment by Asken** [comment]
Same here

**Comment by mandrei12** [comment]
Same here

**Comment by aduartjs** [comment]
same here!

**Comment by xerdink** [comment]
seems like it's happening again.

**Comment by TomaszKlosinski** [comment]
same here.

**Comment by holcz** [comment]
It's happening for us as well, it's flaky, not failing consistently.

**Comment by matslexell** [comment]
Happening to me as well. Flaky as well, when I restart some jobs keep failing while some jobs succeed.

**Comment by usmarvia** [comment]
same here

**Comment by niall-shaw** [comment]
+1

**Comment by DOZBORNE** [comment]
Same here! Tests are randomly exiting and failing install.

**Comment by MartinSMadsen** [comment]
I think it works now, guys :smile:

**Comment by douglascayers** [comment]
For what it's worth, this is happening to me now 😢 

Is the issue related to this action or upstream with GitHub API?

**Comment by douglascayers** [comment]
Ah, I think it's a GitHub Actions Runner issue and not this action as evidenced by past intermittent issues https://github.com/actions/checkout/issues/1448#issuecomment-1705292580

https://www.githubstatus.com/incidents/tqrmcdmghldw

**Comment by junjie-landing** [comment]
same here...

**Comment by jun0tpyrc** [comment]
seem not very stable for the moment , rerun sometimes work

**Comment by giacomochiarella** [comment]
Happening here also right now
