### ISSUE TITLE
Readme recommends @v2 not latest version

### ISSUE THREAD

**Issue by ben-spiller** [actions/checkout#682]
All the examples in the readme in this repo (which people will doubtless copy) suggest using the v2 tag. 

But the latest release (at time of writing) is v2.4.0 - so most people who follow these instructions will be hardcoding a very out of date version of the action into their workflows, with bugs and lack of modern functionality. 

The examples should specify the latest version

**Comment by wwsean08** [comment]
v2 is a rolling tag, see https://github.com/actions/checkout/tags, v2 and v2.4.0 both point to the same commit, [ec3a7ce](https://github.com/actions/checkout/commit/ec3a7ce113134d7a93b817d10a8272cb61118579)

**Comment by ben-spiller** [comment]
Aha thanks I had misunderstood that aspect! Much appreciated
