### ISSUE TITLE
Check out submodule branch.

### ISSUE THREAD

**Issue by npes-95** [actions/checkout#69]
Hi, 

I would like to checkout a specific branch in a submodule (specified in `.gitmodules`) when I run this action - so far I have been unsuccessful. On my local machine I would run `git submodule update --remote` to retrieve this branch, is an equivalent operation possible?

Nick

**Comment by Warchant** [comment]
Assume `src/submodule` is your path to submodule.
```
cd src/submodule
git checkout $MYBRANCH
cd ../..
# git add / commit / push
```
