### ISSUE TITLE
Error in Windows: File not found 'git'

### ISSUE THREAD

**Issue by datapythonista** [actions/checkout#71]
I don't see anywhere in the README that this action is for Linux/Mac only, so I guess it should work with Windows. But when I run it, I get this error:
```
> Run actions/checkout@v1
Added matchers: 'checkout-git'. Problem matchers scan action output for known warning or error strings and report these inline.
Syncing repository: pandas-dev/pandas
Removed matchers: 'checkout-git'
##[error]File not found: 'git'
##[error]Exit code 1 returned from process: file name 'c:\runners\2.160.2\bin\Runner.PluginHost.exe', arguments 'action "GitHub.Runner.Plugins.Repository.v1_0.CheckoutTask, Runner.Plugins"'.
```

Is this expected to work? Anything missing in the README that I should know?

Thanks!

**Comment by ericsciple** [comment]
Git must be in the PATH

**Comment by ericsciple** [comment]
Are you using a self hosted runner? I would expect git to be in the PATH on the hosted runners

**Comment by ericsciple** [comment]
We should make the error more actionable.

Something like:
```
Unable to find executable file 'git'. Please make sure the file is discoverable from the PATH environment variable and the executable attribute is set.
```

the bit about executable attribute only on linux, we can have a separate message on windows

Thoughts?

**Comment by datapythonista** [comment]
Just realized that I'm changing the path before the checkout with:
```
run: echo "::set-env name=PATH::${HOME}/miniconda3/bin:${PATH}"
```
This seems to work as expected in Linux/Mac, updating the path, but seems like in Windows the original path is lost.

Feel free to close, I guess something is wrong with the `echo`, but I think this is unrelated to the checkout action.

**Comment by myoung34** [comment]
I'm having this in ARM:
https://hub.docker.com/repository/docker/myoung34/github-runner-arm

Using that to build ( https://github.com/myoung34/LEDSpicer/runs/320592116 ):
```
  Set up job2s
  Build skx/github-action-publish-binaries@master16m 9s
  Run actions/checkout@v16s
##[error]Exit code 1 returned from process: file name '/actions-runner/bin/Runner.PluginHost', arguments 'action "GitHub.Runner.Plugins.Repository.v1_0.CheckoutTask, Runner.Plugins"'.
Run actions/checkout@v1
Added matchers: 'checkout-git'. Problem matchers scan action output for known warning or error strings and report these inline.
Syncing repository: myoung34/LEDSpicer
Removed matchers: 'checkout-git'
##[error]File not found: 'git'
##[error]Exit code 1 returned from process: file name '/actions-runner/bin/Runner.PluginHost', arguments 'action "GitHub.Runner.Plugins.Repository.v1_0.CheckoutTask, Runner.Plugins"'.
  install build-es
```

**Comment by ericsciple** [comment]
@datapythonista consider the [add-path](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/development-tools-for-github-actions#add-a-system-path-add-path) command instead

windows uses `;` separator - using `add-path` you can avoid that problem

**Comment by datapythonista** [comment]
Wasn't aware of it, this is very useful to know, thanks a lot for the information.

I think this fully resolves the mystery of what was the problem with this issue. Closing.

**Comment by jcs090218** [comment]
@datapythonista  I have the same issue! How did you add path on Windows? 😕

**Comment by datapythonista** [comment]
iirc `git` is in the path by default, so you don't need to do anything. If `git` is not found, it's probably because you're replacing the default path with something else. If you need to add something to the path, use [this command](https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#example-2), and `git` should still be found, as well as whatever it is in the path you are adding. At least that was my problem, I guess yours should be the same.
