### ISSUE TITLE
Add suport for checking out with SSH key 

### ISSUE THREAD

**Issue by danechitoaie** [actions/checkout#72]
Hi,

Opening a separate issue based on discussion from #63 
It would be really nice if checking out with a SSH key would also be supported.
It would make things a bit more secure. With a PAT you basically give access to all the repos that user has access. With a SSH key you could give access only to the specific repo the SSH key is setup for.
It can be a new input option to the checkout action that would temporarily (for the duration of the checkout action) create the `~/.ssh/id_rsa` file with what was provided as input, use that for `git clone` and then restore the previous `~/.ssh/id_rsa` (if any) after current checkout task is done. 
Or maybe there's a better option.

**Comment by chrispat** [comment]
I think this could be very useful to have.

**Comment by gunnsth** [comment]
This would be great for working with submodules too, currently when updating the submodules pulls up the http GitHub user credentials rather than using the SSH key.  When working with the repository locally.

**Comment by ericsciple** [comment]
proposed here: https://github.com/actions/checkout/pull/156

**Comment by ericsciple** [comment]
related to https://github.com/actions/checkout/pull/178

**Comment by ericsciple** [comment]
A new input `ssh-key` is in master now. Gathering feedback on [this issue](https://github.com/actions/checkout/issues/176) before moving v2 tag forward.

**Comment by neyb** [comment]
this is issue is not dedicated to submodules, while #176 is not. So I decide to give a feedback here :

ssh-key does not work: (seems to be totally ignored, the repository is checkout as https, no key seems installed).

checkout is using https
<details><summary>logs</summary>
<p>
```
Run actions/checkout@v2
  with:
    ssh-key: ***
  
    repository: neyb/armor-hunter
    token: ***
    persist-credentials: true
    clean: true
    fetch-depth: 1
    lfs: false
  env:
    CI: true
Added matchers: 'checkout-git'. Problem matchers scan action output for known warning or error strings and report these inline.
Syncing repository: neyb/armor-hunter
Working directory is '/home/runner/work/armor-hunter/armor-hunter'
/usr/bin/git version
git version 2.25.1
Deleting the contents of '/home/runner/work/armor-hunter/armor-hunter'
/usr/bin/git init /home/runner/work/armor-hunter/armor-hunter
Initialized empty Git repository in /home/runner/work/armor-hunter/armor-hunter/.git/
/usr/bin/git remote add origin https://github.com/neyb/armor-hunter
/usr/bin/git config --local gc.auto 0
/usr/bin/git config --local --name-only --get-regexp http\.https\:\/\/github\.com\/\.extraheader
/usr/bin/git config --local http.https://github.com/.extraheader AUTHORIZATION: basic ***
/usr/bin/git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin +3d3a444d2f044fc97e440af1c3e2b4444e9dc0dc:refs/remotes/origin/master
remote: Enumerating objects: 99, done.        
remote: Counting objects:   1% (1/99)        

...


remote: Compressing objects:  97% (78/80)        
remote: Compressing objects:  98% (79/80)        
remote: Compressing objects: 100% (80/80)        
remote: Compressing objects: 100% (80/80), done.        
remote: Total 99 (delta 1), reused 52 (delta 0), pack-reused 0        
From https://github.com/neyb/armor-hunter
 * [new ref]         3d3a444d2f044fc97e440af1c3e2b4444e9dc0dc -> origin/master
/usr/bin/git checkout --progress --force -B master refs/remotes/origin/master
Reset branch 'master'
Branch 'master' set up to track remote branch 'master' from 'origin'.
/usr/bin/git log -1
commit 3d3a444d2f044fc97e440af1c3e2b4444e9dc0dc
Author: neyb <noo.blaster@gmail.com>
Date:   Sun Mar 15 09:38:21 2020 +0100

    fix: change origin url before deploy
Removed matchers: 'checkout-git'
```
</p>
</details>

**Comment by neyb** [comment]
still got a problem :

https://github.com/neyb/armor-hunter/runs/508953664#step:7:28

the ssk key seems not to accessible for other repositories

**Comment by ericsciple** [comment]
@neyb the SSH key isnt configured globally for the user. The SSH command is overwritten in the local git config. You could get it from the config and export to an env var if needed.

export GIT_SSH_COMMAND=$(git config --local --get remote.origin.url)

**Comment by ericsciple** [comment]
Thanks all for the feedback! I updated V2 to include the recent submodule/SSH changes from master.
