### ISSUE TITLE
Changes in microsoft ubuntu focal breaks the actions/workflow

### ISSUE THREAD

**Issue by ghassanmas** [actions/checkout#724]
Error when running `apt-get update && sudo apt-get install git`
focal InRelease' changed its 'Codename' value from 'focal' to 'testing' 

```
Reading package lists...
W: Conflicting distribution: https://packages.microsoft.com/ubuntu/20.04/prod focal InRelease (expected focal but got testing)
E: Repository 'https://packages.microsoft.com/ubuntu/20.04/prod focal InRelease' changed its 'Origin' value from 'microsoft-ubuntu-focal-prod focal' to 'microsoft-ubuntu-focal-prod testing'
E: Repository 'https://packages.microsoft.com/ubuntu/20.04/prod focal InRelease' changed its 'Label' value from 'microsoft-ubuntu-focal-prod focal' to 'microsoft-ubuntu-focal-prod testing'
E: Repository 'https://packages.microsoft.com/ubuntu/20.04/prod focal InRelease' changed its 'Codename' value from 'focal' to 'testing'
```

Relevant failed actions/workflows: [here](https://github.com/openedx/edx-platform/runs/5559969681?check_suite_focus=true) and [here](https://github.com/openedx/edx-platform/runs/5559969939?check_suite_focus=true) 
Also simlair issue reported microsoft/playwright-github-action/issues/63

**Comment by UsamaSadiq** [comment]
As per the discussion on the mentioned PR, this issue has already been fixed by microsoft organisation itself and the suggested approach in the pull request is not needed anymore for this issue.

**Comment by UsamaSadiq** [comment]
@ghassanmas seems like the mentioned issue has been fixed already so you can close this issue. Thanks.
