### ISSUE TITLE
Problem with checkout inside container

### ISSUE THREAD

**Issue by es1o** [actions/checkout#749]
Hello.
I have issue with checkout@v3

I run my job inside container, when container is updated I have always issue with checkout@v3.

Part of my action file:

```
jobs:
  myjob:

    runs-on: self-hosted
    container:
      image: XXXXXXXXXXXX.dkr.ecr.eu-west-1.amazonaws.com/XXXXXXX:builder
      credentials:
        username: ${{ secrets.ECR_USERNAME }}
        password: ${{ secrets.ECR_PASSWORD }}
      options: --user 1000

    steps:
      - name: Checkout
        uses: actions/checkout@v3
```
        
When my runner is pulling image (because i pushed newer version) it always fails with error:

```
/usr/local/bin/docker exec  1039cb92457dd5149f17d3e6f1354e2c70e73e255dfd4757e5d7179753aab397 sh -c "cat /etc/*release | grep ^ID"
##[debug]ID=alpine
##[debug]Container distribution is alpine. Running JavaScript Action with external tool: node16_alpine
OCI runtime exec failed: exec failed: container_linux.go:380: starting container process caused: exec: "/__e/node16_alpine/bin/node": stat /__e/node16_alpine/bin/node: no such file or directory: unknown
##[debug]Node Action run completed with exit code 126
##[debug]Finishing: Checkout
```

I tested many times and checkout step fails always when container is beeing pulled to runner.

This issue also exist in checkout@v2.

**Comment by es1o** [comment]
It was a problem with self-hosted runner, can be closed.

**Comment by denizhoxha** [comment]
Hi @es1o,

Can you please share how you solved it?

**Comment by williamdes** [comment]
For other users experiencing this issue, here is a comment that explains it better: https://github.com/actions/checkout/issues/334#issuecomment-1241306390
