### ISSUE TITLE
Runners send too many requests to clone repos. And this leads to a fatal error.

### ISSUE THREAD

**Issue by qhy040404** [actions/checkout#775]
[Workflow with error](https://github.com/qhy040404/DLUT-library-auto-reservation/actions/runs/2201893120)
This workflow is run twice. First time ```checkout``` was totally failed and the error code is ```http 429```
I re-ran the workflow. The repo's main file was successfully checkout, but the submodule was failed.

**Comment by qhy040404** [comment]
The issue should not be linked to this action. 
To be honest, this issue should be linked to GitHub's API. 
There is a limit to the frequency of API calls. 
And because of the limit, HTTP response returns 429

**Comment by vasireddy99** [comment]
@qhy040404 can you please point out to the repo please if that's possible? so I can add some context there.

**Comment by vasireddy99** [comment]
> The issue should not be linked to this action.
> To be honest, this issue should be linked to GitHub's API.
> There is a limit to the frequency of API calls.
> And because of the limit, HTTP response returns 429

@qhy040404 can you please point out to the repo please if that's possible? so I can add some context there.
