### ISSUE TITLE
Github actions/checkout@v2 failure with error  Error: fatal: No url found for submodule path 'abc' in .gitmodules   Error: The process '/usr/bin/git' failed with exit code 128

### ISSUE THREAD

**Issue by VarshaRuthu824** [actions/checkout#829]
<img width="1223" alt="Screenshot 2022-06-13 at 2 01 11 PM" src="https://user-images.githubusercontent.com/75168164/173312883-4c64afa0-9abe-4b94-bef0-30b12e4ffaab.png">

**Comment by jsoref** [comment]
This is technically a duplicate of #354

**Comment by matiasmartinez1129** [comment]
lo pudiste solucionar?
