### ISSUE TITLE
Marketplace page suggests using old version v2.4.2

### ISSUE THREAD

**Issue by rotu** [actions/checkout#831]
The [Marketplace Page](https://github.com/marketplace/actions/checkout) for this action is confusing (see screenshot). While the nominally latest version is 3 and the header says "Checkout V3", the default version is v2.4.2 and if you click the "use latest version" button that's the one you get.

![image](https://user-images.githubusercontent.com/119948/173889269-62a700c1-feb3-4ed8-948b-a398f082247d.png)

**Comment by rotu** [comment]
@vmjoseph Could you prioritize this? It's still an issue even after the latest release
<img width="1032" alt="Screenshot 2022-12-15 at 10 00 58" src="https://user-images.githubusercontent.com/119948/207908608-d0cb658f-a73d-42bb-8ffc-e5d3e29e00a9.png">

**Comment by cory-miller** [comment]
This has been updated. This usually happens when backporting and marking the backport as latest (the default experience in the UI). I made a note in the release runbook to uncheck this.
