### ISSUE TITLE
Where has commit SHA `d065129` gone?

### ISSUE THREAD

**Issue by jenstroeger** [actions/checkout#874]
Hello,

Github Actions that we’ve written and used in the past (both public and private repos) have been using this Action successfully, e.g. [here](https://github.com/jenstroeger/python-package-template/blob/e5a047f9b0eeef74d06250eb1b63f73c6b63849b/.github/workflows/codeql-analysis.yaml#L42-L43):
```yaml
    - name: Checkout repository
      uses: actions/checkout@d0651293c4a5a52e711f25b41b05b2212f385d28
```
During yesterday’s update, however, I noticed that [SHA `d065129` doesn’t actually exist](https://github.com/actions/checkout/commit/d0651293c4a5a52e711f25b41b05b2212f385d28):

![sha-d065129](https://user-images.githubusercontent.com/12053937/182046664-b957e866-138e-439e-96b1-fc489b123a8a.jpg)

I have two concerns here:
1. Where did that SHA go, did somebody rewrite history on the default branch?
2. Why does Github run the Action anyway ([run log](https://github.com/jenstroeger/python-package-template/runs/7595360007?check_suite_focus=true#step:4:26)) and what exactly is running then? (Although that’s a separate issue I’m [raising with Github](https://support.github.com/contact/bug-report).)

Rather curious about your explanation!
Thanks, Jens

**Comment by aparna-ravindra** [comment]
`d0651293c4a5a52e711f25b41b05b2212f385d28` is the SHA for the tag not commit.


$ git show-ref --tags
af513c7a016048ae468971c52ed77d9562c7c819 refs/tags/1.0.0
544eadc6bf3d226fd7a7a9f0dc5b5bf7ca0675b9 refs/tags/v1
af513c7a016048ae468971c52ed77d9562c7c819 refs/tags/v1.0.0
ec3afacf7f605c9fc12c70bc1c9e1708ddb99eca refs/tags/v1.1.0
a2ca40438991a1ab62db1b7cad0fd4e36a2ac254 refs/tags/v1.2.0
d171c3b028d844f2bf14e9fdec0c58114451e4bf refs/tags/v2
95784fc5bbede4a44d9abcfbde7a64f16e6dbedd refs/tags/v2-beta
722adc63f1aa60a57ec37892e133b1d319cae598 refs/tags/v2.0.0
01aecccf739ca6ff86c0539fbc67a7a5007bbc81 refs/tags/v2.1.0
86f86b36ef15e6570752e7175f451a512eac206b refs/tags/v2.1.1
aabbfeb2ce60b5bd82389903509092c4648a9713 refs/tags/v2.2.0
b4483adec309c0d01a5435c5e24eb40de5773ad9 refs/tags/v2.3.0
28c7f3d2b5162b5ddd3dfd9a45aa55eaf396478b refs/tags/v2.3.1
2036a08e25fa78bbd946711a407b529a0a1204bf refs/tags/v2.3.2
a81bbbf8298c0fa03ea29cdc473d45769f953675 refs/tags/v2.3.3
5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f refs/tags/v2.3.4
1e204e9a9253d643386038d443f96446fa156a97 refs/tags/v2.3.5
ec3a7ce113134d7a93b817d10a8272cb61118579 refs/tags/v2.4.0
f25a3a9f25bd5f4c5d77189cab02ff357b5aedeb refs/tags/v2.4.1
7884fcad6b5d53d10323aee724dc68d8b9096a2e refs/tags/v2.4.2
**d0651293c4a5a52e711f25b41b05b2212f385d28 refs/tags/v3**
a12a3943b4bdde767164f792f33f40b04645d846 refs/tags/v3.0.0
dcd71f646680f2efd8db4afa5ad64fdcba30e748 refs/tags/v3.0.1
2541b1294d2704b0964813337f33b291d3f8596b refs/tags/v3.0.2


cc: @TingluoHuang

**Comment by jenstroeger** [comment]
@aparna-ravindra oh I see… the `v3` tag is an [annotated tag](https://git-scm.com/book/en/v2/Git-Basics-Tagging#_annotated_tags) which has its own SHA `d065129`, and it refers to whatever commit is the latest of the version 3
```
> git show v3
tag v3
Tagger: GitHub <noreply@github.com>
Date:   Thu Apr 21 18:15:50 2022 +0000

Update v3 tag

commit 2541b1294d2704b0964813337f33b291d3f8596b (HEAD -> main, tag: v3.0.2, tag: v3, origin/main, origin/HEAD)
Author: Tingluo Huang <tingluohuang@github.com>
Date:   Thu Apr 21 10:29:04 2022 -0400

    Prepare changelog for v3.0.2. (#777)

diff --git a/CHANGELOG.md b/CHANGELOG.md
index cc333cf..230623b 100644
--- a/CHANGELOG.md
+++ b/CHANGELOG.md
@@ -1,5 +1,8 @@
 # Changelog
 
+## v3.0.2
+- [Add input `set-safe-directory`](https://github.com/actions/checkout/pull/770)
+
 ## v3.0.1
 - [Fixed an issue where checkout failed to run in container jobs due to the new git setting `safe.directory`](https://github.com/actions/checkout/pull/762)
 - [Bumped various npm package versions](https://github.com/actions/checkout/pull/744)
```
Or, as stored in `.git/packed-refs`
```
d0651293c4a5a52e711f25b41b05b2212f385d28 refs/tags/v3
^2541b1294d2704b0964813337f33b291d3f8596b
```
Thus, the above reference
```
actions/checkout@d0651293c4a5a52e711f25b41b05b2212f385d28
```
will always point at the latest of the version 3 releases.

Does that mean that with every version 3 related release you’ll point the `v3` tag at the latest commit?

**Comment by cory-miller** [comment]
This issue is quite old, but to answer the question the expectation is that users use Git tags to utilize the action. The latest major release is `actions/checkout@v4`
