### ISSUE TITLE
Minimum required git version is 2.18. Your git ('/usr/bin/git') is 2.17.1

### ISSUE THREAD

**Issue by kevinburkemeter** [actions/checkout#88]
Just posting in case anyone runs into this and looks in the wrong place. The actions/checkout step failed with this output:

```
/usr/bin/docker exec  2a47320f8dcb42acf77bde007d1695d03019f1ca5eb41d19d4bf6816053421c0 sh -c "cat /etc/*release | grep ^ID"
Running JavaScript Action with default external tool: node12
Added matchers: 'checkout-git'. Problem matchers scan action output for known warning or error strings and report these inline.
Syncing repository: owner/project
Working directory is '/__w/project/project'
/usr/bin/git version
git version 2.17.1
Removed matchers: 'checkout-git'
##[error]Minimum required git version is 2.18. Your git ('/usr/bin/git') is 2.17.1
##[error]Node run failed with exit code 1
```

The problem was I was using a custom Docker container with an outdated Git version installed. Update the Git version in the custom container and it should work again.

**Comment by ericsciple** [comment]
@kevinburkemeter thanks.

Also note, master moved forward today to reflect `actions/checkout@v2-beta` which adds the dependency on git version 2.18.

Whereas `actions/checkout@v1` has a lower min version requirement
