### ISSUE TITLE
Run git fetch with --quiet by default

### ISSUE THREAD

**Issue by Trass3r** [actions/checkout#894]
https://git-scm.com/docs/git-fetch#Documentation/git-fetch.txt--q

As has been noted before in the prematurely closed #489 and #18 the fetch progress does not add any value and just clutters the logs, esp. the raw logs.
The folding in the UI does not fix the issue for the raw logs.
And in general it's a waste of bandwidth and everything.

**Comment by gladiatr72** [comment]
The speed of the scroll makes it a race as to whether or not that segment can be closed before the control to close it is pushed from the display.

**Comment by simonbaird** [comment]
FYI I don't think `--quiet` is really needed. All that's required to squelch the noisy log output is to remove the `--progress` option. See #1067 where I've created a patch that should do it.
