### ISSUE TITLE
In master/v2 can no longer git rev-parse HEAD^ to get prior commit

### ISSUE THREAD

**Issue by ajcann** [actions/checkout#91]
Currently using packtracker which relies on being able to access the prior commit via `git rev-parse HEAD^` reverting to v1.2 works.

**Comment by dijam** [comment]
I have the same problem. For now, reverted from master to v1.

**Comment by ericsciple** [comment]
Setting [`fetch-depth: 2`](https://github.com/actions/checkout/blob/master/README.md#usage) should work

**Comment by ericsciple** [comment]
note, the reason is because `actions/checkout@v2` performance was optimized for the mainline scenario: fetch a single commit.

**Comment by ajcann** [comment]
Makes sense - thanks for the context! Happy to close this unless you'd like to keep it open.

**Comment by ericsciple** [comment]
@ajcann thanks for confirmation. I might leave this open for a little bit longer. I might add this as an example scenario in the readme
