### ISSUE TITLE
checkout-multiple-repos-side-by-side is not working

### ISSUE THREAD

**Issue by Rahulkhinchi03** [actions/checkout#918]
I want to check out another repository and I am doing it by SSH.

GitHub Workflow: [YML File](https://github.com/Rahulkhinchi03/checkstyle/actions/runs/2991280035/workflow#L17-L25)

Here is my TESTING: [GitHub Action](https://github.com/Rahulkhinchi03/checkstyle/runs/8183263907?check_suite_focus=true)

ERROR:
```
Please make sure you have the correct access rights
and the repository exists.
Cloning into 'checkstyle.github.io'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

```

**Comment by cory-miller** [comment]
I checked the repository and am not sure what workflow this is a reference to. The error itself also suggests it's a problem with the SSH key setup and not checkout. Closing.
