### ISSUE TITLE
Checkout is not cleaning properly after bad submodule added

### ISSUE THREAD

**Issue by dgerthe** [actions/checkout#933]
Steps to minimally reproduce:

1. Create a submodule incorrectly by cloning a repo then using git add <repo>
2. commit and push up that change, and there will be an **expected** error in checkout.
3. Go to a completely separate branch (main) and run a workflow that uses actions/checkout 
4. notice the same error in the other branch because of it running git submodule foreach --recursive git config ... in the "Setting up auth step"

I realize (now) that adding a submodule in this way is not correct, but I did not expect that it would propagate to causing a problem in **all** separate branch's CI

I had to fix this issue by going to each separate runner and deleting the cloned repo.

Just an idea of a fix would be if error on setting up auth, have it fall back to cloning the repo

Note that on runners with older git version where actions/checkout uses the github REST API this issue is not seen because it is basically doing a fresh clone.

![image](https://user-images.githubusercontent.com/94373338/192615445-bcd644cf-c804-4949-9505-65206d2314fd.png)

**Comment by 3Jz2** [comment]
JamalZabetan@gmail.com
