### ISSUE TITLE
is version 3.1.0 broken?

### ISSUE THREAD

**Issue by jamengual** [actions/checkout#944]
Yesterday the world was fine, today not so much.
To fix my issue today I just downgrade to V2, this literally worked yesterday and did not today.

Bad run: https://github.com/runatlantis/atlantis/actions/runs/3185910307/jobs/5196021098

Good run: https://github.com/runatlantis/atlantis/actions/runs/3185943896/jobs/5196059932

error: 
```
##[debug]Evaluating condition for step: 'Post Run actions/checkout@v3'
##[debug]Evaluating: always()
##[debug]Evaluating always:
##[debug]=> true
##[debug]Result: true
##[debug]Starting: Post Run actions/checkout@v3
##[debug]Loading inputs
##[debug]Evaluating: github.repository
##[debug]Evaluating Index:
##[debug]..Evaluating github:
##[debug]..=> Object
##[debug]..Evaluating String:
##[debug]..=> 'repository'
##[debug]=> 'runatlantis/atlantis'
##[debug]Result: 'runatlantis/atlantis'
##[debug]Evaluating: github.token
##[debug]Evaluating Index:
##[debug]..Evaluating github:
##[debug]..=> Object
##[debug]..Evaluating String:
##[debug]..=> 'token'
##[debug]=> '***'
##[debug]Result: '***'
##[debug]Loading env
Post job cleanup.
/usr/bin/docker exec  9ff[2](https://github.com/runatlantis/atlantis/actions/runs/3185910307/jobs/5196021098#step:9:2)8c2640f[3](https://github.com/runatlantis/atlantis/actions/runs/3185910307/jobs/5196021098#step:9:3)6d36de6e5ae0ffe0378b7672e70[4](https://github.com/runatlantis/atlantis/actions/runs/3185910307/jobs/5196021098#step:9:4)[5](https://github.com/runatlantis/atlantis/actions/runs/3185910307/jobs/5196021098#step:9:5)472288278dc5a2f[6](https://github.com/runatlantis/atlantis/actions/runs/3185910307/jobs/5196021098#step:9:6)6516c22 sh -c "cat /etc/*release | grep ^ID"
##[debug]ID=debian
##[debug]Running JavaScript Action with default external tool: node16
node:internal/fs/utils:344
    throw err;
    ^

Error: EACCES: permission denied, open '/__w/_temp/_runner_file_commands/save_state_2[7](https://github.com/runatlantis/atlantis/actions/runs/3185910307/jobs/5196021098#step:9:7)[8](https://github.com/runatlantis/atlantis/actions/runs/3185910307/jobs/5196021098#step:9:8)3dec5-b4f7-4[9](https://github.com/runatlantis/atlantis/actions/runs/3185910307/jobs/5196021098#step:9:9)c6-b083-53a8c72b0af3'
    at Object.openSync (node:fs:585:3)
    at Object.writeFileSync (node:fs:2153:35)
    at Object.appendFileSync (node:fs:2215:6)
    at Object.issueFileCommand (/__w/_actions/actions/checkout/v3/dist/index.js:2293:8)
    at Object.saveState (/__w/_actions/actions/checkout/v3/dist/index.js:11873:31)
    at Object.153 (/__w/_actions/actions/checkout/v3/dist/index.js:4044:[10](https://github.com/runatlantis/atlantis/actions/runs/3185910307/jobs/5196021098#step:9:10))
    at __webpack_require__ (/__w/_actions/actions/checkout/v3/dist/index.js:22:30)
    at Object.287 (/__w/_actions/actions/checkout/v3/dist/index.js:70[13](https://github.com/runatlantis/atlantis/actions/runs/3185910307/jobs/5196021098#step:9:13):34)
    at __webpack_require__ (/__w/_actions/actions/checkout/v3/dist/index.js:22:30)
    at Object.853 (/__w/_actions/actions/checkout/v3/dist/index.js:3[18](https://github.com/runatlantis/atlantis/actions/runs/3185910307/jobs/5196021098#step:9:18)01:36) {
  errno: -13,
  syscall: 'open',
  code: 'EACCES',
  path: '/__w/_temp/_runner_file_commands/save_state_[27](https://github.com/runatlantis/atlantis/actions/runs/3185910307/jobs/5196021098#step:9:27)83dec5-b4f7-49c6-b083-53a8c72b0af3'
}
##[debug]Node Action run completed with exit code 1
##[debug]Finishing: Post Run actions/checkout@v3
```

Thanks.

**Comment by jamengual** [comment]
new run on 3.0.2

https://github.com/runatlantis/atlantis/actions/runs/3185997771/jobs/5196164236

**Comment by rentziass** [comment]
Thank you for reporting this, looking into this now!

**Comment by rentziass** [comment]
We are repointing `v3` to `v3.0.2` while we look into this.

**Comment by bel0v** [comment]
We're also facing the same unzipping error ^ 
```Can't use 'tar -xzf' extract archive file```

**Comment by Loic-Hakisa** [comment]
Same error here : 

Download action repository 'actions/checkout@v3' (SHA:2541b1294d2704b0964813337f33b291d3f8596b)
Error: Can't use 'tar -xzf' extract archive file:

**Comment by xSAVIKx** [comment]
It looks like the whole GH universe is going to add their copy of the error here :-D We have hundreds of failed builds, but I personally am not sure the action is the problem.

**Comment by sh-TU** [comment]
same here 
```
Error: Can't use 'tar -xzf' extract archive file: . return code: 2.
```

**Comment by MarijnS95** [comment]
> Still broken here https://github.com/nearform/sql/actions/runs/3196327180/jobs/5218105824

This is a failure to download the tar archive at 2541b1294d2704b0964813337f33b291d3f8596b from the `v3` / `v3.0.2` tag, which is different from the issue reported here. Could it perhaps be related to [the tag being repointed](https://github.com/actions/checkout/issues/944#issuecomment-1268184447)?

Alas, it simply seems that the tarball returned by https://github.com/actions/checkout/tarball/2541b1294d2704b0964813337f33b291d3f8596b is empty:

```console
$ file ~/Downloads/actions-checkout-v3-0-g2541b12.tar.gz
~Downloads/actions-checkout-v3-0-g2541b12.tar.gz: empty
```

**Comment by trevorah** [comment]
For those that are getting the `Can't use 'tar -xzf' extract archive file` when using `actions/checkout@v3`, we've found that switching to `actions/checkout@v3.1.0` has fixed it for us.

**Comment by christian-steinmeyer** [comment]
we ran into the tar issue and are pointing to `actions/checkout@v3`

**Comment by bel0v** [comment]
> switching to actions/checkout@v3.1.0 has fixed it for us.

Unfortunately this didn't work in our case

<img width="777" alt="Screenshot 2022-10-06 at 11 36 28" src="https://user-images.githubusercontent.com/2889382/194292175-cc4cff4e-c4ec-43cd-8543-4322af0fbbad.png">

**Comment by casperbakker** [comment]
Seems like everyone with problems is running `ubuntu-20.04`. I think Github has launched a new version of that container that is broken. We fixed it with moving to `ubuntu-22.04`, but it was an intermitted problem on 20.04 so who knows how long it will work.

I think we have to wait for Github to fix it.

**Comment by ssbarnea** [comment]
@casperbakker I wonder how long does it takes for them to report the outage, if they will ever do it.

**Comment by bel0v** [comment]
No luck with ubuntu-22.04 either :/ 
<img width="436" alt="Screenshot 2022-10-06 at 11 43 15" src="https://user-images.githubusercontent.com/2889382/194293502-fe7fcce3-1419-43cd-95d7-d4b909a987d1.png">

**Comment by ssbarnea** [comment]
I confirm that bump to `v3.1.0` did sort the issue for me.

**Comment by brotich** [comment]
deployed a walkaround on my end using:

- checkout action v3.1.0
- using ubuntu-22-04 as the OS
i am not sure of both changes are needed, or just the updated of the `actions/checkout@v3.1.0`

**Comment by mcalthrop** [comment]
> @casperbakker I wonder how long does it takes for them to report the outage, if they will ever do it.

@ssbarnea It's been reported, a few minutes ago:
https://www.githubstatus.com/incidents/gq1x0j8bv67v

> We identified an issue with the checkout action download which was causing elevated actions failures. We have performed some mitigations and are continuing investigation.

**Comment by fhammerl** [comment]
@jamengual @ollie-etl 

Thanks for reporting this so quickly!

## Summary

In short: the jobContainers in these workflows seem to follow an [unsupported path](https://docs.github.com/en/actions/creating-actions/dockerfile-support-for-github-actions#user). Namely,

> Do not use the USER instruction in your Dockerfile, because you won't be able to access the GITHUB_WORKSPACE

I believe the jobContainer operates as the user 'circleci' in the [workflow](https://github.com/runatlantis/atlantis/actions/runs/3185910307/jobs/5196021098) you linked.

**We will roll out the changes again as we haven't seen issues with the officially supported paths.** 

**It is recommended 'not use the USER instruction in your Dockerfile'.** 
In most cases, this means 'run the container as root'.

I understand this introduces some friction, so see below for workarounds and a technical summary.

## Detailed Summary

1. In actions/checkout@3.1.0, we began phasing out the use of some [workflow commands](https://github.com/actions/checkout/pull/939#:~:text=Update%20state%2Dhelper%20to%20use%20the%20new%20saveState/getState%20functions%20from%20%40actions/core) that **write to stdout** with functions that **write to temp files** instead.
2. If you're running in a jobContainer, these temp files are **created by the runner app on your host OS** and are **owned by the user who started the runner** (in case of `ubuntu-latest`, this user is 'runner' with `UID-1001`). These files are then **mounted to your jobContainer**.
3. `actions/checkout` is a `.js` file executed using `node` on your jobContainer. As per the changes in `1.`, `actions/checkout@v3.1.0` attempts to write to these temp files on your jobContainer. 

 
This can have a couple of outcomes:
1. If the jobContainer user is 'root': writes successfully.
2. If the jobContainer user is _NOT_ 'root':
  a) If the UID of the jobContainer user == UID of host runner user (`UID-1001` on `ubuntu-latest`): write is successful
  b) If the UID of the jobContainer user != UID of host runner user (`UID-1001` on `ubuntu-latest`): permission denied

The jobContainers in the above workflow seem to run into 2/b.

## Fix

As per the [docs](https://docs.github.com/en/actions/creating-actions/dockerfile-support-for-github-actions#user), don't modify the default user in the Dockerfile. If that's not feasible for you: 👇

## Workarounds (unsupported)

- Use `actions/checkout@v3.0.1` in your workflow (will be deprecated)
- Match the UID of the host runner user (e.g. UID-1001 on ubuntu-latest today) to the UID of the user on the jobContainer
- Override the default container user and use 'root':
```    
container: 
    image: alpine:latest
    options: --user root
```

**We will roll out the changes again as we haven't seen issues with the officially supported paths.**
