### ISSUE TITLE
Why is v2.5.0 "newer" than v3.1.0

### ISSUE THREAD

**Issue by aarcro** [actions/checkout#970]
Seriously.

**Comment by TWiStErRob** [comment]
#wrongforum ;)

It's a maintenance release to reduce [warnings](https://github.com/actions/checkout/issues/959) in the ecosystem. It just happened to be *released* after 3.1.0, which puts it as the latest release in the Releases view. This should work itself out in a few weeks when they publish 3.2 or 3.1.x.

@rentziass you might want to re-tag 3.1.0 so it's on top, but it might involve force pushing or recreating the tag/release.

**Comment by rentziass** [comment]
I'd refrain from changing history, v2.5.0 was indeed our latest release but it was only a backport to help v2 users not get swamped with warnings. Thanks for the help @TWiStErRob!

**Comment by taig** [comment]
https://github.blog/changelog/2022-10-21-explicitly-set-the-latest-release/

**Comment by TWiStErRob** [comment]
No way! 😂
