### ISSUE TITLE
Add a CONTRIBUTING file

### ISSUE THREAD

**Issue by jeffwidman** [actions/checkout#982]
While opening #981, I had a [question re: whether I needed to manually run a compilation step](https://github.com/actions/checkout/pull/981#issuecomment-1288406634) and include the generated code in my PR.

I searched for instructions in a [`CONTRIBUTING` file](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors), but couldn't find anything.

So please add one! 😀

**Comment by cory-miller** [comment]
I've started one at https://github.com/actions/checkout/blob/main/CONTRIBUTING.md with steps to get your change ready for review.
