### ISSUE TITLE
Cloning a repo with Token fails 'could not read Username for 'https://github.com': terminal prompts disabled'

### ISSUE THREAD

**Issue by burninmedia** [actions/checkout#997]
There was a breaking change to this about 2 weeks ago.
code
`- name: Checkout Code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.SA_PAT_PUSH }}`

This used to clone correctly. now it fails with 
could not read Username for 'https://github.com': terminal prompts disabled'

**Comment by pmcilwaine** [comment]
Regenerating the token resolved this for me.

**Comment by burninmedia** [comment]
yup expired token. I could have sworn I set 1 year to expire.
